### ISSUE TITLE
New Plugin $Display type: Graph

### ISSUE THREAD

**Issue by Sneddo** [alanrenouf/vCheck-vSphere#145]
This one is a long way off, but I think we should aim to support graphs as an output now that the resource code is pretty much done. Probably a 7.x release goal, but logging to get ideas flowing.

Will need to investigate different graphing APIs.
- Features and styling
- Graph types (pie, bar, line, etc)
- Local vs remote graph generation
- Embed image in report vs HTML reference

From memory Google has one that you can specify the graph parameters via URL, and we can download the resulting image to include in the report, or include in img tags.

**Comment by alanrenouf** [comment]
Did you have a sample plugin for this? I cant find "Test Chart.ps1" anywhere?

**Comment by alanrenouf** [comment]
Dont worry, worked it out
