### ISSUE TITLE
How can vC show all four paths up and the script continue to show only 2?

### ISSUE THREAD

**Issue by dennietidwell** [alanrenouf/vCheck-vSphere#201]
I am running a customized version of the "81 LUN Paths Check" as well as on daily reports. I started getting reports showing only 2 paths from the regular 4 paths. I checked over and over with vmfs and hba scans ... and then rerunning the reports.

I continue to get one cluster with all nodes showing only 2 paths instead of the standard 4 that they have always had. Storage group does re-pathing that requires us to rescan but they have always done so with no issues and reports return to normal after rescans.

This has been going on now for 4 days. One cluster of esxi nodes continues to come up in vchecks as having only 2 paths. I check every one in vC client and all four paths are good on every LUN.

I have had issues with hardware errors getting "hung" in reports but clearing in vC. This went on for months on hardware issue on one node - I did some clearing actions per an article - no luck - finally it just went away.

Does the powercli script read from different area than the cCenter client? How can it show all four paths up and the script continue to show only 2?

**************
	$missingpaths = @() 
	foreach ($esxhost in ($HostsViews | where {$_.Runtime.ConnectionState -match "Connected|Maintenance"})) {
	  #Write-Host $esxhost.Name
		$lun_array = @() # 2D array - LUN Name & Path Count
		$esxhost | %{$_.config.storageDevice.multipathInfo.lun} | %{$_.path} | ?{$_.name -like "fc.*"} | %{
			$short_path_array = $_.name.split('-')
			$short_path = $short_path_array[2]
			$found = $false
			foreach ($lun in $lun_array) {
				if ($lun[0] -eq $short_path) {
					$found = $true
					$lun[1]++
				}
			}
			if (!($found)) {
				$lun_array +=(,($short_path,1))
			}
		}

		#Create report for ESX host
		foreach ($lun in $lun_array) {
			if ($lun[1] -lt $RecLUNPaths) {
				#Write-Host "Alerting due to lack of paths (" $lun[1] "looking for" $RecLUNPaths "), for LUN: " $lun[0]
				$myObj = "" | Select ESXHost, LUN , Paths
				$myObj.ESXHost = $esxhost.Name
				$myObj.LUN = $lun[0]
				$myObj.Paths = $lun[1]
				$missingpaths += $myObj
			}
		}
	}

	$ArchiveFilePath = "C:\tempCheckDead\"
	if (-not (Test-Path -PathType Container $ArchiveFilePath)) { New-Item $ArchiveFilePath -type directory | Out-Null }

	$missingpaths | ConvertTo-Html –body "<H3>Paths less than $RecLUNPaths</H3>" | Out-File -append $filelocation
	$deadluns | ConvertTo-Html –body "<H3>Dead LUNs</H3>" | Out-File -append $filelocation

	# Disconnect session from VC
	disconnect-viserver -confirm:$false

	Invoke-Item $filelocation

**Comment by Sneddo** [comment]
No updates since May 2014, closing this off. Please raise another issue if you still have trouble
