### ISSUE TITLE
Issue with uncontrolled snapshot report

### ISSUE THREAD

**Issue by sahayward** [alanrenouf/vCheck-vSphere#208]
Recently started using vCheck and finding it really useful. However, have just found a slight issue with the Uncontrolled Snapshot report. We have a machine called VFDELTA which is reported as having an uncontrolled snapshot. The machine doesn't have any snapshots, the report seems to be detecting the actual vmdk file for the OS drive, presumeably because the last 6 characters (including the . ) of the vmdk file are delta. 

I haven't really used powershell before, but found the following in the 106 Find Phantom Snapshots.ps1 scripts:

if ($theVMdisk.Filename -match "-\d{6}.vmdk")

Is it possible to edit this line to look for -delta.vmdk files rather than delta.vmdk? and if so, what would I need to change.

Thanks,

Simon

**Comment by Sneddo** [comment]
No Update since May 2014 - closing this ticket. Please log another issue if you still have this problem.
