### ISSUE TITLE
vCheck Functions --> Modules

### ISSUE THREAD

**Issue by Zsoldier** [alanrenouf/vCheck-vSphere#223]
Reading through so many of the checks seems to include functions.  Can we start to think about consolidating all these disparate functions into more 'generic' advanced functions as vCheck modules.  Feels like there might be lots that can be consolidated and shared among plug-in builders.  Thoughts?

**Comment by vScripter** [comment]
Marking this as an enhancement and closing it out. This request should be handled in a future release as we move towards converting vCheck, itself, and all plugins to one main Module, with sub-modules for each plugin.

**Comment by PaulWalkerUK** [comment]
@vScripter : Did you ever manage to get anywhere in converting this to modules/sub-modules?
