### ISSUE TITLE
VMKernel Warnings - tweak?

### ISSUE THREAD

**Issue by BigBen1** [alanrenouf/vCheck-vSphere#225]
Hi,

Would it be possible or how can I tweak the following Vcheck plugin:

44 VMKernel Warnings.ps1

I would like to refine it to show only warnings in the last day and most importantly show the time stamp of the warnings in Local Time not UTC/Zulu time. Would make my life much easier when trying to work out what else may be happening at the time of the warning.

Thanks

**Comment by vScripter** [comment]
Closing this out. We should be converting object properties that contain date/time information into proper PowerShell/.NET `[DateTime]` objects, which should at least help resolve this for you (it would at least give you the ability to leverage PowerShell to automate the conversion).
