### ISSUE TITLE
Script not digitally signed?

### ISSUE THREAD

**Issue by Medikdave** [alanrenouf/vCheck-vSphere#227]
I'm running the latest vCheck version on a Server 2012 R2 server, with PowerCLI 5.5 release 2.  I've got the ExecutionPolicy set to RemoteSigned, and I'm still getting the error that the vCheck script is not digitally signed.  The only way I can get it to run is to bypass security.  I didn't have this issue in the past, so I just want to make sure nothing has changed.  Thank you.

![image](https://cloud.githubusercontent.com/assets/8027672/3431038/f0ef128e-0066-11e4-9fd7-ae234a92c7c0.png)

**Comment by StephenSo** [comment]
Or run this in the vCheck folder root to clean the files...
$files = Get-ChildItem -Recurse -Include *.ps1
foreach ($file in $files){
	$content = Get-Content $file
	$content | Out-File -FilePath $file.fullname }

**Comment by pshearduk** [comment]
Thank You StephenSo
