### ISSUE TITLE
Issue - Capacity Planning - Attempted to divide by zero

### ISSUE THREAD

**Issue by tiyab** [alanrenouf/vCheck-vSphere#234]
Hi,
for the plugin 71-Capacity Planning, if there is a cluster with no host (for example when you create a new cluster and there is no new hosts yet) the plugin try to do a division by zero.
it should have something like " if ($cluv.Summary.NumHosts -ne 0) " at line 12.

**Comment by vScripter** [comment]
Without digging too deep, yet, I agree that it seems to be an issue with trying to divide by zero, which needs to be fixed by adding some value validation, as suggested.

**Comment by vScripter** [comment]
See Pull Request #383, which should have resolved this issue. As of today (5/5/15), please download the code from the Dev branch, or wait until a new release is pushed to the 'Master' branch.

**Comment by Sneddo** [comment]
@nevs55 reported another potential divide by zero issue - seems to be if a cluster has no VMs.

```
Attempted to divide by zero.
At D:\Scripts\vCheck\Plugins-virt\20 Cluster\71 Capacity Planning.ps1:25 char:39

$VmCpuAverage = $CluCpuUsageAvg/ <<<< ($cluvmlist.count)
CategoryInfo : NotSpecified: (:) [], RuntimeException
FullyQualifiedErrorId : RuntimeException
Attempted to divide by zero.
At D:\Scripts\vCheck\Plugins-virt\20 Cluster\71 Capacity Planning.ps1:35 char:39

$VmMemAverage = $CluMemUsageAvg/ <<<< (Get-Cluster $cluv.name|Get-VM).count
CategoryInfo : NotSpecified: (:) [], RuntimeException
FullyQualifiedErrorId : RuntimeException
```
