### ISSUE TITLE
Limit to specific vDC or cluster?

### ISSUE THREAD

**Issue by cwegener** [alanrenouf/vCheck-vSphere#275]
I tried to figure out how to limit the vCheck to a particular vDC or cluster, but could find out how I could achieve that.
Some vCenter servers have dozens of virtual data centers with dozens of clusters all over the world. Specifying a vDC scope or cluster scope would be extremely beneficial in these scenarios.

**Comment by rgarrigue** [comment]
:+1: for a filter feature !

**Comment by andrei-iancu** [comment]
:+1: for a filter feature !

**Comment by vScripter** [comment]
Marked as enhancement request for future version; there have been other issues with similar requests.

**Comment by vScripter** [comment]
Closing this out; feature can be tacked via issue #169
