### ISSUE TITLE
Cluster Slot size report inaccurate with certain policies

### ISSUE THREAD

**Issue by Sneddo** [alanrenouf/vCheck-vSphere#292]
Plugin /20 Cluster/18 Cluster Slot Sizes.ps1 returns false positives when using resource reservations (and possibly dedicated failover hosts?) as slot sizes are not calculated.

There should be a check to determine what admission control policy is in use.

**Comment by vScripter** [comment]
PR #382 resolved this issue. As of today (5/5/15), please download the code from the Dev branch, or wait until a new release is pushed to the Master branch.
