### ISSUE TITLE
Question: How to upgrade vCheck?

### ISSUE THREAD

**Issue by kars85** [alanrenouf/vCheck-vSphere#293]
Probably a simple question, but what are folks doing when the upgrade vCheck to the latest release?  We are on 6.15.  We currently have 5 vCenters with a weekly vCheck that runs a slimmed down report with minimal plugins, along with a monthly that is more complete (still has some plugins disabled).

Are there certain configuration files/dirs that can be safely left as-is?

I'd like to do this using the least time investment as possible, for obvious reasons :)

Thanks!

**Comment by Sneddo** [comment]
This will be simplified in version 7.0 with changes discussed in issue #361.

For now, the above procedure should work.
