### ISSUE TITLE
Send E-mail Does Not Work in vCheck.ps1

### ISSUE THREAD

**Issue by MasterChiefJon** [alanrenouf/vCheck-vSphere#299]
If I set vCheck to send an e-mail, version 6.22-Alpha-9 no longer sends it.  I've found that if I change line 746 back to what it used to be (  if ($SendEmail) {  ), then the e-mail sends just fine.  So the problem appears to be either the $EmailReportEvenIfEmpty variable or the $PluginResult Count calculation.

In my GlobalVariables file, I have $SendEmail = $true and $EmailReportEvenIfEmpty = $true

**Comment by PaulWalkerUK** [comment]
I don't mind trying to get this working - I was thinking of adding a similar `$DisplayReportEvenIfEmpty` anyway.

**Note to self**
Parameter first implemented: #119
Sneddo's implementation: b0976a07f2001f2e708ab80ff0f321266a2c30af
Sneddo's backout: 53516d386c8f7bfd5a7ad4647b00c08eb5d61695

**Comment by Sneddo** [comment]
This should now be closed with pull #329
