### ISSUE TITLE
NTP Server plugin check displays wrongly in the report

### ISSUE THREAD

**Issue by akarthikeyan16** [alanrenouf/vCheck-vSphere#303]
Hi ,

I have added the NTP Server IP addresses in NTP Name and service plugin however in the report its says  NTP server ip is not matching eventhough it is correct in HOst. So am wondering where i have made mistake. I have attached the screenshot below of the sample NTP report .

I have separated the NTP Server ipaddress by "|" also tried with "," but still same result

Please advise,

Thanks,
Ak

**Comment by haripetrov** [comment]
@akarthikeyan16 would it be possible for you to paste here the configuration of the plugin and also the output of the plugin? From the screenshot is not clear what happened in your case.
