### ISSUE TITLE
Change job plugin paths routine so it still works with PowerShell 2.0

### ISSUE THREAD

**Issue by rkleijwegt** [alanrenouf/vCheck-vSphere#306]
Dear @sneddo,

Today I started experimenting with the job parameter and updated my vCheck to the latest commit on GitHub 617e20c582b33a3ba9acc2d6037ee6994fa40b67. I noticed that in 6.22-Alpha-5 df32f73b7c06a992667ff8df1a323ad81c794d51 of the vCheck script you [changed the way that the plugin paths are handled](https://github.com/alanrenouf/vCheck-vSphere/blob/df32f73b7c06a992667ff8df1a323ad81c794d51/vCheck.ps1#L572).

Unfortunately you used a '-Directory' parameter on the Get-ChildItem Cmdlet which is only supported from PowerShell 3.0 and upwards. Now you might ask, why don't you just upgrade to PowerShell 3.0 or even 4.0? Well..... I tried this and for some reason this turned out to be a complete nightmare on my Windows instance.

As an alternative I changed my local vCheck copy so it will still work with PowerShell 2.0:

```powershell
$PluginPaths += Get-Childitem $PluginPath -recurse | ?{ $_.PSIsContainer } | Select -expandproperty FullName
```
Can you please update the public vCheck version to include this tiny enhancement?

You're not only doing me a big favor, @alanrenouf won't have to change his [vCheck webpage](http://www.virtu-al.net/vcheck-pluginsheaders/vcheck/) to reflect the changed prerequisites (currently PowerShell V2) this way.

Mayby I could have done it myself, but I'm a GitHub newbie so I have no idea how to submit a change.

**Comment by rkleijwegt** [comment]
I read some of the GitHub documentation on how to contribute to a project and I think I was able to fix it myself. Please let me know if I did this in the correct way.

**Comment by Sneddo** [comment]
Awesome work @rkleijwegt. I've merged your pull request so I think we can close this off :)

**Comment by rkleijwegt** [comment]
Thanks @Sneddo! I've been a vCheck user for years so I'm glad I can finally do something in return. 

Today I noticed that the [prerequisites for PowerCLI are about to change](http://blogs.vmware.com/PowerCLI/2014/11/announcement-changes-future-powercli-prerequisites.html). So the code you wrote would have worked by default eventually. :confounded:

However I think it is best to keep certain degree of backwards compatibility if possible.
