### ISSUE TITLE
Change Report on Plugins to reflect plugins selected in job file

### ISSUE THREAD

**Issue by rkleijwegt** [alanrenouf/vCheck-vSphere#307]
I just succesfully ran my first vCheck session using a job file. However one of the enabled plugins was the 'Report on Plugins'. This now shows all plugins that are enabled (ie. don't have the disabled file extension). But I would like it to report on the plugins enabled through the job file. Otherwise it's a bit pointless for me to include the Report on Plugins plugin.

**Comment by Sneddo** [comment]
Not a bad idea. I actually want to merge this into the vCheck script as I think it makes more sense (Same as the time to run section). Will try to get to this next week unless someone else does :)

**Comment by Sneddo** [comment]
OK, so I've done a bit of work on this- are you able to test for me?

Grab vCheck.ps1 from here:
https://raw.githubusercontent.com/Sneddo/vCheck-vSphere/master/vCheck.ps1

Add the following to your GlobalVariables.ps1 (change values to suit):
    # Do you want to include plugin details in the report?
    $reportOnPlugins = $true
    # List Enabled plugins first in Plugin Report?
    $ListEnabledPluginsFirst = $true

Now, run vCheck as normal.

I've done a pull request for these updates, just need someone to test it a bit more than I have time to do at the moment!

**Comment by Sneddo** [comment]
Fixed with Pull #352
