### ISSUE TITLE
vCenter session age plugin

### ISSUE THREAD

**Issue by rkleijwegt** [alanrenouf/vCheck-vSphere#311]
As vCenter sessions require resources on the vCenter server monitoring idle sessions is desired especially on large scale enviromnents. I'll add a plugin to report on idle sessions with a configurable maximum age.

**Comment by Sneddo** [comment]
Thanks for the plugin. Just going to track a couple of tweaks for v1.1 in this Issue:
- $ServiceInstance is already defined in the connection plugin. We should assume that this is valid, so you can get rid of the connectivity checks.
- Lines 18/19 are a bit redundant and could just be replaced by $Result | Sort LoginTime
- Add nice timespan formatting similar to vCenter

**Comment by Sneddo** [comment]
This should be pretty much covered off with some other changes to this plugin.
