### ISSUE TITLE
Allow vCheck to send SMTP messages using a non-default TCP port

### ISSUE THREAD

**Issue by rkleijwegt** [alanrenouf/vCheck-vSphere#312]
I started working on some vCheck improvements on a test environment that does not allow SMTP messages using the default TCP port 25. Thankfully the Microsoft .NET SmtpClient lets you [configure the TCP port] (http://msdn.microsoft.com/en-us/library/system.net.mail.smtpclient.port%28v=vs.110%29.aspx) to be used. A few simple additions to vCheck and the GlobalParameters scripts makes these options available to the vCheck users.

**Comment by rkleijwegt** [comment]
Ahw crap! I seemed to have missed commit 80420424807724770f8f2aff262b6fe5de2618f8 on my test environment. Non-default TCP port configuration for SMTP is already added to vCheck.

**Comment by rkleijwegt** [comment]
Alright, commit 80420424807724770f8f2aff262b6fe5de2618f8 only allows you to configure a non-default vSphere port. Re-opening the issue.

**Comment by Sneddo** [comment]
OK, just pushed a commit for this. Now $SMTPSRV supports servername:port notation :)
