### ISSUE TITLE
72 s-vMotion Information.ps1 tweaks

### ISSUE THREAD

**Issue by beefy147** [alanrenouf/vCheck-vSphere#318]
I love this script but am trying to accomplish the following. I only want the output to show storage vmotions and not vmotions and to exit out if there is nothing to report (e.g. no svmotions). I also want to include the datastore it came from and moved to. I think only minor changes would make this possible.

**Comment by Sneddo** [comment]
Hey, I haven't had a chance to test this- can you grab a copy from my repo and test if this works?
https://github.com/Sneddo/vCheck-vSphere/blob/master/Plugins/20%20Cluster/72%20s-vMotion%20Information.ps1

There's two new settings for if you want to include SvMotions and vMotion info. It should also show the applicable source and destination entity.
