### ISSUE TITLE
Running vCheck on VSphere 5.5

### ISSUE THREAD

**Issue by zoltancse** [alanrenouf/vCheck-vSphere#319]
I am in the process of getting the vCheck install in the Vsphere 5.5 environment. I have all the PowerCli installers installed but still get some errors.. Figure if i get these i think will clean up others.

Begin Plugin Processing
[12:46:55] ..start calculating Connection settings for vCenter by Alan Renouf v
.5 [1 of 106]
[12:46:55] Connecting to VI Server
Connect-VIServer : Method not found: 'Boolean VMware.VimAutomation.Sdk.Util10.C
ommonUtil.IsEmpty(System.Collections.IEnumerable)'.
At C:\VMscripts\vCheck-vSphere-master\Plugins\00 Initialize\00 Connection Plugi
n for vCenter.ps1:62 char:34
+     $VIConnection = Connect-VIServer <<<<  -Server $VIServer -Port $Port
    + CategoryInfo          : NotSpecified: (:) [Connect-VIServer], MissingMet
   hodException
    + FullyQualifiedErrorId : System.MissingMethodException,VMware.VimAutomati
   on.ViCore.Cmdlets.Commands.ConnectVIServer

C:\VMscripts\vCheck-vSphere-master\Plugins\00 Initialize\00 Connection Plugin f
or vCenter.ps1 : Unable to connect to vCenter, please ensure you have altered t
he vCenter server address correctly. To specify a username and password edit th
e connection string in the file $GlobalVariables
At C:\VMscripts\vCheck-vSphere-master\vCheck.ps1:667 char:53
+     $TTR = [math]::round((Measure-Command {$Details = . <<<<  $_.FullName}).T
otalSeconds, 2)
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,00 Connection Plugin for vCenter.ps1

[12:46:55] Adding Custom properties
[12:46:56] Collecting VM Objects
Get-VM : 1/14/2015 12:46:56 PM    Get-VM        Method not found: 'Boolean VMwa
re.VimAutomation.Sdk.Util10.CommonUtil.IsEmpty(System.Collections.IEnumerable)'
.
At C:\VMscripts\vCheck-vSphere-master\Plugins\00 Initialize\00 Connection Plugi
n for vCenter.ps1:113 char:13
+ $VM = Get-VM <<<<  | Sort Name
    + CategoryInfo          : NotSpecified: (:) [Get-VM], VimException
    + FullyQualifiedErrorId : Core_BaseCmdlet_UnknownError,VMware.VimAutomatio
   n.ViCore.Cmdlets.Commands.GetVM

[12:46:56] Collecting VM Host Objects
Get-VMHost : 1/14/2015 12:46:56 PM    Get-VMHost        Method not found: 'Bool
ean VMware.VimAutomation.Sdk.Util10.CommonUtil.IsEmpty(System.Collections.IEnum
erable)'.
At C:\VMscripts\vCheck-vSphere-master\Plugins\00 Initialize\00 Connection Plugi
n for vCenter.ps1:115 char:18
+ $VMH = Get-VMHost <<<<  | Sort Name
    + CategoryInfo          : NotSpecified: (:) [Get-VMHost], VimException
    + FullyQualifiedErrorId : Core_BaseCmdlet_UnknownError,VMware.VimAutomatio
   n.ViCore.Cmdlets.Commands.GetVMHost

Thanks

**Comment by Sneddo** [comment]
Yeah,  looks like something failing on the vCenter connection. Can you run Connect-VIserver manually and see if you have the same issue?

**Comment by zoltancse** [comment]
Yes I get the following:

PowerCLI C:\Program Files (x86)\VMware\Infrastructure\vSphere PowerCLI> Connect-
VIServer

cmdlet Connect-VIServer at command pipeline position 1
Supply values for the following parameters:
Server[0]: cmhpvcntw001
Server[1]:
Connect-VIServer : Method not found: 'Boolean VMware.VimAutomation.Sdk.Util10.C
ommonUtil.IsEmpty(System.Collections.IEnumerable)'.
At line:1 char:17
+ Connect-VIServer <<<<
    + CategoryInfo          : NotSpecified: (:) [Connect-VIServer], MissingMet
   hodException
    + FullyQualifiedErrorId : System.MissingMethodException,VMware.VimAutomati
   on.ViCore.Cmdlets.Commands.ConnectVIServer

PowerCLI C:\Program Files (x86)\VMware\Infrastructure\vSphere PowerCLI>

**Comment by Sneddo** [comment]
It seems like an issue with your PowerCLI install not with vCheck.

Try reinstalling PowerCLI and updating .NET

Perhaps try posting in the VMware communities, you may get a better response over there: https://communities.vmware.com/community/vmtn/automationtools/powercli

Failing that, you should be able to raise a support call with VMware.
