### ISSUE TITLE
Ignore / Exclusion List

### ISSUE THREAD

**Issue by bkingx** [alanrenouf/vCheck-vSphere#320]
Is there a way to exclude certain servers or datastores from being reported on or filtered out? I assume this may have to be on a per-plugin basis, but would be nice to have a master "ignore" list and then maybe granular ignore lists for each plugin.  We have hundreds of data stores and a few of them are dedicated to a single VM.  These are constantly showing up on the reports as running out of space, etc.  

Ideas?

**Comment by paulobartos** [comment]
Hi,

I have the necessity to exclude one Datacenter (test one) from my report,
so I changed the following lines:

On Globalvariables.ps1

...
#added

#Exclusion for Datacenters
$DC_exclusion = "BC-ToIP"


On 00 Connection Plugin for vCenter.ps1

...
# replaced the following lines
Write-CustomOut "Collecting Datacenters"
$Datacenters = Get-Datacenter | where  { $DC_Exclusion -notcontains
$_.name} | Sort Name

Write-CustomOut $pLang.collectCluster
$Clusters = Get-Cluster -Location $Datacenters  | Sort Name

Write-CustomOut $pLang.collectDCluster
$clusviews = Get-View -ViewType ClusterComputeResource | where  {
($clusters | select -expand name) -contains $_.name }

Write-CustomOut $pLang.collectHost
$VMH = Get-VMHost -Location $Clusters | Sort Name

Write-CustomOut $pLang.collectDHost
$HostsViews = Get-View -ViewType hostsystem | where  { ($VMH | select
-expand name) -contains $_.name }

Write-CustomOut $pLang.collectDatastore
$Datastores = Get-Datastore | where { $DC_Exclusion -notcontains
$_.Datacenter.Name } | Sort Name

Write-CustomOut $pLang.collectDDatastore
$storageviews = Get-View -ViewType Datastore | where  { ($Datastores |
select -expand name) -contains $_.name }

Write-CustomOut $pLang.collectVM
$VM = Get-VM -Location $Clusters | Sort Name

Write-CustomOut $pLang.collectDVM
$FullVM = Get-View -ViewType VirtualMachine | where  { ($VM | select
-expand name) -contains $_.name }| Where {-not $_.Config.Template}

Hope it helps you.

Paulo


2015-01-16 13:25 GMT-02:00 bkingx <notifications@github.com>:

**Comment by Sneddo** [comment]
at the moment adding where clauses to the connection plugin as @paulobartos mentioned is the only real solution.

Issue #169 is already open to implement global filters, so will close this off.
