### ISSUE TITLE
Plug-in Customizations

### ISSUE THREAD

**Issue by MasterChiefJon** [alanrenouf/vCheck-vSphere#322]
I make custom tweaks to a majority of the vCheck plug-ins (modified comments, adjusted VM exceptions, actual code changes, etc.).  Then when a new version/patch comes out, I have to go through each plug-in and re-enter my tweaks.  I don't have any good ideas on how to keep track of every file that I've changed, and what I need to modify after each new version comes out.

Does anyone out there have any ideas?

**Comment by Sneddo** [comment]
vCheckUtils.ps1 contains a function called Export-vCheckSettings, which exports your settings to CSV.

You can then run Import-vCheckSettings to update afterwards. 

This may break, but at the moment the best we can do. The settings handling is something that needs to be fixed at some point...

**Comment by MasterChiefJon** [comment]
Exporting the settings section of the plug-ins does solve part of my issue, but I tried to run that function (after dot-sourcing the script), and it is erroring out.  The error is shown below the break.
####################################
New-Object : Cannot find type [â?TypeName PSObject â?Prop]: make sure the assembly containing this type is loaded.
At C:\Users\AdcockJ\Documents\Scripts\PowerCLI\vCheck-6.22\vCheckUtils.ps1:366 char:22
+             $currentsetting = New-Object â?"TypeName PSObject â?"Prop $settings
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

**Comment by MasterChiefJon** [comment]
Exporting the settings section of the plug-ins would help with part of my issue.  But when I tried running the export function (after dot-sourcing the vCheckUtils script) it generated an error.  That error is shown below the break.
######################################
You cannot call a method on a null-valued expression.
At C:\Users\AdcockJ\Documents\Scripts\PowerCLI\vCheck-6.22\vCheckUtils.ps1:365 char:4
+             $settings.var = $CurSet.Trim()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by MasterChiefJon** [comment]
Sneddo, as I mentioned, I have made some custom modifications to the plug-ins.  In a few cases, those modifications were to allow me to exclude certain VMs by name.  When I added the variable to the settings section of the plug-in, the Export-vCheckSettings doesn't like it if you don't have a line explaining what the variable does.  For example, I needed to do this:

# Don't report on VMs with Names that match...
$VMsDoNotInclude="^MLB-"

...not this:

$VMsDoNotInclude="^MLB-"


So when I ran the export settings function, it expected to find a variable line AND an explanation line.  I didn't have both.  I do now.  Also, in the GlobalVariables.ps1 file, I had an extra line break in the settings section.  That also cause an error.

I hope this level of detail helps the other vCheck users out there.

**Comment by Sneddo** [comment]
Yep, that makes sense. Not the most robust system for handling setting...
