### ISSUE TITLE
76 VM Network State Broken?

### ISSUE THREAD

**Issue by MasterChiefJon** [alanrenouf/vCheck-vSphere#323]
Looking at the code in this plug-in, it appears that the conditions on lines 9 & 10 could never be met.  Therefore you would NEVER get any output from the plug-in.  

Specifically, line 9 (foreach ($myCard in...) would return each NIC that is NOT connected.
Then, line 10 does an IF statement for the resulting (not connected) NIC that says if the card IS connected then gather the details.
So the IF statement on line 10 can never be true!  

I tested this by REM'ing out the IF line and the curly brace that closes that IF statement (line 17) and ran it.  That returned the list of disconnected NICs as expected.  
With the IF statement still in the plug-in, it doesn't return anything.

**Comment by Sneddo** [comment]
Yeah, good catch. The second condition should be checking for StartConnected rather than Connected property. Will fix now :)
