### ISSUE TITLE
Backup Monitoring

### ISSUE THREAD

**Issue by Ti360** [alanrenouf/vCheck-vSphere#324]
Hello Alan, 
I recently discovered your vcheck script and that help me resolving lot of unknown issue, i really like it.Thank you!  We are using veeam as a backup solution and it is possible to set a specific attribute when a job is successful. 
Is there a way to list all vm with this specific attribute ? if it older than 2 days so i can have it in my daily report ?

Our attibute name was set to BackupStatus and here is the Data leave by veeam; 
Veeam Backup: Job name: [ProdServers] Time [1/12/2015 6:37:20 AM], Backup host [BackupServer], Backup file [[This server] BACKUPSERVER:\Dedup\backup\PROD Servers\PROD Servers2015-01-12T040039.vib]

**Comment by Sneddo** [comment]
This is simple enough for you to implement.

[Plugin Structure](https://github.com/alanrenouf/vCheck-vSphere/wiki/Plugin-structure)
[Get-Annotation PowerCLI reference](http://pubs.vmware.com/vsphere-60/topic/com.vmware.powercli.cmdletref.doc/Get-Annotation.html)

From there is it just a matter of a regex match and some simple date handling.
Regex: `Veeam Backup: Job name: \[(.*)\] Time \[(.*)\], Backup host \[(.*)\], Backup file \[(.*)\]`
$Matches[1] should be the job name, $Matches[2] the time, $Matches[3] the backup server, $matches[4] the backup file.

From there, just do something like `(Get-Date).AddDays(-2) -gt (Get-Date $Matches[2])`

My suggestion is to get the logic working first, and then put it into a plugin.

**Comment by Sneddo** [comment]
No reply in over three weeks- closing off this issue.
