### ISSUE TITLE
PluginsEnabled Count?

### ISSUE THREAD

**Issue by MasterChiefJon** [alanrenouf/vCheck-vSphere#328]
In the plugin "119 Report on Plugins.ps1", the header uses the variable ($PluginsEnabled).Count) and for me, that count always returns 1 plugin enabled (when I actually have several dozen plugins enabled).  Where is the variable $PluginsEnabled defined?

**Comment by Sneddo** [comment]
I don't see that variable in use...
https://github.com/alanrenouf/vCheck-vSphere/blob/master/Plugins/80%20Finish/119%20Report%20on%20Plugins.ps1

**Comment by MasterChiefJon** [comment]
I must have copied that from an older version.  Closing this issue.
