### ISSUE TITLE
Can you run vcheck on a host instead of vcenter?

### ISSUE THREAD

**Issue by ddd2015** [alanrenouf/vCheck-vSphere#330]
I saw the prereqs say:
vCenter 2.5 or later version

I am new to ESXi, we only have one ESXi host and I have a Windows 7 VM setup that I run vsphere client to access the host.

Can the vcheck script run against a single host in an environment that does not use vcenter?
If it can, can you suggest which plugins to use when only a single host is being used?

Thanks

**Comment by Sneddo** [comment]
hmmmm...it probably won't work without modification to the connection plugin as it uses objects that aren't available on a single host. Interesting question though!

**Comment by ddd2015** [comment]
Thanks sneddo. ..
Hopefully someone will chime in with more info...
If connection plug in modifications are needed, hopefully someone can let me know a little more about the needed mods.

I didn't previously mention that our version of esxi is version 5.5 update 2.

Thanks

**Comment by monahancj** [comment]
As Sneddo pointed out a lot would fail, like anything to do with
clusters, but it should run.  Just change the vcenter variable to the esxi
hostname.  As for which plugins, exlude anything that would need more than
one host to exist (like a cluster).  Easiest way is to run the vCheck and
see what breaks.

  I'll have to test that one tomorrow.

**Comment by ddd2015** [comment]
Thanks monahancj!
I would really appreciate to hear your feedback after you test. I hope to start testing too later today, just trying to get as much info up front before I start.

Thanks

**Comment by monahancj** [comment]
It ran as expected against a single host.  Lots of plugins failed as
expected, but I still got a report emailed with everything that did work.

  I suggest running it with the plugins you want and then remove all the
plugins that fail.

-Chris

**Comment by ddd2015** [comment]
Thanks monahancj for your follow up. I plan to begin working on this in a few hours , I will follow back up with my results.
Thank you very much for your feedback.

Thanks

**Comment by ddd2015** [comment]
monahancj, you mention running it with the plugins you want and then remove all the plugins that fail.
First time user question...
How do you select which plugins you want?
And, how do you remove the plugins that fail?
Do you modify the script? If so, can you tell me which one and how to remark out?
Or, do you rename or move the plugin folder or plugin file so it cant be found?

Thanks

**Comment by monahancj** [comment]
Easy way is to use the Select-Plugins.ps1 utility.  It's in root of the
vCheck directory.  All it does is rename deselected plugins from "name.ps1"
to "name.ps1.disabled".  When vCheck runs it skips any of the disabled
plugins.

**Comment by ddd2015** [comment]
monahancj, I made some progress... I did get vcheck to run through from start to finish!
Questions...
Sneddo mentioned "it probably won't work without modification to the connection plugin as it uses objects that aren't available on a single host"
And you commented "Just change the vcenter variable to the esxi hostname"
Can anyone further elaborate on what mods may be needed on the connection plugin?
And monahancj, can you let me know where to find the vcenter variable?
When I first ran vcheck the first question was to enter an IP to run vcheck against.
The only thing I did was entered our ESXi host IP at that prompt.
Should I have changed any other vcenter variables?

Next question, are there any error logs?
If so, where are they located?

When I first ran vcheck I saw alot of errors pass by on the screen...
On my first run I chose all default answers on the initial config screen thats run on first run, and I did not disable any plugins yet...
I would like to review any logs to help me disable "non applicable" plugins when running vcheck on a single host (no vcenter).

Lastly, I didnt get an email report, so reviewing error logs may help me resolve my email issue.

Lastly, thank you all very much for all help provided.

Thanks

**Comment by Sneddo** [comment]
OK, so if you entered your host IP on the setup it will already be in the GlobalVariables.ps1 file.

In terms of changes to the connection plugin, there only seems to be one line that will generate an error:
$alarmMgr = get-view $ServiceInstance.Content.alarmManager

The rest should at worst evaluate to $null. Now, some plugins may not like that, but that's something you'll just have to try and see what breaks.

You can pretty much wipe out everything in the Cluster and vCenter folders straight away. I guess VSAN, sDRS, dvSwitches, SRM plugins should be able to be disabled as well.

**Comment by ddd2015** [comment]
Sorry for the delay in returning to this work..
I do now have vcheck running on my single host (no using vcenter)
I am now reviewing failures and I see alot of:
"The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

We are using a self signed cert...
I researched and a post (not here at github) about a possible fix of adding the below line...
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}

Does anyone know if this could resolve my above "connection closed" issue?
If it can work, to enable it to be a global fix for all ps1 scripts (plugins), where would this line be added?

Thanks

**Comment by ddd2015** [comment]
I did more troubleshooting and learned...
If I run the plugin by itself via the Job switch it works fine?
But running normally I get the "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

Here is a little more info...
- I see many plugins failing with the "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel." error.
- I decided to just work with the first failing plugin, which is Plugins\50 Network\24 vSwitch with less than x Ports Free.ps1
- As I said, running vcheck normally I  get the above error everytime?
I am running 75 plugins, I have not removed all non working plugins yet...
- I created a jobtest.xml file and included the below plugins only...
<plugin>\00 Initialize\00 Connection Plugin for vCenter.ps1</plugin>
<plugin>\00 Initialize\01 General Information.ps1</plugin>
<plugin>\50 Network\24 vSwitch with less than x Ports Free.ps1</plugin>
<plugin>\80 Finish\999 VeryLastPlugin Used to Disconnect.ps1</plugin>

And, it works?
Here are my logs...
Broken log:
[17:03:02] ..start calculating Checking Standard vSwitch Ports Free by Alan Renouf v1.1 [31 of 75]
Get-VirtualSwitch : 2/21/2015 5:03:02 PM    Get-VirtualSwitch        The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Working log:
[18:07:19] ..start calculating Checking Standard vSwitch Ports Free by Alan Renouf v1.1 [3 of 4]
[18:07:19] ..finished calculating Checking Standard vSwitch Ports Free by Alan Renouf v1.1 [3 of 4]

Can anyone offer a solution?

I checked the vcheck.ps1 file and see I have version:
$vCheckVersion = "6.23-alpha-1"

Thanks

**Comment by Sneddo** [comment]
*sigh* this bug is really frustrating. As you can see it is quite inconsistent. Though the job switch working is interesting. My current thought is that it is memory related, and that Powershell is doing something to the vCenter objects to close a connection. Downside of the way we currently do data collection.

Might need to go through and actually clean up variables when we are done with them...starting with some of the larger ones. And abstracting the data collection as well, but that's a bigger task!

**Comment by ddd2015** [comment]
I am very willing to troubleshoot / beta test in hopes to get a faster resolution to this problem. I guess I can try splitting my 75 plug in into two separate jobs next and see if that helps. 
Thanks for your quick reply.

**Comment by ddd2015** [comment]
Hi guys, sorry for the delay in following back up...
I finally got vcheck to cleanly run on our ESXi host (we are not in a vcenter environment)
It took some testing and some code help from the vmware commnunities, but last night I cleanly ran 75 plugins (in groups a 3 batches of plugins)!

To help others in non vcenter environments who want to run vcheck, I have documented my steps...
But first, one important note...
In an ESXi host environment there is no "Alarm" functionality, this is only present in VCenter. Sadly, this ESXi host drawback does impact probably the most important feature of VCheck, alarm alerting!

But, even with this major alarm drawback, VCheck still provides alot of valuable info!

Here are my docs...
1. In powerCLI, CD to your vcheck folder, issue a ".\select-plugins.ps1" , a plugins window opens, uncheck the below plugins.
18 Cluster Slot Sizes.ps1
38 Cluster Configuration Issues.ps1
41 vCenter Services.ps1
42 Windows vCenter Error Event Logs.ps1
43 Windows vCenter Warning Event Logs.ps1
47 vCenter Session Age.ps1
55 Clusters with DRS Disabled.ps1
70 Cluster Node Version.ps1
80 DvPG with less than x Ports Free.ps1
104 Clusters with no Host Profile.ps1
108 SRM RPO Violations.ps1
115 Datastore Clusters with sDRS Disabled.ps1
116 sDRS VM Behavior not Default.ps1
990 VSAN Capacity Report.ps1
991 VSAN Configuration Maximum Disk Group Per Host Report.ps1
992 VSAN Configuration Maximum Magnetic Disks Per Disk Group Report.ps1
993 VSAN Configuration Maximum Total Magnetic Disks In All Disk Groups Per Host Report.ps1
994 VSAN Configuration Maximum Component Per Host Report.ps1
995 VSAN Configuration Maximum Hosts Per Cluster Report.ps1
996 VSAN Configuration Maximum VMs Per Host Report.ps1
997 VSAN Configuration Maximum VMs Per Cluster Report.ps1

2.  Disable all plugins in the below folders (add ".disabled" to the end of the plugin name)
10 vCenter
20 Cluster

3. Remark out AlarmMgr in 00 Connection Plugin for Vcenter.ps1
- Edit -  00 Connection Plugin for Vcenter.ps1
- Remark out the below two lines by placing a # sign in front...
126 - Write-CustomOut $pLang.collectAlarm
127 - $alarmMgr = get-view $ServiceInstance.Content.alarmManager

4. Disable the below plugins (add ".disabled" to the end of the plugin name)
30 Host - 36 Host Alarms.ps1
30 Host - 105 Host Profile Compliance.ps1

5. Plugin 60 VM - 09 Created or cloned VMs.ps1 failed with error:
get-view - view with ID Eventmanager-Eventmanager was not found on this server.

The problem was...
In VCenter...
$evtmgr - get-view eventmanager

The above equivalent in ESXI host is...
$si = get-view serviceinstance
$evtmgr = get-view $si.content.eventmanager

To add the above ESXi host adjustment...
- Edit -  00 Connection Plugin for Vcenter.ps1
Line 204 - $eventMgr = Get-View EventManager
Add a # sign in front to remark out that line
Place your cursor at the end of Line 204 and hit Enter twice to create two new blank lines.
Paste in the below lines... (note I added ddd to $si to create a unique name)
205 - $si_ddd=Get-View ServiceInstance
206 - $eventMgr = Get-View $si_ddd.Content.EventManager

6. Plugin 60 VM - 14 VMs restarted due to Guest OS Error.ps1 failed as well.
This plugin uses "QueryEvents", which only works in VCenter.
I posted a "QueryEvents" alternative for ESXi question in the vmware communities and LucD responded with "History Collector" code that worked perfectly.
The original plugin only check for "VMs restarted due to Guest OS Error".
I asked LucD to add poweron & poweroff time stamp events so that I could see all VM reboots.
There is one important note about ESXi host Events, they purge quickly, meaning that they are only available for a day or two. The History Collector "queries" the ESXi host Events, which are only a day or two of events at most. 

I will post LucD code in a new comment box...

**Comment by ddd2015** [comment]
LucD code...
- I made a backup of original Plugin 60 VM - 14 VMs restarted due to Guest OS Error.ps1
- Then, edit 14 VMs restarted due to Guest OS Error.ps1 and delete all code.
- Paste in the below...

# VCheck Plugin - Plugins - 60 VM - 14 VMs restarted due to Guest OS Error.ps1 - Modified for ESXI Host Environment
# Start of Settings 
# End of Settings

# Info & reason for mods...
# The original script plugin was wrote for a VCenter environment.
# When attempting to run original script in a ESXi Host Environment quickly learned why script did not work...
# The reason was its use of "QueryEvents", which is not available on ESXi Hosts!
# Through good fortune I found LucD in the vmware communities, who...
# A. provided an alternative solution to using "QueryEvents", the "History Collector".
# B. wrote the below "History Collector" code.

# The original code was wrote for "HA VM reset day(s) number due to Guest OS error"
# I asked to also add VmPoweredOffEvent & VmPoweredOnEvent

# Below is mod code for ESXi Host Environment...

$eventnumber = 1000
$serviceInstance = get-view ServiceInstance 
# ddd $serviceInstance = get-view ServiceInstance -Server $global:DefaultVIServer
$eventMgr = Get-View $serviceInstance.Content.EventManager

$efilter = New-Object VMware.Vim.EventFilterSpec
$efilter.time = New-Object VMware.Vim.EventFilterSpecByTime
$efilter.time.beginTime = (Get-Date).Adddays(-7)
$efilter.time.endtime = Get-Date
$efilter.EventTypeId = 'VmPoweredOffEvent','VmPoweredOnEvent','com.vmware.vc.ha.VmRestartedByHAEvent'

$events = @()

$ecollectionImpl = Get-View ($eventMgr.CreateCollectorForEvents($efilter))
$ecollectionImpl.RewindCollector()

$ecollection = $ecollectionImpl.ReadNextEvents($eventnumber)

while($ecollection -ne $null){
   $ecollection.Count
   $histcoll +=  $ecollection.Count
   $events += $ecollection
   $ecollection = $ecollectionImpl.ReadNextEvents($eventnumber)
}

$ecollectionImpl.DestroyCollector()

$filtertext = {$_.FullFormattedMessage -match "powered off" -Or $_.FullFormattedMessage -match "powered on" -Or $_.FullFormattedMessage -match "reset due to a guest OS error"}

$events | ? $filtertext |select CreatedTime,FullFormattedMessage |sort CreatedTime -Descending

$Title = "VMs restarted due to Guest OS Error and/or Power State of VMs"
$Header = "HA: VM restarted due to Guest OS Error and/or Power State of VMs (Number is HistoryCollector hits: $histcoll)"
$Comments = "The following VMs have been restarted by HA and/or show Power State of VMs"
$Display = "Table"
$Author = "LucD"
$PluginVersion = 1.1
$PluginCategory = "vSphere"

- Save and exit...

**Comment by ddd2015** [comment]
And lastly...
When I ran Vcheck with just a ".\vcheck.ps1" which runs all plugins, I had many of the below errors:
"The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

The temp workaround was to run vcheck with the "-job" switch and break all plugins into 3 groups.
Running...
.\vcheck.ps1 -job .\job1.xml
.\vcheck.ps1 -job .\job2.xml
.\vcheck.ps1 -job .\job3.xml

Worked perfectly!

**Comment by Sneddo** [comment]
Nice, I'll try to compile this info into a wiki entry when I have a chance.

FYI- if you indent text by 4 spaces or more it will show as a code block (I updated your post to demonstrate)

**Comment by ddd2015** [comment]
Hi guys, one last follow up...
Where I last left off I was able to cleaning run vcheck on our ESXi host in the powerCLI window!
Lets call that Part 1...
Part 2 was getting vcheck to run under a Windows 7 Scheduled task...
Which, should have been a simple thing, but I encounter many "issues" in the process and wanted to follow back up and pass on what I encountered and how I addresses those "issues".
If anything, hopefully it will help others new to running vcheck on a ESXi host by saving them a lot of research time...
I will do several small posts to help keep things clean...

**Comment by ddd2015** [comment]
First, remember that these notes are meant for someone new to vcheck & powerCLI...
Here goes...
I previously mentioned that I was able to cleanly run vcheck on our ESXi host.
The way I confirmed this was..., in the powerCLI screen I entered...
PowerCLI >Start-Transcript -path c:\util\vlog.txt -append
PowerCLI > .\vCheck.ps1 -job .\job1.xml
PowerCLI >Stop-Transcript

Doing the above logs all vcheck output to the vlog.txt file...
Then, I renamed vlog.txt to vlog.csv, and opened it in Excel 2002.
When Excel open the CSV file, I was prompted with CSV prompts, I choose Delimited - Next, I unchecked all Delimiters - Next, Finish.
This allowed Excel to display the log file in a line by line view.
I could quickly & easily verify no errors.

Also note, you must create the ".job1.xml" file in the vcheck root folder. This file contains only the plugins that you want to run.

Here is a copy of my job1.xml...
<vCheck> 
<globalVariables>GlobalVariables.ps1</globalVariables> 
<plugins path="plugins-vSphere"> 

<plugin>\00 Initialize\00 Connection Plugin for vCenter.ps1</plugin>
<plugin>\00 Initialize\01 General Information.ps1</plugin>
    
<plugin>\30 Host\07 Hosts Overcommit State.ps1</plugin>
<plugin>\30 Host\08 Hosts Dead LUN Path.ps1</plugin>
<plugin>\30 Host\16 Host Swapfile datastores.ps1</plugin>
<plugin>\30 Host\20 ESXi with Technical Support mode enabled.ps1</plugin>
<plugin>\30 Host\21 ESXi hosts which do not have Lockdown mode enabled.ps1</plugin>
<plugin>\30 Host\31 NTP Name and Service.ps1</plugin>
<plugin>\30 Host\35 Host Configuration Issues.ps1</plugin>
<plugin>\30 Host\44 VMKernel Warnings.ps1</plugin>
<plugin>\30 Host\46 Missing ESX patches.ps1</plugin>
<plugin>\30 Host\51 Syslog Name.ps1</plugin>
<plugin>\30 Host\53 Hardware status warnings-errors.ps1</plugin>
<plugin>\30 Host\57 Hosts with reboot required.ps1</plugin>
<plugin>\30 Host\67 Host OS Pivot Table.ps1</plugin>
<plugin>\30 Host\68 Disk Max Total Latency.ps1</plugin>
<plugin>\30 Host\74 Host - Network Redundancy lost.ps1</plugin>
<plugin>\30 Host\75 Hosts with Different Hostnames.ps1</plugin>
<plugin>\30 Host\77 Lost Access to Volume.ps1</plugin>
<plugin>\30 Host\81 LUN Paths Check.ps1</plugin>
<plugin>\30 Host\83 Hosts not Connected or Alarms Disabled.ps1</plugin>
<plugin>\30 Host\101 ESXi Inode Usage.ps1</plugin>
<plugin>\30 Host\105 Host Profile Compliance.ps1</plugin>
<plugin>\30 Host\110 Host Certificate Expiration Check.ps1</plugin>

<plugin>\80 Finish\119 Report on Plugins.ps1</plugin>
<plugin>\80 Finish\999 VeryLastPlugin Used to Disconnect.ps1</plugin>

</plugins> 
</vCheck>

And..., a copy of my job2.xml
<vCheck> 
<globalVariables>GlobalVariables.ps1</globalVariables> 
<plugins path="plugins-vSphere"> 

<plugin>\00 Initialize\00 Connection Plugin for vCenter.ps1</plugin>
<plugin>\00 Initialize\01 General Information.ps1</plugin>
    
<plugin>\40 Datastore\03 Datastore Information.ps1</plugin>
<plugin>\40 Datastore\34 Number of VMs per Datastore.ps1</plugin>
<plugin>\40 Datastore\39 Datastore OverAllocation.ps1</plugin>
<plugin>\40 Datastore\59 Datastores with Storage IO Control Disabled.ps1</plugin>
<plugin>\40 Datastore\69 Datastores in Maintenance mode.ps1</plugin>
<plugin>\50 Network\24 vSwitch with less than x Ports Free.ps1</plugin>
<plugin>\50 Network\98 vSwitch Security.ps1</plugin>
<plugin>\60 VM\02 Snapshot Information.ps1</plugin>
<plugin>\60 VM\04 Map disk region event.ps1</plugin>
<plugin>\60 VM\09 Created or cloned VMs.ps1</plugin>
<plugin>\60 VM\10 Removed VMs.ps1</plugin>
<plugin>\60 VM\11 VMs with over CPU Count.ps1</plugin>
<plugin>\60 VM\12 VMs Swapping or Ballooning.ps1</plugin>
<plugin>\60 VM\13 Invalid or inaccessible VMs.ps1</plugin>
<plugin>\60 VM\14 VMs restarted due to Guest OS Error_dasmod.ps1</plugin>
<plugin>\60 VM\19 Guests with less than X MB free.ps1</plugin>
<plugin>\60 VM\22 Checking VM Hardware Version.ps1</plugin>
<plugin>\60 VM\25 VMs in inconsistent folders.ps1</plugin>
<plugin>\60 VM\26 No VM Tools.ps1</plugin>
<plugin>\60 VM\27 VM Tools Issues.ps1</plugin>
<plugin>\60 VM\28 CD-ROMs Connected.ps1</plugin>
<plugin>\60 VM\29 Floppy Drive Connected.ps1</plugin>
<plugin>\70 Misc\750 DAS Added get vms lastpoweron info.ps1</plugin>

<plugin>\80 Finish\119 Report on Plugins.ps1</plugin>
<plugin>\80 Finish\999 VeryLastPlugin Used to Disconnect.ps1</plugin>

</plugins> 
</vCheck>

And..., a copy of my job3.xml
<vCheck> 
<globalVariables>GlobalVariables.ps1</globalVariables> 
<plugins path="plugins-vSphere"> 

<plugin>\00 Initialize\00 Connection Plugin for vCenter.ps1</plugin>
<plugin>\00 Initialize\01 General Information.ps1</plugin>
    
<plugin>\60 VM\30 Single Storage VMs.ps1</plugin>
<plugin>\60 VM\32 VM CPU Percent RDY.ps1</plugin>
<plugin>\60 VM\33 VM CPU Usage.ps1</plugin>
<plugin>\60 VM\37 VM Alarms.ps1</plugin>
<plugin>\60 VM\40 VCB Garbage.ps1</plugin>
<plugin>\60 VM\45 VMs needing snapshot consolidation.ps1</plugin>
<plugin>\60 VM\48 Find VM Disk Format.ps1</plugin>
<plugin>\60 VM\50 VMs with CPU or Memory Limits Configured.ps1</plugin>
<plugin>\60 VM\54 Virtual Machines with incorrect OS Configuration.ps1</plugin>
<plugin>\60 VM\58 Virtual machines with less hard disks than partitions.ps1</plugin>
<plugin>\60 VM\60 Powered Off VMs.ps1</plugin>
<plugin>\60 VM\61 Guest OS Pivot table.ps1</plugin>
<plugin>\60 VM\62 Unwanted Virtual Hardware.ps1</plugin>
<plugin>\60 VM\64 Snapshots Oversize.ps1</plugin>
<plugin>\60 VM\66 Misnamed VM.ps1</plugin>
<plugin>\60 VM\76 VM Network State.ps1</plugin>
<plugin>\60 VM\78 Reset VMs.ps1</plugin>
<plugin>\60 VM\79 Find VMs in Uncontrolled Snapshot Mode.ps1</plugin>
<plugin>\60 VM\85 Snapshot Activity.ps1</plugin>
<plugin>\60 VM\100 VMs with CPU or Memory Reservations.ps1</plugin>
<plugin>\60 VM\102 VM Logging.ps1</plugin>
<plugin>\60 VM\106 Find Phantom Snapshots.ps1</plugin>
<plugin>\60 VM\107 Quantity of Snapshots.ps1</plugin>
<plugin>\60 VM\114 VM Tools Not Up to Date.ps1</plugin>
<plugin>\60 VM\620 CBT Status.ps1</plugin>

<plugin>\80 Finish\119 Report on Plugins.ps1</plugin>
<plugin>\80 Finish\999 VeryLastPlugin Used to Disconnect.ps1</plugin>

</plugins> 
</vCheck>

Ok, now that you can cleanly run the above 3 jobs on the powerCLI console, lets move on...

**Comment by ddd2015** [comment]
Ok, my next problem was I could not get vcheck to store my user creds...
Everytime I ran vcheck I had to enter creds...
Maybe a ESXI host thing?
Maybe a different user account thing?
I am running powerCLI on a Windows 7 VM as UserA, and running vcheck against of ESXI host as UserB, maybe that was my issue?

With the above issue in mind, and thinking about our environment (wanting a simple "batch file" sitting on the desktop)...
I decide my best option to "automate" vcheck was:
- Batch file that calls
- my "wrapper" ps1 file, that calls
- vcheck ps1

Doing the above allowed me to:
- keep the vcheck ps1 file in its original state (no changes made to vcheck)
- Any needed adjustments could be implemented in my wrapper ps1 file
- give me a simple BAT file to launch vcheck

Ok, with the above in mind, I first addressed the password issue.
My solution was to create a credfile.xml file to store the creds, and call the credfile.
To do this...
Launch powerCLI and paste in the below
New-VICredentialStoreItem -host YourHostIP -user UserName -password Password -file C:\util\credfile.xml

Adjust your YourHostIP, UserName, Password, and where & name you want for your credfile file.
Now you can use the credfile to auto login to your ESXi host...
Keep the credfile handy, I show you how to use it next...

**Comment by ddd2015** [comment]
Ok, next up is launching vcheck from a Batch file...
I am big on log files, I like to log everything and name the log file with a date & time stamp.
I found that if I do a ">> ToLogFile.txt" in my batch file when I call the ps1 script everything in my wrapper ps1 and vcheck ps1 was logged!
Also, I needed to pass batch file variables into the ps1 scripts...
I am sure there are cleaner ways to do this, but what I have works perfectly...

Ok, first note...
The batch file and wrapper ps1 file must be in the root of the vcheck folder.
I created vcheckdas.bat file in the root of the vcheck folder and pasted in the below...

     rem pause

@echo off
CLS

set logtime=%time: =0%
rem above 0% makes 1 appear as 01
set timestampdas=%date:~-4,4%%date:~-10,2%%date:~-7,2%_%logtime:~-11,2%h%logtime:~-8,2%m%logtime:~-5,2%s
set logdas=c:\util\logs\%timestampdas%_zvcheckdaslog.txt

echo Start: %date% %time% > %logdas%
echo. >> %logdas%

C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe -PSConsoleFile "C:\Program Files (x86)\VMware\Infrastructure\vSphere PowerCLI\vim.psc1" -file "C:\util\vCheck-vSphere-master\zvcheckdas.ps1" >>  %logdas%


@echo on

rem pause

echo. >> %logdas%
echo Finish: %date% %time% >>  %logdas%

Ok, that is it for the batch file...

**Comment by ddd2015** [comment]
Next up is the wrapper ps1 file...
In the root of the vcheck folder I created a file named zvcheckdas.ps1
I found several advantages of using this wrapper ps1...
- I can call 3 vcheck runs
- I can add log notes to note the progress of the script
- I added "error" checking...
Being that I am dumping everything to a log file, at the end I can search that log file for "FullyQualifiedErrorId", which informs me when a plugin fails. I noticed that whenever a plugin fails there is always reference to FullyQualifiedErrorId.
So after my 3 vcheck job runs, I then run a check on the log file for FullyQualifiedErrorId
- I have also added email so that I get an additional email with the subject line Pass or Fail and my batch file log attached.
I hit two snags...
1. You cant email a logfile thats in use, so I had to make a copy of the log file and attach the copied file.
2. When calling a second ps1 file from a starting ps1 file, I found that the second ps1 "does not know where its at"...
To get around this I used $ScriptPath

Other than that, the file has more log file info than code, but it does create a detailed log file!
And lastly...
Remember the credfile...
You will need to adjust the below location & name of the credfile for your environment...

$creds = Get-VICredentialStoreItem -file “C:\util\credfile.xml”

In the below code...

Ok, here is the wrapper ps1 file code...

     write-output "" | out-default
     write-output "Starting zvcheckdas.ps1 script now..." | out-default
     write-output "" | out-default

     write-output "Starting vcheck.ps1 with job1.xml script now..." | out-default
     write-output "" | out-default

     $creds = Get-VICredentialStoreItem -file “C:\util\credfile.xml”
     Connect-viserver -Server $creds.Host -User $creds.User -Password $creds.Password 

     $ScriptPath = Split-Path $MyInvocation.MyCommand.Path
     ."$ScriptPath\vcheck.ps1" -job .\job1.xml –OutputPath c:\util\logs\vcheckreports\job1

     write-output "" | out-default
     write-output "Pausing 10 seconds..." |out-default
     get-date -format "MMM-dd-yyyy hh:mm:ss" |out-default
     Start-Sleep -s 10
     get-date -format "MMM-dd-yyyy hh:mm:ss" |out-default

     write-output "" | out-default
     write-output "Ending vcheck.ps1 with job1.xml script now..." | out-default
     write-output "" | out-default

     write-output "Starting vcheck.ps1 with job2.xml script now..." | out-default
     write-output "" | out-default

     $creds = Get-VICredentialStoreItem -file “C:\util\credfile.xml”
     Connect-viserver -Server $creds.Host -User $creds.User -Password $creds.Password 

     $ScriptPath = Split-Path $MyInvocation.MyCommand.Path
     ."$ScriptPath\vcheck.ps1" -job .\job2.xml –OutputPath c:\util\logs\vcheckreports\job2

     write-output "" | out-default
     write-output "Pausing 10 seconds..." |out-default
     get-date -format "MMM-dd-yyyy hh:mm:ss" |out-default
     Start-Sleep -s 10
     get-date -format "MMM-dd-yyyy hh:mm:ss" |out-default

     write-output "" | out-default
     write-output "Ending vcheck.ps1 with job2.xml script now..." | out-default
     write-output "" | out-default

     write-output "Starting vcheck.ps1 with job3.xml script now..." | out-default
     write-output "" | out-default

     $creds = Get-VICredentialStoreItem -file “C:\util\credfile.xml”
     Connect-viserver -Server $creds.Host -User $creds.User -Password $creds.Password 

     $ScriptPath = Split-Path $MyInvocation.MyCommand.Path
     ."$ScriptPath\vcheck.ps1" -job .\job3.xml –OutputPath c:\util\logs\vcheckreports\job3

     write-output "" | out-default
     write-output "Ending vcheck.ps1 with job3.xml script now..." | out-default
     write-output "" | out-default

     write-output "Starting Log Review for Errors and Emailing results..." | out-default
     write-output "" | out-default
     get-date -format "MMM-dd-yyyy hh:mm:ss" |out-default
     write-output "" | out-default

     # needed to pass batch file logdas variable into this Powershell script...
     $timestampdas = $env:timestampdas
     write-output "timestampdas is: $timestampdas" |out-default
     write-output "" | out-default

     $logdas = $env:logdas
     write-output "Log file name is: $logdas" |out-default
     write-output "" | out-default

     $logdasemail = "c:\util\logs\" + $timestampdas + "_zvcheckdaslogemail.txt"
     write-output "logdasemail is: $logdasemail" |out-default
     write-output "" | out-default

     write-output "Now checking $logdas for pattern FullyQualifiedErrorId and storing results in srchresults variable..." | out-default  

     # -quiet is needed to just return true or false !
     $srchresults = Get-Content $logdas | Select-String  -pattern "FullyQualifiedErrorId" -quiet

     if ($srchresults -eq "True") {
	     write-output "" | out-default
	     write-output "srchresults variable is eq to True, ERRORS Found, the srchresults variable is $srchresults" |out-default
	     }
     else {
	     write-output "" | out-default
	     write-output "srchresults variable is eq to False, NO Errors Found, the srchresults variable is $srchresults" |out-default
	     }

     # Read-Host "Press Enter Key to continue . . ." | Out-Null

     write-output "" | out-default
     write-output "Ending Log Review for Errors and Emailing results..." | out-default
     write-output "" | out-default

     write-output "Ending zvcheckdas.ps1 script now and returning to Batch File..." | out-default
     write-output "" | out-default
     get-date -format "MMM-dd-yyyy hh:mm:ss" |out-default
     write-output "" | out-default
     ###
     copy-item $logdas $logdasemail

     write-output "" | out-default
     write-output "Pausing 10 seconds for file copy..." |out-default
     get-date -format "MMM-dd-yyyy hh:mm:ss" |out-default
     Start-Sleep -s 10
     get-date -format "MMM-dd-yyyy hh:mm:ss" |out-default
     write-output "" | out-default

     if ($srchresults -eq "True") {
	     Send-MailMessage -From "YourFromAddress" -To "YourToAddress"-Subject "VCheck Plugins Scripts FAILED, FAIL" -Body "Message sent via Powershell!" -Attachments "$logdasemail" -smtpServer YourEmailServerIP
	     }
     else {
	     Send-MailMessage -From "YourFromAddress" -To "YourToAddress"-Subject "VCheck Plugins Scripts Successful, PASS" -Body "Message sent via Powershell!" -Attachments "$logdasemail" -smtpServer YourEmailServerIP
	     }
     ###

Ok, thats it for the wrapper ps1 file....

**Comment by ddd2015** [comment]
Ok, with the above, you can launch a batch file and have it run 3 check jobs and get a 4th email with plugin pass/fail info and your log file...

Lastly, to schedule the batch file...
Here is what worked for me using Windows 7...
My Windows 7 user account (UserA) is an admin on that box.
Being that I successfully ran the batch file as UserA, that is the user that will run the scheduled task.
Launch Task Scheduler - create task
- Name it
- The UserA account was list by default, I left it as is.
I selected run whether user is logged in or not
The "Do not store password" box is unchecked.
(do not check that box, if you do it does not work, I tried)
Thats all I set on the General tab
Triggers tab - set your time to run.
Actions tab:
A. browse to the BAT file (in the root of vcheck folder)
B. Add arguments box - empty
C. Start In box - must put in the "path" to your vcheck ps1 file
Ex: c:\util\vcheck\
(Step C is required, without it it does not work, I tried)
Conditions tab - I left at default
Settings tab:
I made one change:
I set stop task if runs longer than 1 hour.
Thats it, click OK and enter your UserA password.

As a test...
I logged out as UserA and left Windows 7 sitting at a login prompt.
Five minutes later my batch file kicked off, ran vcheck, and I got 4 emails (3 vcheck jobs and 1 log email)

It all seems simple now, but it took alot of research...
Hopefully, going forward, this will save someone some time...

Thats all for now...

**Comment by vScripter** [comment]
This appears to be solved. Cleaning up open issues and marking as closed. Please re-open, if you continue to encounter issues. Thanks!
