### ISSUE TITLE
vCenter Session Age MinvCenterSessionAge Variable

### ISSUE THREAD

**Issue by MasterChiefJon** [alanrenouf/vCheck-vSphere#332]
I would like to be able to define a MinvCenterSessionAge variable, and have that define the minimum number of idle minutes that a session must have to be included in the report.  Defining variable is easy enough, but finding a way to do the comparison in the Where clause is beating me.
Can you help modify the Where clause in the script to include where:
IdleMinutes -ge $MinvCenterSessionAge

**Comment by Sneddo** [comment]
So you essentially want to filter out sessions that aren't idle for x number of hours, right?

You can basically do a similar comparison, you just need to Get-Date and AddHours with a negative value. I'll hopefully have a bit of time next week to look at this unless someone else does :) Few other fixes needed in that plugin

**Comment by MasterChiefJon** [comment]
As written, the plugin shows every session that was initiated greater than 48 hours ago.  Well some of those sessions are active, and the IdleMinutes is 0 or 1 minutes.  So what I'm looking for is this: if the LoginTime is more than 48 hours ago and IdleMinutes is greater than or equal to 10 minutes, then display the session.  If the IdleMinutes is less than 10 minutes, then don't include it.

Having said that, the problem that I'm running into is that the IdleMinutes value is created AFTER the Where clause, and when I move it before the Where clause I keep blowing up the plug-in.

**Comment by monahancj** [comment]
I noticed that logic problem today too.  If I have it right (and I think
I'm restating what Jon said), every session created longer than the 48
hours or whatever you set it to ( we do 4 hours) is listed, and THEN idle
minutes is calculated.  So for me it's showing sessions that have been idle
for 7 minutes.

  If I can tomorrow (15 hours to my start of day) I want to rewrite the
plugin to calculate just the idle minutes and return sessions longer than
"x" minutes instead of hours.  I'll reread Jon's request too and try to
work it in.

-Chris

**Comment by MasterChiefJon** [comment]
I got it working.  In short, I added an additional Where clause after the select statement.  How would you like for me to post the resulting script (directly into this thread)?

**Comment by monahancj** [comment]
I thought I was on to something, but I think I ran into a timezone issue.  The vCenter session info has some last active times a few hours into the future.  Will have to pick it up Monday  :-/

$SessionManager.SessionList | select username,fullname,ipaddress,logintime,lastactivetime,@{n="DaysIdle";e={if (([int]($_.LastActiveTime - (get-date)).TotalDays * -1) -gt 0) {[int]($_.LastActiveTime - (get-date)).TotalDays * -1}
}},@{n="HoursIdle";e={[int]($_.LastActiveTime - (get-date)).TotalHours * -1}},@{n='a';e={($_.LastActiveTime - (get-date)).TotalHours}} | ft -a

UserName      FullName      IpAddress    LoginTime             LastActiveTime        DaysIdle HoursIdle                  a
--------      --------      ---------    ---------             --------------        -------- ---------                  -
xx\yyyyy      yyyyyy yyyy   10.5.3.66    2/19/2015 9:59:21 AM  2/19/2015 9:59:21 AM         1        30  -30.4865465848889
xxx\yyyyyyyyy               10.5.42.10   2/20/2015 2:09:03 PM  2/20/2015 8:03:21 PM                  -4   3.58025090191667
xxx\yyyyyyyyy yyyyy yyyyyyy 10.6.237.63  2/20/2015 8:48:36 PM  2/20/2015 8:48:36 PM                  -4   4.33433157961111
xxx\yyyyyyyyy yyyyy yyyyyyy 10.6.237.63  2/20/2015 2:52:53 PM  2/20/2015 2:52:53 PM                   2  -1.59430845863889
xxx\yyyyyyy   yyyy yyyyy    10.6.237.76  2/20/2015 5:01:12 PM  2/20/2015 7:45:21 PM                  -3   3.28021145422222
xxx\yyyyyyy   yyyy yyyyyy   10.4.168.41  2/20/2015 7:17:58 PM  2/20/2015 7:18:15 PM                  -3   2.82853490080556
xxx\yyyyyyy   yyyy yyyyyy   10.5.42.3    2/18/2015 2:30:15 PM  2/20/2015 7:55:32 PM                  -3   3.45002898305556
xxx\yyyyyyyyy yyy yyyyyyyy  10.4.161.234 2/19/2015 5:54:56 PM  2/20/2015 8:49:19 PM                  -4   4.34645667211111
xxx\yyyyyyyyy yyy yyyyyyyy  10.4.161.234 2/20/2015 2:53:18 PM  2/20/2015 3:18:32 PM                   1  -1.16663375986111
xxx\yyyyyy                  10.6.237.54  2/20/2015 1:40:12 PM  2/20/2015 1:40:12 PM                   3  -2.80570126213889
xxx\yyyyyyyyy               10.4.14.24   2/14/2015 11:08:57 PM 2/14/2015 11:08:57 PM        6       137  -137.326440741361
xxx\yyyyyyyyy               10.4.14.24   2/6/2015 9:36:23 AM   2/20/2015 3:47:24 PM                   1 -0.685576772277778
xxx\yyyyyyyyy               10.4.14.24   2/14/2015 11:08:56 PM 2/14/2015 11:08:56 PM        6       137   -137.32680800175
xxx\yyyyyyyyy               10.4.14.24   2/14/2015 11:08:57 PM 2/14/2015 11:08:57 PM        6       137  -137.326564089444
xxx\yyyyyyyyy               10.4.14.24   2/6/2015 9:29:21 AM   2/20/2015 8:50:37 PM                  -4   4.36795409333333
xxx\yyyyyyyyy               10.4.14.24   2/14/2015 11:08:56 PM 2/14/2015 11:08:56 PM        6       137  -137.326687436861
xxx\yyyyyyy                 10.4.42.102  2/20/2015 8:42:42 PM  2/20/2015 8:52:00 PM                  -4   4.39113502047222
xxx\yyyyyyy                 10.4.42.102  2/20/2015 8:52:04 PM  2/20/2015 8:52:04 PM                  -4   4.39203455394444

**Comment by Sneddo** [comment]
@MasterChiefJon you can either do a pull request, or just post it here :)

**Comment by MasterChiefJon** [comment]
OK, here you go...

# Start of Settings
# Enter maximum vCenter session length in hours
$MaxvCenterSessionAge = 48
# Enter minimum vCenter session length in minutes (IdleMinutes)
$MinvCenterSessionAge = 10
# Do not report on usernames that are defined here (regex)
$vCenterSessionsDoNotInclude = "DOMAIN\\user1|DOMAIN\\user2"
# End of Settings

# Changelog
## 1.0 : Initial Release
## 1.1 : Modified the plug-in to not report active sessions, only report sessions that have been inactive for more than $MinvCenterSessionAge minutes

# Retrieve vCenter sessions and report any sessions that exceed the maximum session age AND have been idle longer than the specified minutes.
if ($VIConnection.IsConnected) {
	$Result = @(
		$ServiceInstance = Get-View ServiceInstance
		$SessionManager = Get-View $ServiceInstance.Content.SessionManager
		$SessionManager.SessionList | `
			Where {$_.LoginTime -lt (Get-Date).AddHours(-$MaxvCenterSessionAge) -AND `
			$_.UserName -notmatch $vCenterSessionsDoNotInclude} | `
			select LoginTime, UserName, FullName, @{N="IdleMinutes";e={([Math]::Round(((Get-Date)-($_.lastActiveTime).ToLocalTime()).TotalMinutes))}} | ` 
			Where {$_.IdleMinutes -ge $MinvCenterSessionAge}
			)
	$Return = $Result | Sort LoginTime
	$Return
}
else {
	Write-Error $pLang.connError
}

$Title = "vCenter Sessions Age"
$Header = "vCenter Sessions Age Report"
$Comments = "The following vCenter sessions have been open longer than the maximum session age ($MaxvCenterSessionAge Hour(s)), plus the session has been inactive (idle) longer than the minimum session age ($MinvCenterSessionAge minute(s))."
$Display = "Table"
$Author = "Rudolf Kleijwegt"
$PluginVersion = 1.0
$PluginCategory = "vSphere"

**Comment by Sneddo** [comment]
OK, I've added this and cleaned up some of the redundant code at the same time. Can you guys test and let me know if there are any issues?

**Comment by MasterChiefJon** [comment]
That worked for me.  Thank you.
