### ISSUE TITLE
Should these upgrade scripts be added to vCheckUtils.ps1 or in there own file?

### ISSUE THREAD

**Issue by monahancj** [alanrenouf/vCheck-vSphere#334]
https://gist.github.com/monahancj/7fbca58bc80443dffd38

I think it could go either way.  I wondering what others think before I submit them.

Thanks,
-Chris

**Comment by Sneddo** [comment]
Neat, I reckon we add them to vCheckUtils :)

And if I ever have time, into the config GUI...

**Comment by monahancj** [comment]
Patch submitted.

**Comment by Sneddo** [comment]
Pull request #339 merged
