### ISSUE TITLE
vCD Audit vApp Firewall Rules

### ISSUE THREAD

**Issue by jefflevy** [alanrenouf/vCheck-vSphere#337]
I am having issues with this particular script.  I am running the latest VMware PowerCLI, vSphere 5.5 U2, and vCD 5.5.2.  If I have the connection, global, and this script in the plugins folder, it will run but the output does not contain any data for the firewall rules.

**Comment by Sneddo** [comment]
Might be better tracked through appropriate repository. Although development is not really active on these projects...
https://github.com/alanrenouf/vCheck-vCD
https://github.com/alanrenouf/vCheck-vCDAudit
