### ISSUE TITLE
vCheck.ps1 'Get-ReportHTML'

### ISSUE THREAD

**Issue by JeremyRider** [alanrenouf/vCheck-vSphere#341]
Greetings,

I am receiving the following exception when attempting to run vCheck 6.22.  Are there any other files or settings I need to support the 'Get-ReportHTML' command?  

Thanks!

The term 'Get-ReportHTML' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At C:\scripts\vcheck_6.22\vCheck.ps1:718 char:27
+ $MyReport = Get-ReportHTML <<<<
    + CategoryInfo          : ObjectNotFound: (Get-ReportHTML:String) [], Comm
   andNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Sneddo** [comment]
Hi,

You just need to update your style- this was changed in one of the latest releases to move towards separating the markup and the code.

**Comment by JeremyRider** [comment]
Thank you Sneddo.  I knew it had to be something simple that I was overlooking since no one else had posted about it. :+1:
