### ISSUE TITLE
Capacity Planning Addition

### ISSUE THREAD

**Issue by delucad1** [alanrenouf/vCheck-vSphere#342]
Hi All,

Was wondering if it is possible to add an additional column in the capacity planning script to show the corresponding datacenter name in which the cluster belongs to?  I didn't see an object reference under ClusterComputeResource for it but I may be missing something.

Thanks in advance!

**Comment by Sneddo** [comment]
Had a quick look at this.

$Clusters[*].ParentFolder.Parent.Name contains the Datacenter name, will just need to match up the view and the cluster object, instead of running a Get-Datacenter call. About to head home, so will submit a pull request for this tomorrow.

**Comment by vScripter** [comment]
We should be able to get it by doing something like: (adding some additional code for context)
```
foreach ($cluv in ($clusviews | Sort Name)) {
    
    $datacenterName = (Get-VIObjectByView -MoRef $cluv.Parent).Parent.Name
```

**Comment by Sneddo** [comment]
Cool, wasn't aware of that cmdlet :) I've been trying to avoid and Get- cmdlets in plugins where possible, but that is certainly an option. I realised there is a bit of extra work in this plugin as well- Issue #234, and a general cleanup of the code.

**Comment by vScripter** [comment]
I agree, 100%, on trying to avoid native (and redundant) cmdlet calls, unless necessary. In my experience, on a single scoped vCenter/environment, the `Get-VIObjectByVjew` cmdlet doesn't add significant processing cost, and has proven to be a pretty decent 'shortcut'.

**Comment by delucad1** [comment]
Thanks guys - I took a look at the commit and it works exactly how I was hoping.  One note, the cmdlet Get-VIObjectByView should actually be Get-VIObjectByVIView

Thanks again!

**Comment by Sneddo** [comment]
Yeah, you're right. Must not have committed that change after testing. I'll update now.
