### ISSUE TITLE
Collecting Detailed Datastore Objects - You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by haripetrov** [alanrenouf/vCheck-vSphere#343]
During the execution of "00 Connection Plugin for vCenter.ps1" I received this error:
```
Collecting Detailed Datastore Objects
You cannot call a method on a null-valued expression.
At C:\Scripts\vCheck\Plugins\00 Initialize\00 Connection Plugin for vCenter.ps1:136 char:70
+ $VIVersion = ((Get-View ServiceInstance).Content.About.Version).Chars <<<< (0)
    + CategoryInfo          : InvalidOperation: (Chars:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by Sneddo** [comment]
What version of vCheck, PowerCLI, and vCenter are you running?

**Comment by haripetrov** [comment]
I am sorry. I forgot about these details:
vCheck: the latest 6.23-alpha-2
vCenter: 5.1.0 (947673)
PowerCLI: 5.1 Release 1

I will check on another vCenter servers with different version.

**Comment by haripetrov** [comment]
There is no problem with the following configuration:
vCheck: the latest 6.23-alpha-2
vCenter: 5.5 Update 2
PowerCLI: 5.8 Release 1

The same situation with:
vCheck: the latest 6.23-alpha-2
vCenter: 5.1 Update 2
PowerCLI: 5.1 Release 1

Probably this is some special case in which this error occurs in this particular configuration of versions.
