### ISSUE TITLE
Configuration advice for multiple vcenter servers with -job parameter

### ISSUE THREAD

**Issue by rppalmer** [alanrenouf/vCheck-vSphere#350]
I set up vCheck for our environment with two vCenter servers to kick the tires (awesome by the way!).  So after getting it set up the team decided we wanted to split the reports up into things we want to see daily vs weekly vs monthly.  I read through the documentation and figured out how to configure the XML file with the -job parameter.  I set an XML file up for each server (daily/weekly/monthly) ... basically each file has increasingly more scripts that it runs meaning that daily = A, weekly = A+B, and monthly has A+B+C (where A,B,C represent the scripts that are allowed to run in each XML file - basically the monthly includes everything that we want to see each month in addition to the weekly and daily stuff).

Now that I had that down, I needed to figure out how to have the XML file call the global variables file ...this part was easy, each XML file was set to call the respective server's globalvariable file.  So at this point there are 8 files.

Selection-ServerA-Daily.xml
Selection-ServerA-Weekly.xml
Selection-ServerA-Monthly.xml
GlobalVariables-ServerA.ps1

Selection-ServerB-Daily.xml
Selection-ServerB-Weekly.xml
Selection-ServerB-Monthly.xml
GlobalVariables-ServerB.ps1

The last thing I attempted to do was configure the subject line based on which report was being run and I am having some trouble with this.  I can't figure out a way to have GlobalVariables know if the XML file being used is for daily weekly or monthly so I can have the subject line reflect appropriately, I could just create multiple global variables files but I want to keep this as simple as possible and I am hoping someone has already solved this problem before I go that route. So what am I missing?

I am also open to suggestions on the entire implementation if someone sees any glaring/dumb mistakes. Thanks!

**Comment by Sneddo** [comment]
Really, there isn't a great solution for this situation. 

If you keep to the Selection-Server-Frequency.xml format you could modify your GlobalVariables to parse the job parameter and set server and subject based on that. 

e.g. 

    if ($job -match "Selection-(.*)-(.*)\.xml") {
       $Server = $Matches[1]
       $EmailSubject = "$Server vCheck Report - $($Matches[2])"
    }
    else {
       # Failed to Parse job parameter
       Write-Error "Failed to Parse job parameter"
       quit
    }
    
**This does mean you will have to do any reconfiguration manually, the setup wizard will not like this**

As a longer term goal, pushing setting overrides into the job file might be an idea...which is something I've been considering to simplify updates as well.
