### ISSUE TITLE
vCenter Permissions and roles getting an error - pl help

### ISSUE THREAD

**Issue by akarthikeyan16** [alanrenouf/vCheck-vSphere#351]
+ ... eport = @()    $authMgr = Get-View AuthorizationManager    $roleHash = @{}    $a ...
+                    ~~~~~~~~
Unexpected token '$authMgr' in expression or statement.
At C:\Karthik\vCenter permission and roles\PRtestAlan.ps1:1 char:948
+ ... rmissions()    foreach($perm in $perms){      $ret = New-Object PSObject      $e ...
+                    ~~~~~~~
Unexpected token 'foreach' in expression or statement.
At C:\Karthik\vCenter permission and roles\PRtestAlan.ps1:1 char:1694
+ ... nt($nodeName)  $node.AppendChild($tmp)}function Set-XmlAttribute{  param($node,  ...
+                    ~~~~~
Unexpected token '$node' in expression or statement.
At C:\Karthik\vCenter permission and roles\PRtestAlan.ps1:1 char:1901
+ ... Inventory =  1 "<Inventory><Roles/><Permissions/></Inventory>"# Roles$XMLRoles = ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token '"<Inventory><Roles/><Permissions/></Inventory>"' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by Sneddo** [comment]
This isn't a vCheck script name, what are you trying to run? It also looks like you have some issue with your line endings or character encoding looking at those errors...

**Comment by Sneddo** [comment]
No response in almost 4 weeks - closing off issue.
