### ISSUE TITLE
vCheck for Multiple vCenter and Non-Outlook Environment

### ISSUE THREAD

**Issue by kandadeepak** [alanrenouf/vCheck-vSphere#354]
Hi,
I would like to run vCheck for multiple vCenter and i don't use the outlook in my environment.Do i have any solution for this?

I really appreciate the work.

**Comment by Sneddo** [comment]
At the moment, running vCheck against multiple vCenters is not a supported solution- see Issue #204 for a bit more info.

As for Outlook, vCheck just sends a HTML formatted message, so any capable email client (and an SMTP server to send email via) is all that is required.
