### ISSUE TITLE
vCheck not working

### ISSUE THREAD

**Issue by pretty25** [alanrenouf/vCheck-vSphere#363]
Hi I have got vCheck 6.15 running for couple of months, all of a suddent it stopped working and keeps running for more than 2 days, where as earlier it used to finish with in 4 hours. having said that the same script runs and sends an email if runs manually.

Could you please check with this and let me know where do i check to run this again or troubleshoot.
task scheduler last run result code 0x0 which means it ran successfully

**Comment by pretty25** [comment]
can any one please respond on this

**Comment by Sneddo** [comment]
I assume you are running it as a different user to your logged in user? Can you run the script manually as the scheduled task user?

Without seeing any error messages there isn't really much we can do to help.

Incidently, there have been a number of releases since 6.15. Perhaps this is a good time to update :)

**Comment by pretty25** [comment]
as the old 6.15 isn't running anyways, i have downloaded vCheck 6.23 and running it manually before it could check it, it ran for couple of times and scheduling the same doesn't work. I was retrying vCheck again and it stops at 94 of 108 plugins and it stopped responding without proceeding further. how to move further without actually cancelling the running script.

I ran the PowerCLI as an administrator and running the vCheck.ps1 -config didn't ask me to enter credentials and i will be scheduling this as a different user. Please let me know if you need more info with any screenshots if screenshots, how do i upload them here.

I also got another vCheck 6.15 running successfully when ran it manually only, but doesn't run it as a scheduled task. when i look at the display all running tasks in task scheduler and history notes of these scheduled tasks, i get to see that its still running for more than 20 hours and for sometimes, i get to see as task stopped due to time out reached and the task gets terminated.
thx in advance

**Comment by Sneddo** [comment]
> how to move further without actually cancelling the running script.
You can't really. Which plugin is it getting to?

> lease let me know if you need more info with any screenshots if screenshots, how do i upload them here.
See the notes below the comment box.

If you "run as" Powershell as the user you are running the task as, what does it do?

**Comment by pretty25** [comment]
I logged in as the user which is scheduled to run this vCheck task and opening Powershell works fine. 
is it something, that we need to run this vCheck script -config with the user scheduled to run this task as logged in user and run the task with the same user.
in vCheck 6.23, when do i get to see prompting for enterting vCenter credentials, if entered once with running this vCheck -config as one user, does it need to enter again if run as different user.

can you please list the steps for me to get this run as scheduled task: i looked at different articles, it looks simple but never got this working as a scheduled task, but the same script when run manually works absolutely perfect.

thx

**Comment by pretty25** [comment]
i tried again with the user logged in as set to run the scheduled and did ran the vCheck.ps1- config with the same user, then set the scheduled task to run, it keeps on running for more than 2 hours, where as the same vCheck script ran in less than 2 hours. Not sure where its going wrong and i am really tired of this, could someone please help me on getting this worked.

**Comment by Sneddo** [comment]
> I logged in as the user which is scheduled to run this vCheck task and opening Powershell works fine. 

So vCheck runs fine as the scheduled task user? Then there is some issue with the way you have created your task. It's pretty simlple, just create a task as follows (this is a copy and paste from my tasks, so adjust paths as required)
Program/script: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Arguments: -Command "& 'C:\Scripts\Powershell\vCheck\vcheck.ps1' 
Start in: C:\Scripts\Powershell\vCheck

> when do i get to see prompting for entering vCenter credentials

Is vCheck prompting for credentials to connect to vCenter? In which case, you need to look at your SSO config and permissions of the user you are running vCheck as. Or is this after it connects and is running the vCenter plugins?

We really need more information to help you out- please post some screenshots so that we can see exactly what is happening.

**Comment by pretty25** [comment]
HI i really appreciate your response on this,
I am trying to run 2 scripts on the same 1 is 6.15 and other 6.23 latest one, where as earlier both  are 6.15 and used to run fine until it broke recently. i am just wondering why running 2 scripts 6.15 & 6.23 are overlapping each other, on one of the tests, i get to see the report has got the results from both the vCenter severs. its kind of broken and nothing seems to work again.
To get more clarity on this, i will start this from a scratch.
running vCheck 6.15 - i will login as scheduled task user and run this vCheck 6.15 - config and schedule this script with the same user.
running vCheck 6.23 - i will login as scheduled task user and run this vCheck 6.23 - config and schedule this script with the same user. using the above commands in creating a task. 
Please check with this and let me know is this approach correct.

I will let you know more on this shortly and with possible screenshots as well.

**Comment by pretty25** [comment]
Hi, i am running both the scripts as fresh start, while running vCheck6.23.ps1 -config, i started getting errors for most of the plugins as shown below except few scripts which went through ok.
![image](https://cloud.githubusercontent.com/assets/11729130/7308721/bb3753a8-ea0e-11e4-88d6-31e97ad12188.png)

fyi: when i downloaded the vCheck6.23 version of scripts, it was all ok and looking at the report, i decided to remove the scripts from the respective folders which i don't want them to run and thought i could save time by skipping/deleting them. trying this way, its giving all the errors as showing in screenshot, please let me know how do i proceed with this.

![image](https://cloud.githubusercontent.com/assets/11729130/7308793/5a36dd16-ea0f-11e4-891c-62d2b2b47115.png)

i am running the script as i am writing this and getting the credentials prompt here which i am entering now as the scheduled task user set to run this task. it prompted 3 times and entered 3 times and later on it went further this.

![image](https://cloud.githubusercontent.com/assets/11729130/7308846/e1552686-ea0f-11e4-941e-261c7d8f98e0.png)

also, i was wondering why is it going through series of scripts even though i deleted most of the scripts from the plugins folder. Please check with this and let me know ways to get this script working for me as a scheduled script.

thx in advance

**Comment by Sneddo** [comment]
> i am just wondering why running 2 scripts 6.15 & 6.23 are overlapping each other, on one of the t ests, i get to see the report has got the results from both the vCenter severs. 

You would get this if you either have an existing connection to both vCenters before running vCheck, or if the disconnect plugin does not run.

> i started getting errors for most of the plugins as shown below except few scripts which went through ok.

Looks like you do not have write/modify access to the plugin files.

> i am running the script as i am writing this and getting the credentials prompt here which i am entering now as the scheduled task user set to run this task. it prompted 3 times and entered 3 times and later on it went further this.

This is a little strange if the other vCenter service/event plugins are working as it should use the same credential file. Worth noting however, that the credential file will only work for the user that created it, due to the fact that it uses secure strings to save the password. 

> also, i was wondering why is it going through series of scripts even though i deleted most of the scripts from the plugins folder. 

Did you delete them after you started running vCheck? Because it only evaluates the list at the start of execution.

**Comment by pretty25** [comment]
i got the mix report yesterday from both the vCenters and thought of running it again as a fresh start. no there were no existing connections, i will double check while running it next time.

the user which i am running this vCheck script is local administrator on the sever where this script is running and is also vmware administrator, having all the privileges why is it failing and prompting for credentials 3 times, don't understand.

i deleted the plugins before i started running the script.
the script is still running as of now and will update you shortly.

many thx for your quick response on this.

**Comment by pretty25** [comment]
this is how it keeps running for hours when its running as scheduled task and i am guessing its waiting for these prompts or errors mentioned above.
![image](https://cloud.githubusercontent.com/assets/11729130/7309326/2a572078-ea15-11e4-8fc5-85f955d4fb3e.png)

also, i am running this vCheck.ps1 -config as a test entering only my email id to send the reports to, assuming this all works ok and later on, if i edit the global variables.ps1 file and enter distribution list email id, will it work and start sending the report to the distribution list email id or not ?

or else, do i need to run this again specifying this DL email id in global variables.ps1 file ?

thx

**Comment by pretty25** [comment]
Here is the screenshots of both the versions 6.15 & 6.23 scripts running stuck at this point for so long and still hanging.....
![image](https://cloud.githubusercontent.com/assets/11729130/7309410/02a4dcc2-ea16-11e4-9b20-aa89bf213dd1.png)
it stopped at this script for more than 40 minutes and still running at the same plugin on both the version of scripts, is this normal ?

**Comment by Sneddo** [comment]
> this is how it keeps running for hours when its running as scheduled task and i am guessing its waiting for these prompts or errors mentioned above.

Yep, I think that is exactly what is happening.

Just to check: you're not running with the -config switch on the scheduled task, right?

> if i edit the global variables.ps1 file and enter distribution list email id, will it work and start sending the report to the distribution list email id or not ?

Yeah, this will save you a lot of time, instead of running though all settings.

> it stopped at this script for more than 40 minutes and still running at the same plugin on both the version of scripts, is this normal ? 

Depends on a lot of factors- size of environment, utilization of vCenter and client, etc. Without looking at the plugin code, anything dealing with VMDKs can be pretty slow, especially if you have a lot of datastores and/or VMs. Reset VMs could potentially be slow if it you have a lot of events to go through. And of course, if you click into the Powershell window you can also pause the execution of the script- if the cursor is blinking it should be trying to do something at least :)

For the moment, it may be worth running with less plugins whilst you get things working- once the script is actually sending information you should be able to add extra plugins without any impact.

**Comment by pretty25** [comment]
Hi Sneddo,
i am getting the passwords for these 3 scripts:
41 vCenter Services
42 Windows vCenter Error Event Logs
43 Windows vCenter Warning Event Logs
and i am entering the username and password everytime it prompts, but it doesn't cache them and keeps on prompting and this is the reason its taking long and keep on waiting at this.
but earlier, it used to work fine and now its not working for these scripts, having said that working earlier, it doesn't prompt for credentials but doesn't showup these 3 scripts info in the vCheck report.

![image](https://cloud.githubusercontent.com/assets/11729130/7337938/5ef7c326-ec33-11e4-9aba-0c5ed38c0521.png)

my question is, when it doesn't show up in the report about these 3 scripts, whats the point of running these scripts and i am thinking of disabling these scripts. why it didn't prompt for credentials earlier and why is it prompting now.

**Comment by Sneddo** [comment]
Given that you were having "Access Denied" errors, my guess would be the credentials file was not updated for the account that is scheduling the script...

So yeah, either disable them, or perhaps modify the script to either use a different file, or add the credentials to the plugins themselves.

**Comment by pretty25** [comment]
Hi Sneddo,
thanks for your help on this so far, i got this script working successfully but a few bits about vCheck report emailing is not working.
Here's the scenario, i got this vCheck 6.15 worked successfully and emailed the report to the specified email ids in global variables.ps1 file but at the same time mentioning the same email ids in lateest vCheck 6.23  global variables.ps1 isn't sending to 2 of the 3 email ids specified, where as the report is working and getting emailed to only the 3rd email id which is my personal email id. Please check below as in vCheck 6.23 its considering the 1st 2 email ids with the incorrect format of email ids and that's the reason its not sending the report to these 2 email ids, where as the same email ids were used and were sent these reports using the old vCheck report.
emailed report not sent to the specified email ids:
![image](https://cloud.githubusercontent.com/assets/11729130/7382501/845b572e-ee07-11e4-8ba4-6f52c17daf8f.png)

emailed report to the specified email ids:
![image](https://cloud.githubusercontent.com/assets/11729130/7382503/89444e08-ee07-11e4-95d9-f0df24551e84.png)

Please check with this and advise where is it getting wrong.

thx

**Comment by Sneddo** [comment]
How are you specifying the to addresses- I suspect with the changes with email handling that they will need to be semicolon separated, not comma separated now...

**Comment by pretty25** [comment]
i tried like this "1@test.com, 2@test.com, 3@test.com" and it looks like it worked for me, where as i was specifying  "1@test.com", "2@test.com", "3@test.com" and was not working with the vCheck 6.23 verison. I will check with your suggestions as well and will update you once done.

even after running the vCheck.ps1 -config and entering the credentials once and running just vCheck.ps1 from next time, if its still asking for credentials, how do we go about fixing it, so as it should remember it in credentials.xml file and shouldn't be prompting for it.

**Comment by pretty25** [comment]
looks like its only working like this "1@test.com, 2@test.com, 3@test.com" , i just tried the way you suggested and it didn't email me reports.
can you suggest on remembering the credentials instead of prompting for it even though its specified already using vCheck.ps1 -config

**Comment by Sneddo** [comment]
OK, lets see if it is storing the credentials correctly...

Open up Powershell and switch to the vCheck directory and run this:
      $LoadedCredentials = Import-Clixml Windowscreds.xml
      $creds = New-Object System.Management.Automation.PsCredential($LoadedCredentials.Username,($LoadedCredentials.Password | ConvertTo-SecureString))
      Write-Host ("Username: {0}     Password: {1}" -f $creds.Username, $creds.GetNetworkCredential().Password)

**Comment by Sneddo** [comment]
Any update on this? Will leave this open for another week before closing it off we don't hear anything.

**Comment by pretty25** [comment]
Oh, sorry, its been sorted and has been working absolutely fine. thanks very much for your help on this and yes you can close this.
just one more thing regarding the same, just yesterday night, vCheck 6.23 is taking longer than usual where as in past it normally finishes with in 7 hours and is still running, so is there anyway to check where is it stuck and why is it taking this longer.

**Comment by Sneddo** [comment]
At the moment, not really. I'd like to extend the output function to support logging to a file at some point.

**Comment by captainaa4** [comment]
Hi Sneddo
I want to re-open this thread because I am facing same kind of issue. I am using vCheck ver 6.23 and I have created 10 Schedule tasks for my 10 vCenters. Out of 10 only 6 tasks are working fine and I am getting report on mail but 4 Tasks are not stopping and keeps running for 2 days.
Also when I try to run the task manually also it did not stop but when I run the script manually and it works for all of the vCenters.
All tasks are configured for below configuration.

**Program/script**: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
**Arguments**: -file vcheck.ps1 -OutputPath C:\scripts\vCheck_Scripts\Report
**Start in**: C:\scripts\vCheck_Scripts\
