### ISSUE TITLE
SMTP send failing

### ISSUE THREAD

**Issue by SUBnet192** [alanrenouf/vCheck-vSphere#366]
I had an issue with SMTP send in vCheck, ended up having to change the $smtpClient.UseDefaultCredentials = $true; to $false for it to work in our environment, kept getting 5.7.1 error message. Would be nice if that was an configurable option (-config). :)

**Comment by Sneddo** [comment]
Yep, we have Issue #144 to track enhancements to the SMTP config. Due the the limitations of the settings handling I've been holding off on it for now, once that is sorted out we can proceed with it.

I'll close this one off, no point having two open issues for effectively the same request :)
