### ISSUE TITLE
Errors and Blank HTML on Manual Run

### ISSUE THREAD

**Issue by cajunitalian** [alanrenouf/vCheck-vSphere#367]
Getting some interesting situations.
Ran it manually and quite a few different errors show up:

![screenshot 17](https://cloud.githubusercontent.com/assets/1809840/7231600/d69e890c-e73b-11e4-8a59-97acd9327c00.jpg)
![screenshot 15](https://cloud.githubusercontent.com/assets/1809840/7231601/d6a08f22-e73b-11e4-8630-d24e71bedad4.jpg)
![screenshot 16](https://cloud.githubusercontent.com/assets/1809840/7231599/d69c4a5c-e73b-11e4-99db-caa0ae35b2ac.jpg)

Also, after it's done running it pops the HTML like normal but it's just blank.  Also of note - no email gets sent to me.

**Comment by Sneddo** [comment]
OK, what version of Powershell, PowerCLI and vCheck are you running?

Second one: What do you get when you run `$host.PrivateData.WarningForegroundColor` in your console? 

The third one may be related to PowerCLI 6.0, I certainly get the same error since updating.

**Comment by Sneddo** [comment]
Bump. If there is no reply to this in another week, I'll close this off.

**Comment by Sneddo** [comment]
Closing this off as there has been no response. Please log a new issue if you are still having trouble.
