### ISSUE TITLE
122 NonPersistent Disks Exclude VMs

### ISSUE THREAD

**Issue by MasterChiefJon** [alanrenouf/vCheck-vSphere#368]
I wanted the ability to exclude (by name) a bunch of desktop VMs from this report.  So I edited the foreach line as follows:

    $Result = @(ForEach($vm in $FullVM | Where {$_.Name -notmatch $NPExcludeVM}){

I added the variable $NPExcludeVM in the settings section as follows:

    # Exclude all desktop virtual machines
    $NPExcludeVM = "^DV-|^MLB-"

 and modified the $Comments variable to say "The following server VMs have disks....

I'm submitting this change for inclusion into the plug-in.

**Comment by Sneddo** [comment]
> I'm submitting this change for inclusion into the plug-in.

Sounds good, submit the pull request and I'll merge it :) Always good to have more options!

**Comment by MasterChiefJon** [comment]
Sneddo, I submitted a pull request (my first).  I had a steep learning curve.  Any feedback you may have would be appreciated.

**Comment by Sneddo** [comment]
That's great, thanks :)
