### ISSUE TITLE
Creation of 'dev' branch (to support a more efficient git flow model)

### ISSUE THREAD

**Issue by vScripter** [alanrenouf/vCheck-vSphere#371]
Requesting the creation of a 'dev' branch to support a more formal git flow model for contributions (name can be whatever; just something that clearly translates to 'dev'). Pull Requests would be made to the dev branch, instead of the master branch, which would reserve the master branch for 'gold' builds and allow for collaboration to occur outside of the production code stream. While the necessity may not exist, today, this model would also support further breaking out the 'plugins' into their own 'feature' branches, off of the dev branch, and merging feature branch changes back into the dev code stream, all without affecting production. 

(A much better, more detailed description can be found at http://nvie.com/posts/a-successful-git-branching-model/)

![Git Flow Model](https://camo.githubusercontent.com/9bde6fb64a9542a572e0e2017cbb58d9d2c440ac/687474703a2f2f6e7669652e636f6d2f696d672f6769742d6d6f64656c4032782e706e67)

**Comment by Sneddo** [comment]
Always happy to see suggestions on how we can use Github more efficiently- not something I've personally had much experience with :)

I've just created a 'dev' branch.

**Comment by monahancj** [comment]
I hope Kevin can fix what we break.  :)

**Comment by Sneddo** [comment]
You call them mistakes, I call them undocumented features :P

**Comment by vScripter** [comment]
Features are just bugs with a suit and tie on, aren't they? ;)

Glad to finally have the time to start contributing. I certainly don't consider myself a git/GitHub pro, but I've been using it, almost daily, for the past 2 years (give or take). I've been looking for a good project to really start digging my heels into and this one has been on my list for quite some time.

Somewhat unrelated to this issue request, but has there been any consideration about getting a [Gitter chat]( https://gitter.im) going for the repo? It 100% free and serves as a good place for relevant conversation about code changes, questions, etc. (for example, I have some general questions that might generate good conversation, which would probably be a good candidate for gitter, as opposed to a pull request or opening an issue (don't really like junking up those workflows) ). Anywho, take a look and see what you think; great, free, tool with a nice compliment of native apps, as well. 

Thanks again!

**Comment by Sneddo** [comment]
Hey, that's really neat! Certainly something we could use IMO. Will set it up now :)

Glad to have some fresh blood, I have been lacking time to really do anything meaningful and what I have had time for is just helping out with issues as they are raised, hoping we can actually see some progress now!

**Comment by vScripter** [comment]
Yea, I hear that; looking forward to kicking the tires.
