### ISSUE TITLE
Issue after disconnecting from vCenter

### ISSUE THREAD

**Issue by matthewlroth** [alanrenouf/vCheck-vSphere#384]
PowerCLI Version
VMware vSphere PowerCLI 5.5 Release 1 build 1295336
vCheck v6.23-alpha-3
vCenter 5.5

I get no issues with any of the scripts. When it completes it errors out and does not send the report. it is copied to to temp correctly. any help would be appreciated
![capture](https://cloud.githubusercontent.com/assets/7388060/7574677/0b6994ac-f7fd-11e4-8a01-fd72b1f9ab8b.PNG)

**Comment by Sneddo** [comment]
Were there any errors running any of the plugins?

It looks like one of the plugins returned a non-null result from running, but wasn't an object that could be converted to HTML either.

Might need to add some more verbose and/or debug logging to help with some of these issues...

**Comment by matthewlroth** [comment]
There are no other errors during the run. how do you run debug logging. i ran with the -verbose but no obvious errors there either.

**Comment by matthewlroth** [comment]
i commented out those lines and the script ran with no issues.

**Comment by vScripter** [comment]
Which lines; 206 & 207 inside `vCheck.ps1` ?

**Comment by matthewlroth** [comment]
Correct

**Comment by Sneddo** [comment]
There's probably no harm in removing that- I'm trying to remember why I put that in there in the first place. I suspect it was due to how tables were formatted in older versions of the script...

**Comment by Sneddo** [comment]
This should now be fixed.
