### ISSUE TITLE
vCheck does not honor -outputpath location, attempts to append additional directory

### ISSUE THREAD

**Issue by three18ti** [alanrenouf/vCheck-vSphere#385]
Hello,

According to the documentation the `-outputpath` parameter can be used to specify the location where the HTML file is saved:

    Output File

    Some people like to save a copy of the HTML for future reference or so they can go back and see when a problem started happening, to do this use the –OutputPath parameter and specify a location where the HTML will be saved, to do this run the script as follows:

    1
    .\vCheck.ps1 –OutputPath C:\vCheckOutput\DailyReports

However, this does not appear to work as the script attempts to append "archives" to the path:

    PowerCLI > .\vCheck.ps1 -OutputPath C:\inetpub\wwwroot
    Invoke-Item : Cannot find path 'C:\inetpub\wwwroot\Archives ... <snip paths containing hostnames>

Essentially, I would like to dump the html files into my webroot for viewing. How do I specify the exact path where the files will be dumped?

Thanks,
Jon

**Comment by Sneddo** [comment]
Not a bad idea to change this. If an $Outputpath is specified, we should just use that rather than appending archives/servername

**Comment by Sneddo** [comment]
This is fixed in the latest dev release.
