### ISSUE TITLE
vCheck unable to detect when datastore alarm is disabled

### ISSUE THREAD

**Issue by akarthikeyan16** [alanrenouf/vCheck-vSphere#387]
Hi Friends,

We are using the great vCheck script in our environment and noticed that from the report it shows only host with alarms disabled and unable to display the datastore with alarms disabled.

Could you kindly advise if there are any plugins to pull datastore with alarms disabled.
Please advise.

Thanks,

**Comment by akarthikeyan16** [comment]
Hi Sneddo,

Im awaiting for your reply. It will be very helpful any information.
Can vCheck pull datastore with alarms disabled ?

Please advise,

Thanks,
AK

**Comment by vScripter** [comment]
AK,

I don't think we are currently pulling this but we have marked this issue as an enhancement and will include it in a future version. Please stay tuned to new releases; we will close this issue once it's implemented. Thanks!

**Comment by Sneddo** [comment]
It's a simple enough plugin, effectively the same as the host alarms but using $Datastores instead.

I'll try to get to it tomorrow unless someone beats me to it.

**Comment by akarthikeyan16** [comment]
Hi Sneddo,

Thanks, Let us know once the host alarm plugin is modified to check for datastore alarms.
It will be really helpful.

Thanks,
AK

**Comment by Sneddo** [comment]
Hey sorry, been a busy week. Give this a try, should do what you want:
```
# Start of Settings 
# End of Settings 

$Datastores | where {!$_.ExtensionData.AlarmActionsEnabled} | Select Name, @{n='AlarmActionsEnabled'; e={$_.ExtensionData.AlarmActionsEnabled}}

$Title = "Datastores with Alarms Disabled"
$Header = "Datastores with Alarms Disabled"
$Comments = "Datastores with Alarms Disabled"
$Display = "Table"
$Author = "John Sneddon"
$PluginVersion = 1.0
$PluginCategory = "vSphere"
```
