### ISSUE TITLE
vCheck-Tools in config-gui branch

### ISSUE THREAD

**Issue by MasterChiefJon** [alanrenouf/vCheck-vSphere#392]
I was playing with this Thursday, trying to get it to work and was getting an XAML error.  I figured out that line 29 was trying to store the path with "\vCheck" appended to the end of the path.  When I run this tool, I am in the directory that contains the vCheck.ps1, so there is no sub-directory under that named "\vCheck".  When I removed the part that appends "\vCheck" to the ScriptPath variable, the script worked fine for me.

**Comment by Sneddo** [comment]
Yep, good catch. Was a pretty quick commit just to merge the code into the one repo. Will fix it up now
