### ISSUE TITLE
13 Invalid or inaccessible VMs Additional Information

### ISSUE THREAD

**Issue by MasterChiefJon** [alanrenouf/vCheck-vSphere#393]
When this plugin runs, if the "ConnectionState of any VMs are "invalid" or "inaccessble", it lists the VM name.  I would like to have it display some additional information about each VM including what is the ConnectionState & PowerState, and what is the IPAddress of the Guest VM.

I got it to display what I want on the Command-line, but not within the framework of vCheck (so it doesn't display properly in my HTML report).

How can I add those 3 additional properties to the output of this plugin?

**Comment by Sneddo** [comment]
You just need to include them in the object the gets written out. Should be pretty much the same as what you did on the command line.

Post the code you have and we can see why it isn't working for you.

**Comment by MasterChiefJon** [comment]
The additional data is not (directly) in the FullVM object, it's in a sub-object (not the correct terminology I know), so I would have to "select" something like this:  
`Select Name, $_.Runtime.ConnectionState, $_.Runtime.PowerState, $_.Guest.IpAddress

...and I couldn't get that to work in the existing select.  Here's what I did to get it to display on the command-line:

`ForEach ( $indVM in $FullVM ) { Write-Host $indVM.Name "    "  $indVM.Runtime.ConnectionState "    "  $indVM.Runtime.PowerState "    " $indVM.Guest.Hostname "    " $indVM.Guest.IpAddress }

Not pretty and it doesn't display properly in the HTML output.

**Comment by Sneddo** [comment]
Simple, use calculated properties:

Select Name, @{Name="ConnectionState";e={$_.Runtime.ConnectionState}}, @{Name="PowerState";e={$_.Runtime.PowerState}}, @{Name="IpAddress";e={$_.Guest.IpAddress}}

**Comment by MasterChiefJon** [comment]
Sweet. tested it and ended up with the following command:

    $BlindedVM = $FullVM | Where {$_.Runtime.ConnectionState -eq "invalid" -or $_.Runtime.ConnectionState -eq "inaccessible"} | Sort Name | `
	Select Name, @{Name="ConnectionState";e={$_.Runtime.ConnectionState}}, @{Name="PowerState";e={$_.Runtime.PowerState}}, @{Name="IP_Address";e={$_.Guest.IpAddress}}

One caveat, the VM has to be powered on in order for the plugin to get the IP address from it.

Can you paste this change into the plugin?
