### ISSUE TITLE
vCheck asking for credentials with vCenter Appliance 

### ISSUE THREAD

**Issue by bexinul** [alanrenouf/vCheck-vSphere#394]
Hello,

 

I am currently building a new environment using vSphere 6.

 

I installed a vCenter Appliance 6.

 

I want to use my good old daily vCheck (latest version available).

 

When I run it against my new vCenter Appliance 6 it keeps asking me for my credentials...

 

I tried to use the same script to run it against my "old" Windows vCenter 5.5 and it doesn't ask me for credentials.

 

This is problematic as I want to schedule the vCheck...

 

vCenter Appliance is joined to active directory, AD authentification is working correctly.

 

FQDN is correctly set.

 

I am using PowerCLI 6 Release 1.

 

Thanks in advance for your help!

**Comment by Sneddo** [comment]
Does Connect-VIServer work for you without credentials prompt?

**Comment by bexinul** [comment]
No, I have the same problem, it is asking for credentials... so doesn't come from the vCheck sorry :-(

VMware support forwarded me to thie website...

**Comment by Sneddo** [comment]
Yeah, VMware support is pretty rubbish unfortunately :(

I guess I'll close this off since it is not an issue with vCheck itself, but appears to be a larger issue with authenticating against VCSA 6.0
