### ISSUE TITLE
Scripted vCheck doesnt send email, but same parameters supplied via command line does.

### ISSUE THREAD

**Issue by tquizzle** [alanrenouf/vCheck-vSphere#395]
I don't get it. I used to run vCheck this way for years but the past couple of months it just hasn't worked as before.

As title suggests, I have a script that is setup as a scheduled task on Windows.

Contents of my script are as follows
` C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -file "C:\_VMware\vCheck\vCheck.ps1" -OutputPath \\path\to\my\share\vCenter-Reports
`

When I run this manually, it sends me an email as specified in the variables as well as saves the html file to the "OutputPath". When ran via a scheduled task, it only creates the file in the "OutputPath" and does not send an email.

What could be the cause of this? Am I missing something?

**Comment by Sneddo** [comment]
Is the scheduled task running as the same user? Does your SMTP server require authentication or anything?

**Comment by tquizzle** [comment]
Yes, the user that runs the scheduled task is me. Its configured to run as me. I've tried configuring it with another user but get the same results. 

SMTP is relaying off of the Exchange Server and does not require auth.

**Comment by tquizzle** [comment]
Out of the blue, it started working again. I've not changed anything in my environment to account for this, but for now it is working.

**Comment by anthonyrhook** [comment]
Blame Exchange ;).
