### ISSUE TITLE
Exclude specific vmkernel warning

### ISSUE THREAD

**Issue by willemdh** [alanrenouf/vCheck-vSphere#397]
Is it possible to exclude specific vmkernel warnings? These warnings are included a lot in the report, but this seem to be 'normal' on esx servers that have vm's which have snapshots:

2015-06-17T01:49:57.472Z cpu14:270797)WARNING: CBT: 1006: Unsupported ioctl 58

**Comment by randy16randy** [comment]
Hi Willem

I had exactly the same issue.   Here is the script version I have and the modified line highlighted.

Thanks
-Randy-

Filter out extraneous/invalid vCheck warnings relating to storage latency
Add highlighted section below


# Start of Settings
# End of Settings

$VMKernelWarnings = @()
foreach ($VMHost in ($HostsViews)){

            $product = $VMHost.config.product.ProductLineId
            if ($product -eq "embeddedEsx" -and $VIVersion -lt 5){
                        $Warnings = (Get-Log -vmhost ($VMHost.name) -Key messages -ErrorAction SilentlyContinue).entries |where {$_ -match "warning" -and $_ -match "vmkernel"}
                        if ($Warnings -ne $null) {
                                    $VMKernelWarning = @()
                                    $Warnings | % {
                                                $Details = "" | Select-Object VMHost, Message, Length, KBSearch, Google
                                                $Details.VMHost = $VMHost.Name
                                                $Details.Message = $_
                                                $Details.Length = ($Details.Message).Length
                                                $Details.KBSearch = "<a href='http://kb.vmware.com/selfservice/microsites/search.do?searchString=$Message&sortByOverride=PUBLISHEDDATE&sortOrder=-1' target='_blank'>Click Here</a>"
                                                $Details.Google = "<a href='http://www.google.co.uk/search?q=$Message' target='_blank'>Click Here</a>"
                                                $VMKernelWarning += $Details
                                    }
                                    $VMKernelWarnings += $VMKernelWarning | Sort-Object -Property Length -Unique |select VMHost, Message, KBSearch, Google
                        }
            }
            else
            {
                        $Warnings = (Get-Log –VMHost ($VMHost.Name) -Key vmkernel -ErrorAction SilentlyContinue).Entries | where {$_ -match "warning" -and $_ -notmatch "unsupported ioctl 58"}
                        if ($Warnings -ne $null) {
                                    $VMKernelWarning = @()
                                    $Warnings | % {
                                                $Details = "" | Select-Object VMHost, Message, Length, KBSearch, Google
                                                $Details.VMHost = $VMHost.Name
                                                $Details.Message = $_
                                                $Details.Length = ($Details.Message).Length
                                                $Details.KBSearch = "<a href='http://kb.vmware.com/selfservice/microsites/search.do?searchString=$($Details.Message)&sortByOverride=PUBLISHEDDATE&sortOrder=-1' target='_blank'>Click Here</a>"
                                                $Details.Google = "<a href='http://www.google.co.uk/search?q=$($Details.Message)' target='_blank'>Click Here</a>"
                                                $VMKernelWarning += $Details
                                                }
                                    $VMKernelWarnings += $VMKernelWarning | Sort-Object -Property Length -Unique |select VMHost, Message, KBSearch, Google
                        }
            }
}

$VMKernelWarnings | sort Message -Descending

$Title = "VMKernel Warnings"
$Header =  "ESX/ESXi VMKernel Warnings: $(@($VMKernelWarnings).Count)"
$Comments = "The following VMKernel issues were found, it is suggested all unknown issues are explored on the VMware Knowledge Base. Use the below links to automatically search for the string"
$Display = "Table"
$Author = "Alan Renouf"
$PluginVersion = 1.1
$PluginCategory = "vSphere"

**Comment by willemdh** [comment]
Seem your solution worked. Thanks!
