### ISSUE TITLE
Run vCheck against a Datacetner, not entire vCenter

### ISSUE THREAD

**Issue by edsekula** [alanrenouf/vCheck-vSphere#404]
is it possible to run daily vCheck against a specific DataCenter and not the enitire vCenter?

**Comment by Sneddo** [comment]
Sure, just filter the objects in the connection plugin:
/Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1

**Comment by mekmiotek** [comment]
Anyone know what the syntax would be to exclude a Datacenter called "QALAB"?

Also what line would it be added to in the /Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1 file?

Thanks!

**Comment by mekmiotek** [comment]
We have 2 datacenters, and want to exclude 1

Will this work:

Add this to the top:
$myDatacenter = "ProdDataCenter"

Modify line 116 as follows:

$VM = Get-VM -Location $myDatacenter| Sort Name 

Thanks.

**Comment by danimalrowe** [comment]
We could add an optional parameter to the param in vCheck.ps1 where the DataCenter is passed in.  If the DataCenter is passed in then some of the commands in the Connection Plugin would add the -Location option to them.  This is what I have setup:

Change vCheck.ps1
    [CmdletBinding()]
    param (
        [Switch]$config,

        [ValidateScript({ Test-Path $_ -PathType 'Container' })]
        [string]$Outputpath=$Env:TEMP,

        [ValidateScript({ Test-Path $_ -PathType 'Leaf' })]
        [string]$job,

        [string]$Server = "vcServer01",

        [string]$DataCenter = ""

)

00 Connection Plugin for vCenter.ps1
    if ( $DataCenter ) {
        Write-CustomOut $pLang.collectVM
        $VM = Get-VM -Location "$DataCenter" | Sort Name
        Write-CustomOut $pLang.collectHost
        $VMH = Get-VMHost -Location "$DataCenter" | Sort Name
        Write-CustomOut $pLang.collectCluster
        $Clusters = Get-Cluster -Location "$DataCenter" | Sort Name
        Write-CustomOut $pLang.collectDatastore
        $Datastores = Get-Datastore -Location "$DataCenter" | Sort Name
     } else {
        Write-CustomOut $pLang.collectVM
        $VM = Get-VM | Sort Name
        Write-CustomOut $pLang.collectHost
        $VMH = Get-VMHost | Sort Name
        Write-CustomOut $pLang.collectCluster
        $Clusters = Get-Cluster | Sort Name
        Write-CustomOut $pLang.collectDatastore
        $Datastores = Get-Datastore | Sort Name
    }

**Comment by danimalrowe** [comment]
Added the code for command line parameters Server and DataCenter to DEV.  See Pull Request #489

**Comment by Sneddo** [comment]
Closing this issue. Global filters are a long-standing issue- #169
