### ISSUE TITLE
Email Error

### ISSUE THREAD

**Issue by waterwalker23** [alanrenouf/vCheck-vSphere#408]
I'm brand new to vCheck and pretty new to PowerShell/PowerCLI.  Can someone help with the following error?  The report is working, but email is not being sent. Our environment is Exchange 2013.

Exception calling "Send" with "1" argument(s): "The remote certificate is invalid according to the validation procedure."
At C:\scripts\vCheck\vCheck.ps1:818 char:4
+    $smtpClient.Send($msg)
+    ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : AuthenticationException

**Comment by Sneddo** [comment]
This is an issue with your SMTP server, looks like you have an invalid cert (expired, wrong hostname, etc.) 

You might be able to insert the following before you send the email (say around line 841)
    ServicePointManager.ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true;

This basically forces certificate validation to return true- though not sure this will apply to SMTP certs. You would probably be better off fixing the problem with your mail server.

**Comment by waterwalker23** [comment]
Thank you for your help.  I have resolved this.
