### ISSUE TITLE
How to get multiple vCenter report together 

### ISSUE THREAD

**Issue by lbxsunil** [alanrenouf/vCheck-vSphere#409]
Hi SME,
I have 2 vCenter where I want to run this script single time to get the report together, is this possible…

I am having vCenter in different domain and guest os in different domain so I want to exclude that part as services account do not have access to guest os domain and because of that I am getting below error while running the script.

Get-HardDisk : 7/28/2015 3:07:32 PM    Get-HardDisk        The underlying
connection was closed: Could not establish trust relationship for the SSL/TLS
secure channel.
At C:\Users\495658\Desktop\Sunil\vCheck-vSphere-master\Plugins\60 VM\106 Find
Phantom Snapshots.ps1:8 char:28
+     $theVMdisks = $theVM | Get-HardDisk
+                            ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-HardDisk], ViError
    + FullyQualifiedErrorId : Client20_QueryServiceImpl_RetrievePropertiesEx_V
   iError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.GetHardD
  isk

Get-HardDisk : 7/28/2015 3:07:32 PM    Get-HardDisk        The underlying
connection was closed: Could not establish trust relationship for the SSL/TLS
secure channel.
At C:\Users\495658\Desktop\Sunil\vCheck-vSphere-master\Plugins\60 VM\106 Find
Phantom Snapshots.ps1:8 char:28
+     $theVMdisks = $theVM | Get-HardDisk
+                            ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-HardDisk], ViError
    + FullyQualifiedErrorId : Client20_QueryServiceImpl_RetrievePropertiesEx_V
   iError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.GetHardD
  isk
-----------------------------------------------------------------------------------
 Note :- Its takeing approx 2 hr to finish the task for one vcenter.

Thanks So Much 
Sam

**Comment by Sneddo** [comment]
See issue #217 for more information on this issue.
