### ISSUE TITLE
vmkernel logs are restricted by 24 hours

### ISSUE THREAD

**Issue by gronau-it-cloud-computing** [alanrenouf/vCheck-vSphere#410]
is there a possibility to expand 44 VMKernel Warnings.ps1 to have variable to determinate vmkernel logs for example for 10 days.

many thanks in advance

vPierre

**Comment by Sneddo** [comment]
Well, it isn't necessarily 24 hours either. The default config for the vmkernel log is to rotate at 1MB. You can see this by running `esxcli system syslog config logger list`. You can also see this in the Advanced Settings section of the vSphere client under syslog/loggers/vmkernel.

The cmdlet that is used for fetch the vmkernel warnings if Get-Log, which essentially just returns the current /scratch/log/vmkernel.log. Changing the logic of this plugin to pull down the gzipped archives and iterate over them is probably more effort that it is worth.

So, if you want to return more items you would need to change the config on each ESX server to retain a larger logfile.

Alternatively, setup a syslog server and pull results from it instead. E.g. you could use [SexiLog(http://www.sexilog.fr/)
