### ISSUE TITLE
Plugin to get host utilization

### ISSUE THREAD

**Issue by lp1504** [alanrenouf/vCheck-vSphere#411]
Hi,

How can we incorporate a plugin to get the host memory utilization? It's not for auditing but we just need to monitor all hosts which are, say, more than 75% utilized.

Thx,
LP

**Comment by Sneddo** [comment]
See the [Plugin structure wiki page](https://github.com/alanrenouf/vCheck-vSphere/wiki/Plugin-structure).

Then just add your logic, something like `$vmh | Where {($_.MemoryUsageMB/$_.MemoryTotalMB) -gt 0.75} | Select Name, @{"Name"="Memory usage %";Expression={($_.MemoryUsageMB/$_.MemoryTotalMB)*100}}`

**Comment by lp1504** [comment]
Thanks, but I am not sure how it fits within the plugin. Is something like below looks fine?

# Start of Settings
# End of Settings

# Setup plugin-specific language table
$pLang = DATA {
   	ConvertFrom-StringData @' 
     	pluginActivity = Checking overcommit state for hosts
'@
}

# Override the defaults (en) if language file exists in lang driectory
Import-LocalizedData -BaseDirectory ($ScriptPath + "\lang") -BindingVariable pLang -ErrorAction SilentlyContinue

$ResUtil = @()
$VMHCount = $VMH | Measure
Foreach ($VMHost in $VMH) 
{
$ResUtil = $VMH | Where {($_.MemoryUsageMB/$_.MemoryTotalMB) -gt 0.75} | Select Name, @{"Name"="Memory usage %";Expression={($_.MemoryUsageMB/

$_.MemoryTotalMB)*100}}
}


# generate your report content here. Simple placeholder hashtable for the sake of example
@{"Plugin"="Hosts Resource utilization"}

$Title = "Resource utilization for the hosts"
$Header =  "Hosts above the 75% threshold : $(@($ResUtil).count)"
$Comments = "Over utilized hosts cause performance issues in the environment which may result in deteriorating performance for the underlying virtual machines. Please analyse and report accordingly"
$Display = "Table"
$Author = "LP"
$PluginVersion = 1.0
$PluginCategory = "vSphere"

**Comment by Sneddo** [comment]
Close. You have a heap of redundant code though. 

      # Start of Settings
      # End of Settings

      $ResUtil = $VMH | Where {($_.MemoryUsageMB/$_.MemoryTotalMB) -gt 0.75} | Select Name, @{"Name"="Memory usage %";Expression={($_.MemoryUsageMB/$_.MemoryTotalMB)*100}}
      $ResUtil
      
      $Title = "Resource utilization for the hosts"
      $Header =  "Hosts above the 75% threshold : $(@($ResUtil).count)"
      $Comments = "Over utilized hosts cause performance issues in the environment which may result in deteriorating performance for the underlying virtual machines. Please analyse and report accordingly"
      $Display = "Table"
      $Author = "LP"
      $PluginVersion = 1.0
      $PluginCategory = "vSphere"

**Comment by lp1504** [comment]
Thanks, works as expected, I will build the same for CPU. Just a couple of questions, since naive on this:
1. The value for the percentage is coming as 88.07092511357235465251273786. Can we round this to two digits after decimal?
2. Where is it picking $VMH value from? I do not see the variable in the script neither it's there in Global variables.

**Comment by lp1504** [comment]
Got the reply for point 2, found it in vcenter connection plugin..thx!

**Comment by Sneddo** [comment]
Sure, just use the standard round() function.

     $ResUtil = $VMH | Where {($_.MemoryUsageMB/$_.MemoryTotalMB) -gt 0.75} | Select Name, @{"Name"="Memory usage %";Expression={[Math]::Round(($_.MemoryUsageMB/$_.MemoryTotalMB)*100,2)}}

**Comment by lp1504** [comment]
yep, that's what was looking for..another doubt, i wanted to exclude a few datastores which I did during the -config wizard (comma separated) but they still appear in the list..can you let me know where can i manually check the entry and modify it in the script.

**Comment by Sneddo** [comment]
There isn't any global filtering of datastores, so you probably just added them to the specific plugin.

However, if you do want to remove certain datastores completely, you can filter them out in pluings\00 Initialize/00 Connection Plugin for vCenter.ps1

**Comment by lp1504** [comment]
Presumably, I wasn't clear the last time. What I meant was there was a section where we can explicitly filter out multiple datastores for the below two sections. This does not seem to be present in Initialize plugin. Also when specifying multiple datastores over the command line via vcheck -config the datastores are still not excluded

Datastore Information
# Set the warning threshold for Datastore % Free Space [25]: 20
# Do not report on any Datastores that are defined here (Datastore Free Space Plugin) [local]:

Datastore OverAllocation
# Datastore OverAllocation % [50]:
# Exclude these datastores from report [datastore1,datastore2,datastore3,datastore4]:

**Comment by Sneddo** [comment]
Yeah sorry, I wasn't sure exactly what you were asking :)

The Datastore Information filter works for me, as we have all our local datastores with -local appended to the server name which do not show in our report.

Bear in mind these filters generally use the -notmatch operator, so you want to use regular expressions. So for example `datastore[1-4]` to exclude datastores named datastore1,datastore2,datastore3,datastore4

**Comment by lp1504** [comment]
For some reason it still doesn't work for me, anyplace where I can hard code it?

**Comment by lp1504** [comment]
Hi, any updates on this? I actually tried doing it for several other sections including vmtools issues, no vm tools, datastores over certain% etc.. but it works fine till there is only 1 value. When I have multiple entries separated by comma it simply doesn't exclude them.

**Comment by lp1504** [comment]
Please ignore, got the solution!
