### ISSUE TITLE
Credential Storage

### ISSUE THREAD

**Issue by omrsafetyo** [alanrenouf/vCheck-vSphere#412]
I'm not really sure this is an issue, per se.  But I have been working on scheduling vCheck to run on a daily basis, across 2 vCenters.  I have this up and running now, and the report is archiving to a folder on my batch job server, where I can access it.  I expect to utilize this for audit purposes - SSAE-16, SOC-1, and SOC-2.

One item that I ran into, was that I initially ran the script under my own account. When I ran it against one of the 2 vCenters, I didn't have admin privileges, and couldn't make WMI calls against the vCenter server, so the following 3 plugins had issues:
41 vCenter Services.ps1
42 Windows vCenter Error Event Logs.ps1
43 Windows vCenter Warning Event Logs.ps1

They prompted me for credentials, and I provided some that worked, and the credentials were cached.  From then on it worked.  However, when I went to schedule it, I had some failures:

ConvertTo-SecureString : Key not valid for use in specified state.

At C:\vCheck\Plugins\10 vCenter\41 vCenter Services.ps1:7 char:124
+ ... als.Password | ConvertTo-SecureString))
+                    ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ConvertTo-SecureString], CryptographicException
    + FullyQualifiedErrorId : ImportSecureString_InvalidArgument_CryptographicError,Microsoft.PowerShell.Commands.Conv 
   ertToSecureStringCommand
 
New-Object : Exception calling ".ctor" with "2" argument(s): "Cannot process argument because the value of argument 
"password" is null. Change the value of argument "password" to a non-null value."
At C:\vCheck\Plugins\10 vCenter\41 vCenter Services.ps1:7 char:12
+         $creds = New-Object System.Management.Automation.PsCredential($LoadedCredentia ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

After a little research, I found this was because the stored credentials, as used in vCheck, can only be re-used by the same user on the same machine which they were cached from.  I was switching users, and machines, by going to my batch job server, and scheduling it as a service account.

So, the solution I came up with was to cache, and retrieve the credentials using a key.

```PowerShell
$cred = Get-Credential
$credCopy = $cred | select *
$key = (0,1,56,34,254,222,1,100,2,23,42,54,33,233,10,34,2,7,6,5,37,43,6,254,6,62,63,61,31,33,60,28)
$credCopy.Password = $credCopy.Password | ConvertFrom-SecureString -key $key
$CredCopy | Export-Clixml Windowscreds.xml
```

(Not my real key)

And then in each of the 3 plugins which used the cached credentials, I used the key to retrieve it:
```PowerShell
$key = (0,1,56,34,254,222,1,100,2,23,42,54,33,233,10,34,2,7,6,5,37,43,6,254,6,62,63,61,31,33,60,28)
$LoadedCredentials = Import-Clixml Windowscreds.xml
$creds = New-Object System.Management.Automation.PsCredential($LoadedCredentials.Username,($LoadedCredentials.Password | ConvertTo-SecureString -key $key))
```

Now, I'm not sure this is the best approach.  Perhaps I should just log into the server as the service account I intend to schedule the job, and cache the credentials that way - I'm not really sure.  I was hoping we could discuss the solution I came up with, the drawbacks (security, specifically of storing the key in plain text), and potential solutions for those drawbacks.  Or should I really just cache the credentials as the user I intend to run it as, on the server I intend to run it?

**Comment by Sneddo** [comment]
Yeah, generally it is better (or at least more secure) to run vCheck manually with the service account once to configure it. This does sometimes cause confusion if you are trying to run with different accounts though, I almost think we need to change the filename to append the username of the account or something.

However, provided your host is sufficiently secured, and the service account has read-only access to vCenter, there shouldn't be any negative impact to doing it this way. Bear in mind it is only just above saving the password in plain text however.

**Comment by omrsafetyo** [comment]
Right, I knew storing the key right where I used it to decrypt the password wasn't particularly secure, which is why I brought it up.  I was wondering if there was a better way.  The way it's currently implemented does seem the most secure, but also the least portable.  I guess that's always the trade-off.  

I personally have a password vault that can allow the service account to retrieve the key at run-time, and secure the key in that manner, which does give the best of both worlds, so long as the account doesn't change, or at least the access is granted to the new account when it is changed.  I didn't know, though if perhaps the current solution was just an oversight that could be fixed in a way I wasn't think about.
