### ISSUE TITLE
Different way of handling script configurations

### ISSUE THREAD

**Issue by phathocker** [alanrenouf/vCheck-vSphere#419]
I was wondering if there was a way to centralize all of the plugin script's variables into the GlobalVariables.ps1 file.  This would allow easier git pulls and could allow you to add a .gitignore for the file similar to how [GitHub Backup Utils](https://github.com/github/backup-utils) works.  I guess the SelectPlugins script would also need to be updated because it would be better to select plugins from some file rather than moving Git tracked files inside the repository.

You would then just be able to "source" those variables or pass them from the vCheck.ps1 script instead of doing the below code:

```
# Start of Settings
# Orphaned Delta File: Exclude datatores by DS name? (regex)
$excludeDatastoreRegex = ''
# Orphaned Delta File: Exclude VMs by VM path (regex)
$excludeVMPathRegex = ''
# End of Settings
```

**Comment by Sneddo** [comment]
Has been discussed previously in issue #361

I agree, the handling of settings needs quite a bit of work. It just needs someone with the time to implement the changes.

**Comment by phathocker** [comment]
Great. I'll add my thoughts to #361 then and close this issue.
