### ISSUE TITLE
No vCheck Updates in 4 Months?

### ISSUE THREAD

**Issue by MasterChiefJon** [alanrenouf/vCheck-vSphere#421]
The various repository branches show that the most recent commit was 4 months ago.  Has development for this software stopped?

**Comment by Sneddo** [comment]
At the moment I have a couple of large projects at work taking up most of my time, so really just replying to issues at the moment and not really tackling any coding :/

Not helped by the fact the next steps are fairly big ones as well- settings handling, config GUI, etc.

**Comment by MasterChiefJon** [comment]
I'm glad to hear that this project has not been abandoned, and I'm excited to hear that "settings handling" is coming in the future.  I really like vCheck and our organization definitely uses it.

**Comment by kavanaghtech** [comment]
Especially with PowerCLI 6 R2 with modules versus snapins

**Comment by Sneddo** [comment]
The great thing about vCheck being hosted on Github is that it's nice and easy for other people to contribute as well :)
