### ISSUE TITLE
vCloud check requirement

### ISSUE THREAD

**Issue by Javedshai** [alanrenouf/vCheck-vSphere#422]
Hi Alan,
One things i observed where VM details are listed it is not listed withOrgvdc details.
 I don’t know how to get these informations. Need your help.

1] Will it be possible to get OrgvDC name list along with list of vApps and their details. 
#Code used as below.
$CIVApp | Select Org, OrgvDC, Name, Description, Enabled, CPUCount, SizeGB, MemoryAllocationMB | Sort Org, OrgvDC, Name

2] I am not getting the VMs disk size in VM Detailed Information plugins
#Code used as below.
$CIVM | Select Org, OrgVDC, Name, Status, GuestOSFullName, CPUCount, MemoryGB, storageGB, VmVersion, vApp, Description

3]  CPUUsedGHz information is missing List of all VDCs
#Code used as below.
$AllOrgs = @()
Foreach ($Org in $OrgVDC) {
    $TotalCPUUsedGhz = ($VMCPUUsage | Where { $_.OrgVDC -eq ($org.Name) } | Measure-Object -Property CPUUsageMHzAvg -Sum).Sum * 0.001
    $AllOrgs += $Org | Select Name, AllocationModel, Enabled, @{Name="CPUUsedGHZ";Expression={"$TotalCPUUsedGhz"}}, CPULimitGhz, MemoryUsedGB, MemoryLimitGB, StorageUsedGB, StorageLimitGB
}

$AllOrgs

**Comment by monahancj** [comment]
I don't know how many people use vCloud.  All those commands will fail in an a non vCloud environment.  If you submitted those as new vCloud specific plugins then they could be enabled/disabled as needed.

**Comment by smasterson** [comment]
For vCD info try this version instead - https://github.com/alanrenouf/vCheck-vCD
I run both reports against our vCD environment as they report on different things.

**Comment by monahancj** [comment]
That would be a much better solution.  :)
