### ISSUE TITLE
Latest link to download - EASY VSWITCH & PORTGROUP SETUP.

### ISSUE THREAD

**Issue by akarthikeyan16** [alanrenouf/vCheck-vSphere#424]
Hello Friend,

I would like to know the link to download the latest script to setup " EASY VSWITCH & PORTGROUP SETUP. 

Please provide me the link to download and setup.

t will be very usefule as we are setting up a new environment with dozens of hosts.

Thanks,
Karthik

**Comment by akarthikeyan16** [comment]
Hi Sneddo... May i know why the case was closed ?

**Comment by Sneddo** [comment]
Because it has nothing to do with vCheck. If you need a script from Alan, contact him via twitter or his website.
