### ISSUE TITLE
How to run script against DataCenter rather than VC

### ISSUE THREAD

**Issue by djbeenie** [alanrenouf/vCheck-vSphere#425]
We have a very large VC and some DCs are global. The script starts erroring out around the end of the script because it takes so long.  Would like to run it against a smaller DC than the whole VC.  Or is there a way to exclude certain DCs.  Either way, what is the best route.  Thanks!

**Comment by Sneddo** [comment]
See #404, just down the list of open issues.

**Comment by djbeenie** [comment]
Yeah but hat do you edit?

**Comment by Sneddo** [comment]
There isn't any really great way to do this at the moment, you just have to filter each of the Get-* cmdlets using the location parameter or Where-Object.
