### ISSUE TITLE
Add value configured in the report

### ISSUE THREAD

**Issue by RahimB** [alanrenouf/vCheck-vSphere#427]
Hi,

In the vCheck when the value match was is configured, this is not appearing in the report that is fine but the problem is that if the value set to be checked is wrong and the servers are well configured against this wrong value, then we never know that for our example the syslog server is not the correct one.

The idea will be when checking to allow the report to show a ALL OK value with the configured value from the scripts.

SYSLOG - ALL OK - value set 192.168.0.220

This will allows to know quickly what is configured from the web page reports then all the rest don't need to be showed. Just a 1 line OK statement. 

Please let me know if this is not clear

Thanks
Rahim

**Comment by Sneddo** [comment]
This sort of goes against the ethos of vCheck, which is designed more as an at-a-glance report of issues in a vSphere environment. By adding this, we start to move towards more of an auditing script.

That said, there is nothing stopping you from writing a plugin to do just this. https://github.com/alanrenouf/vCheck-vSphere/wiki/Plugin-structure

**Comment by RahimB** [comment]
Hi Alan,

 

Many thanks for your answers. I will try to add a plugin to report the values in used

 

Regards

Rahim

**Comment by monahancj** [comment]
We already have a lot of plugins.  If another plugin was written for every static configuration setting you'd like to see there could be a lot more.  It sounds like you're asking to see every day in an email a setting that should never change.  I feel like that information should be in your site documentation, however you store that.

  If you want to see the correct value in vCheck when there are hosts with incorrect values showing in the report that information can be shown in the header and comment lines of that section/plugin.  The plugin "34 Number of VMs per Datastore.ps1" is a good example of that.
