### ISSUE TITLE
Send E-mail Does Not Work in vCheck.ps1

### ISSUE THREAD

**Issue by surfingcaliforniacoastline** [alanrenouf/vCheck-vSphere#433]
The vCheck script finishes but I get an error when it tries creating the output file and shows this error Out-File : The given path's format is not supported.

see full error message below...

[13:56:51] ..start calculating Disconnecting from vCenter by Alan Renouf v1.1 [106 of 106]
[13:56:51] ..finished calculating Disconnecting from vCenter by Alan Renouf v1.1 [106 of 106]
Out-File : The given path's format is not supported.
At C:\scripts\vCheck\vCheck.ps1:767 char:16
+ $embedReport | Out-File -encoding ASCII -filepath $Filename
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], NotSupportedException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

[13:56:54] ..Displaying HTML results
Invoke-Item : Cannot find path 'C:\Users\jarzynka\AppData\Local\Temp\4\natty.ad.salk.edu:443_vCheck_16-12-2015.htm' because it does
not exist.
At C:\scripts\vCheck\vCheck.ps1:772 char:4
+    Invoke-Item $Filename
+    ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\jarzyn..._16-12-2015.htm:String) [Invoke-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.InvokeItemCommand

[13:56:54] ..Sending Email
Exception calling "Send" with "1" argument(s): "The operation has timed out."
At C:\scripts\vCheck\vCheck.ps1:818 char:4
+    $smtpClient.Send($msg)
+    ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SmtpException

PowerCLI C:\scripts\vCheck>

**Comment by Sneddo** [comment]
Ah, looks like you have specified a port (which is irrelevant since 443 is the default), which is likely what has broken it. We're probably using the wrong variable name in vCheck.ps1...

**Comment by Sneddo** [comment]
OK, this is fixed in the dev branch but I've pushed a fix to master as well. Download the latest vCheck.ps1 and this should be OK.

**Comment by surfingcaliforniacoastline** [comment]
ok its working now but I get a new error when it actually tries to send the email

[15:36:39] ..Sending Email
Exception calling "Send" with "1" argument(s): "The operation has timed out."
At C:\scripts\vCheck\vCheck.ps1:818 char:4
+    $smtpClient.Send($msg)
+    ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SmtpException

**Comment by surfingcaliforniacoastline** [comment]
ok its working now but I get a new error when it actually tries to send the email

[15:36:39] ..Sending Email
Exception calling "Send" with "1" argument(s): "The operation has timed out."
At C:\scripts\vCheck\vCheck.ps1:818 char:4

*	$smtpClient.Send($msg)
*	~~~~~~~~~~~~~~~~~~~~~~ 

*	CategoryInfo : NotSpecified: (:) [], MethodInvocationException
*	FullyQualifiedErrorId : SmtpException

**Comment by surfingcaliforniacoastline** [comment]
I downloaded the latest master vCheck.ps1 but it still is not sending.

[09:17:35] ..finished calculating Disconnecting from vCenter by Alan Renouf v1.1 [105 of 105]
[09:17:38] ..Sending Email
Exception calling "Send" with "1" argument(s): "The operation has timed out."
At C:\scripts\vCheck\vCheck.ps1:818 char:4
+    $smtpClient.Send($msg)
+    ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SmtpException

**Comment by surfingcaliforniacoastline** [comment]
I downloaded the latest master vCheck.ps1 but it still is not sending.

[09:17:35] ..finished calculating Disconnecting from vCenter by Alan Renouf v1.1 [105 of 105]
[09:17:38] ..Sending Email
Exception calling "Send" with "1" argument(s): "The operation has timed out."
At C:\scripts\vCheck\vCheck.ps1:818 char:4

*	$smtpClient.Send($msg)
*	~~~~~~~~~~~~~~~~~~~~~~ 

*	CategoryInfo : NotSpecified: (:) [], MethodInvocationException
*	FullyQualifiedErrorId : SmtpException

**Comment by Sneddo** [comment]
Have a look at your SMTP server to see why it is timing out.

**Comment by surfingcaliforniacoastline** [comment]
I checked the logs and it never connects to my SMTP server –

This is our production SMTP server and we have lots of other scripts that relay mail through it.

Its as if it doesn’t try sending to my SMTP server.

 

I also ran a Send-MailMessage test from the server via powershell to verify I can send an email with attachment and it worked.

 

Send-MailMessage -To “jarzynka@salk.edu" -From “vCheck@salk.edu" -SMTPServer helix.salk.edu -Subject “Daily report” -Body “Attached file has details of Natty vCenter” -Attachments “C:\Users\jarzynka\AppData\Local\Temp\4\vCheck.html” 

 

 

Here are my global variables  settings:

 

# You can change the following defaults by altering the below settings:

#

 

 

# Set the following to true to enable the setup wizard for first time run

$SetupWizard = $False

 

 

# Start of Settings

# Report header

$reportHeader = "vCheck"

# Would you like the report displayed in the local browser once completed ?

$DisplaytoScreen = $false

# Display the report even if it is empty?

$DisplayReportEvenIfEmpty = $true

# Use the following item to define if an email report should be sent once completed

$SendEmail = $true

# Please Specify the SMTP server address (and optional port) [servername(:port)]

$SMTPSRV = "helix.salk.edu"

# Would you like to use SSL to send email?

$EmailSSL = $false

# Please specify the email address who will send the vCheck report

$EmailFrom = "vCheck@salk.edu"

# Please specify the email address(es) who will receive the vCheck report (separate multiple addresses with comma)

$EmailTo = "jarzynka@salk.edu"

# Please specify the email address(es) who will be CCd to receive the vCheck report (separate multiple addresses with comma)

$EmailCc = ""

# Please specify an email subject

$EmailSubject = "$Server vCheck Report"

# Send the report by e-mail even if it is empty?

$EmailReportEvenIfEmpty = $true

# If you would prefer the HTML file as an attachment then enable the following:

$SendAttachment = $true

# Set the style template to use.

$Style = "CleanGreen"

# Do you want to include plugin details in the report?

$reportOnPlugins = $true

# List Enabled plugins first in Plugin Report?

$ListEnabledPluginsFirst = $true

# Set the following setting to $true to see how long each Plugin takes to run as part of the report

$TimeToRun = $true

# Report on plugins that take longer than the following amount of seconds

$PluginSeconds = 30

# End of Settings

 

# End of Global Variables
