### ISSUE TITLE
Incompatible with vCenter 55u3b

### ISSUE THREAD

**Issue by shawnpd** [alanrenouf/vCheck-vSphere#435]
Many / most of the plugins will not run against the vCenter once 55u3b is applied to the vCenter.  One of the "features" of this updated includes disabling sslv3.  If there is a possible workaround other than re-enabling sslv3 across the infrastructure, it would prove very helpful.

**Comment by Sneddo** [comment]
hmmmmmm interesting. Haven't updated to 5.5U3b yet (actually planning to do this next week all things going well), so not really in a position to test at the moment.

Are you able to provide some of the errors/messages you are getting so I can have a look into it?

Also, what version of PowerCLI are you running?

**Comment by shawnpd** [comment]
Sneddo thank you for the very fast attention!  I am re-running the script against the vCenter now but the PowerCLI version is below

PowerCLI Version
----------------
   VMware vSphere PowerCLI 5.5 Release 2 Patch 1 build 1931983
---------------
Snapin Versions
---------------
   VMWare AutoDeploy PowerCLI Component 5.5 build 1890764
   VMWare ImageBuilder PowerCLI Component 5.5 build 1890764
   VMware License PowerCLI Component 5.5 build 1265954
   VMware VDS PowerCLI Component 5.5 build 1926677
   VMware vSphere PowerCLI Component 5.5 Patch 1 build 1926677

**Comment by Sneddo** [comment]
Maybe try the latest version of PowerCLI (6.0 Release 3) as a first step
https://blogs.vmware.com/PowerCLI/2015/11/powercli-6-0-release-3-has-arrived.html

**Comment by Sneddo** [comment]
OK, so I updated our vCenter to Update 3b this morning and vCheck is working fine with it. PowerCLI 6.0 Release 2

**Comment by shawnpd** [comment]
Thank you Sneddo … I will update my Powercli version and check the results.  Thanks again for the reply / tip!

**Comment by shawnpd** [comment]
I updated to PowerCLI 6.0 Release 2 and all of the plugins worked as before.  Thank you for the tip and calming my panic!
