### ISSUE TITLE
vCheck is not sending email

### ISSUE THREAD

**Issue by santoshchowdary07** [alanrenouf/vCheck-vSphere#436]
Hi,

I ran the vCheck.ps1 and it did not send me any email with the report. Below is the output screenshot.

![screen shot 2016-01-23 at 3 49 45 pm](https://cloud.githubusercontent.com/assets/16856897/12532740/42e2401c-c1e9-11e5-9fd1-fe1572cb0b02.png)

**Comment by Sneddo** [comment]
Can you post your config file? It looks like it's not even trying to send the email, either because the report is empty and $EmailReportEvenIfEmpty is $false, or because $SendEmail is set to $false

**Comment by santoshchowdary07** [comment]
Below is the configuration for my vcheck.

# You can change the following defaults by altering the below settings:
#


# Set the following to true to enable the setup wizard for first time run
$SetupWizard = $False


# Start of Settings
# Report header
$reportHeader = "ETCKWPVVC002 vCheck Report"
# Would you like the report displayed in the local browser once completed ?
$DisplaytoScreen = false
# Display the report even if it is empty?
$DisplayReportEvenIfEmpty = true
# Use the following item to define if an email report should be sent once completed
$SendEmail = true
# Please Specify the SMTP server address (and optional port) [servername(:port)]
$SMTPSRV = "servermail.coca-cola.com"
# Would you like to use SSL to send email?
$EmailSSL = $false
# Please specify the email address who will send the vCheck report
$EmailFrom = "eKOvC002@na.ko.com"
# Please specify the email address(es) who will receive the vCheck report (separate multiple addresses with comma)
$EmailTo = "kovirtualizationteam.nar@capgemini.com"
# Please specify the email address(es) who will be CCd to receive the vCheck report (separate multiple addresses with comma)
$EmailCc = ""
# Please specify an email subject
$EmailSubject = "ETCKWPVVC002 vCheck Report"
# Send the report by e-mail even if it is empty?
$EmailReportEvenIfEmpty = $true
# If you would prefer the HTML file as an attachment then enable the following:
$SendAttachment = $false
# Set the style template to use.
$Style = "VMware"
# Do you want to include plugin details in the report?
$reportOnPlugins = $true
# List Enabled plugins first in Plugin Report?
$ListEnabledPluginsFirst = $true
# Set the following setting to $true to see how long each Plugin takes to run as part of the report
$TimeToRun = $true
# Report on plugins that take longer than the following amount of seconds
$PluginSeconds = 30
# End of Settings

# End of Global Variables

**Comment by Sneddo** [comment]
From looking at the screenshot, this must be evaluating to false `if ($SendEmail -and (!($emptyReport -and !$EmailReportEvenIfEmpty))) {`

Is the report generated in your temp directory? And what version of vCheck are you running?

**Comment by kumarkumar2791** [comment]
I don't see the report generated in my temp directory. I am using the latest version downloaded from below URL.

http://www.virtu-al.net/vcheck-pluginsheaders/vcheck/

**Comment by santoshchowdary07** [comment]
I don't see the report generated in my temp directory. I am using the latest version downloaded from below URL.

http://www.virtu-al.net/vcheck-pluginsheaders/vcheck/

**Comment by santoshchowdary07** [comment]
Hi Sneddo,

Is there any solution for my issue?

**Comment by Sneddo** [comment]
I assume you mean the latest from the master branch?
https://github.com/alanrenouf/vCheck-vSphere/archive/master.zip

I just noticed you seem to be hitting issue #217 as well, which may explain it...

**Comment by AlphaCasper2001** [comment]
There is a wrong parameter in the vCheck.ps1 file.

Beginning on line 809 (I'm using Notepad++ to edit)  change the variable $server to $smtpsrv

$smtpClient.Host = ($SMTPSRV -Split ":")[0]
     if ((**$server** -split ":")[1]) {
            $smtpClient.Port = (**$server **-split ":")[1]
         }

TO

$smtpClient.Host = ($SMTPSRV -Split ":")[0]
     if ((**_$SMTPSRV_** -split ":")[1]) {
            $smtpClient.Port = (**_$SMTPSRV_** -split ":")[1]
         }

**Comment by Sneddo** [comment]
Good catch, fixed in the dev branch

**Comment by mw403git** [comment]
I hit this problem today as well, hopefully it will be fixed soon.

Michael

**Comment by buckmaster60** [comment]
What is the format when your email server requires a password?  I saw in a post username/password but I'm not receiving emails and I applied the change above.
$smtpClient.Host = ($SMTPSRV -Split ":")[0]
if (($SMTPSRV -split ":")[1]) {
$smtpClient.Port = ($SMTPSRV -split ":")[1]
}
Tom

**Comment by buckmaster60** [comment]
email working.  username@domain.com 

is the change above updated as I just downloaded the zip and i had to make the smtpsrv change?
t

**Comment by bareddy8** [comment]
$SMTPSRV did the trick for me, Thanks a ton ..!!

AB
