### ISSUE TITLE
vCheck information

### ISSUE THREAD

**Issue by kumarkumar2791** [alanrenouf/vCheck-vSphere#437]
Hi,

I am planning to run vcheck in our environment but I have below questions can you please help me answer them.

What is the level of access that the script need to run?
will the script impact performance of systems in environment or any other drawbacks using this script?

**Comment by Sneddo** [comment]
vCheck should only require read only access. I just use the default Read Only role in vCenter. 

I have not seen any impact to running vCheck, other than potentially high memory usage on the host running the script.

**Comment by kumarkumar2791** [comment]
Thanks Sneddo.

When I run the script it did not ask me for any credentials. Is there any  way that I can set up script to use a read only user credentials to login to vcenter?

**Comment by Sneddo** [comment]
The most common way is to run the script as a scheduled task, running as a read only user.
