### ISSUE TITLE
 InitializeDefaultDrives operation on the 'FileSystem' provider failed. / Warning  should not use the 'Client' property

### ISSUE THREAD

**Issue by meoso** [alanrenouf/vCheck-vSphere#439]
```
[15:03:07] ..start calculating Clusters Without Host Profile attached by John Sneddon v1.0 [21 of 108]
Attempting to perform the InitializeDefaultDrives operation on the 'FileSystem' provider failed.
WARNING: PowerCLI scripts should not use the 'Client' property. The property will be removed in a future release.
[15:03:11] ..finished calculating Clusters Without Host Profile attached by John Sneddon v1.0 [21 of 108]
```

**Comment by Sneddo** [comment]
What version of vCheck, and PowerCLI are you using?

**Comment by meoso** [comment]
vCheck: 6.22

powershell:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
```

**Comment by Sneddo** [comment]
OK, does it work with just this plugin? I suspect this is just a symptom of the connection failures.

**Comment by meoso** [comment]
it does.  please close.

i may try running the this package from the vCenter server itself, as running from a remote workstation is obviously not working well enough.

**Comment by gulmiguel** [comment]
I'm still getting that message in v 6.51 of PowerCLI.  What's the substitute for 'Client'?  It's been over a year and I still can't find that answer.
