### ISSUE TITLE
TableFormat 03 Datastore Information - Colors not displaying properly

### ISSUE THREAD

**Issue by BKroepfl** [alanrenouf/vCheck-vSphere#445]
We've recently upgraded to the newest release of vCheck from the 6.20 version that we were using previously and noticed that the TableFormat no longer seems to work properly for 'critical' items. Here is the example that I have found: We have a datastore that matches the 'critical' criteria therefore it also matches that 'warning' criteria and it is being colored as a 'warning'. My guess was that once it determined it met the 'warning' criteria it applied those settings and moved on. 

I've tested moving the 'critical' criteria above the 'warning' criteria and running the script again and indeed it does now display the item as red. 

Just wanted to put this out there to see if others were having a similar issue and see if there is an appropriate fix.

**Comment by Sneddo** [comment]
This is an interesting one actually. It turns out that adding a class attribute changes the reference to and XmlElement instead of a string. I'll push an update to the dev branch soon.

**Comment by BKroepfl** [comment]
Upon testing, this fix didnt seem to work in my case. I previously fixed the issue by flipping the critical and warning pieces in the Datastore Information plugin formatting. Would this affect the fix implemented here?

**Comment by Sneddo** [comment]
Yeah, it will apply the rules in order, with the last matching rule being the resukt. So since you flipped them it won't work for you. Flip them back and it should be OK (worked for my testing)
