### ISSUE TITLE
Error message Add-PSSnapin : The Windows PowerShell snap-in 'VMware.VimAutomation.Vds' for vSwitch Security

### ISSUE THREAD

**Issue by nelsonnetto** [alanrenouf/vCheck-vSphere#446]
I am using vSphere PowerCli 6.0 Release 3 and getting the following message:

> [11:45:53] ..start calculating vSwitch Security by Justin Mercier, Sam McGeown,
> John Sneddon v1.2 [62 of 108]
> Add-PSSnapin : The Windows PowerShell snap-in 'VMware.VimAutomation.Vds' is
> not installed on this computer.
> At D:\vcheck-vsphere\Plugins\50 Network\98 vSwitch Security.ps1:24 char:10
> -          Add-PSSnapin VMware.VimAutomation.Vds
> -          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : InvalidArgument: (VMware.VimAutomation.Vds:Strin
>     g) [Add-PSSnapin], PSArgumentException
>   - FullyQualifiedErrorId : AddPSSnapInRead,Microsoft.PowerShell.Commands.Ad
>     dPSSnapinCommand

But the VMware.VimAutomation.Vds is not a Snapin, but a module....
Isn't it a good opportunity to check the code and set Import-Module VMware.VimAutomation.Vds instead?

**Comment by megamorf** [comment]
I guess it's time to implement a Module check and if a VMware module is found use that and use the PSSnapins as fallback if no module can be found.

**Comment by alanrenouf** [comment]
I would recommend just using Add-PSSnapin VMware* as this will add any that exist and if none exist it will not error, this should future proof it as modules should be auto loaded.

**Comment by megamorf** [comment]
Some environment's might've disabled module auto-loading though. I think it's safer to he explicit here.

**Comment by alanrenouf** [comment]
Ok good point, I was just leaving it open as I don't want to break scripts where people use this as a rule with VMware moving from snapins to modules.

**Comment by mw403git** [comment]
I hit this issue today too.  Hope it doesn't actually hurt anything or is it just cosmetic?

Michael

**Comment by danbarr** [comment]
Thinking this could be closed, should have been fixed in PR #431

**Comment by Sneddo** [comment]
Yep, agreed
