### ISSUE TITLE
vCheck report

### ISSUE THREAD

**Issue by jogaurav** [alanrenouf/vCheck-vSphere#447]
I am using vcheck report on VMware appliance and appliance is running on Linux server and server is not on domain. so when I run the vcheck report it ask me for user name and password. when I entered it works well. but issue with scheduled task. In this scenario how can I schedule it schedule task with local user and ID.

**Comment by robertbryanwilliams** [comment]
What user are you running the scheduled task as? (See General Tab of Scheduled Task as shown below)
![image](https://cloud.githubusercontent.com/assets/16541152/15293563/8f5c65aa-1b56-11e6-8baa-7083ac2308c5.png)

My thinking here is that if you are running the scheduled task as a user other than the one where you can run it manually it might not have the proper cached credentials. 

In theory, you should be able to log into the PC with the same user as you run the scheduled task as. Run the script once, and it should prompt for credentials and save them. The scheduled task should then be able to run, pulling the credentials.

Please confirm the particulars and we can better sort out the issue.
