### ISSUE TITLE
Duplicatin vCenter entires

### ISSUE THREAD

**Issue by paadams** [alanrenouf/vCheck-vSphere#449]
I'm running two vCenter servers in linked mode and one vCenter server info is being duplicated in the report?  Has anyone seen this before?

**Comment by Sneddo** [comment]
How are you running vCheck? I believe if you have an open session to both vCenters prior to running vCheck you might get this result...

If you can supply the console output from vCheck and PowerCLI config (`Get-PowerCLIConfiguration | fl`) we might be able to give more insight.

**Comment by paadams** [comment]
I figured this out. I had a previous connection using the unqualified name so it was running against both connections.  I still can't get it to run as a scheduled task though.  Any tips on that?

**Comment by Sneddo** [comment]
What problem are you having? If you have AD authentication setup, it's pretty straight-forward.
