### ISSUE TITLE
PercentFree on Datastore

### ISSUE THREAD

**Issue by vijaychand** [alanrenouf/vCheck-vSphere#451]
Looks like PercentFree value in Datastore Information plugin is being rounded off to 0 decimals.

Example:

Datastore Capacity 2.00 TB
Free Space 304.01 GB
Actual Percent free space (if we round of to 2 decimals) should be 14.84%, but it is not considering it as less than 15%, as I think it is rounding off to 15%.

Can anyone help me on how to get PercentFree round off to 2 decimals please ?

**Comment by Sneddo** [comment]
Modify /Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1, around line 107:
`[math]::Round(((100 * ($ds.FreeSpaceMB)) / ($ds.CapacityMB)),**2**)`
 i.e. change the 0 to a 2

Will merge this change at some point to keep the significant digits consistent.
