### ISSUE TITLE
Error Message - Get-VIEvent : Cannot convert the "VMware.Vim.VirtualMachine" value of type "VMware.Vim.VirtualMachine" to type "VMware.VimAutomation.Sdk.Types.V1.VIObject"

### ISSUE THREAD

**Issue by virtualex-itv** [alanrenouf/vCheck-vSphere#453]
I am using PowerCLI 6.3 R1 (latest release) and am receiving the following error message...

Get-VIEvent : Cannot bind parameter 'Entity'. Cannot convert the "VMware.Vim.VirtualMachine" value of type
"VMware.Vim.VirtualMachine" to type "VMware.VimAutomation.Sdk.Types.V1.VIObject".
At D:\Scripts\vCheck-vSphere-master\Plugins\70 Misc\108 SRM RPO Violations.ps1:45 char:77
- ...    $Events = Get-VIEvent -MaxSamples $MaxSampleVIEvent -Entity $RPOvm
-                                                                    ~~~~~~
  - CategoryInfo          : InvalidArgument: (:) [Get-VIEvent], ParameterBindingException
  - FullyQualifiedErrorId : CannotConvertArgumentNoMessage,VMware.VimAutomation.ViCore.Cmdlets.Commands.GetEvent

![image](https://cloud.githubusercontent.com/assets/12056704/15227202/07fc7906-1854-11e6-916f-b0df9ba7187e.png)

**Comment by lucdekens** [comment]
Engine is using Get-VIEventPlus instead Get-VIEvent.
Should be fixed since then.
Open a new issue when similar problems occur with Get-VIEventPlus
