### ISSUE TITLE
send email problem, email admins say I need to use annoymously

### ISSUE THREAD

**Issue by jrr001** [alanrenouf/vCheck-vSphere#455]
email issue. Been working for years, we had some exchange changes in our environment. All internal. Get error: “client does not have permission to send as this sender”.

our exchange people said:
The error message indicates Send As permissions are required. The best option to get around this is to send the messages anonymously.
#send email from powershell 'anonymous' sender
$anonUsername = "anonymous"
$anonPassword = ConvertTo-SecureString -String "anonymous" -AsPlainText -Force
$anonCredentials = New-Object System.Management.Automation.PSCredential($anonUsername,$anonPassword)

Send-MailMessage -to "user@company.org" -from "vcente@company.org" -subject "test from VCENTERDC sender" -smtpserver smtp.company.org -credential $anonCredentials

Anyone had to work around this issue before or have a solution to this. The reports are generated, just not emailed.

using Powercli 6.3 r1 and current vcheck 6.22

**Comment by Sneddo** [comment]
Related to Issue #144, support for credentials would be a nice feature to have.

There's currently no native way to do this with vCheck, however you can just modify vCheck.ps1 and replace `$smtpClient.UseDefaultCredentials = $true;`  with `$smtpClient.Credentials = New-Object System.Management.Automation.PSCredential("anonymous", (ConvertTo-SecureString -String "anonymous" -AsPlainText -Force))`
