### ISSUE TITLE
Plugins with 1 Column of results, or 1 Result not displaying properly

### ISSUE THREAD

**Issue by BKroepfl** [alanrenouf/vCheck-vSphere#456]
1. If your [count] is less than 2, it does not work correctly. I have a plugin with only 1 result and the [count] is blank.
2. If your results table only contains 1 column, it strips the column name and replaces it with an asterisk (*)

**Comment by Sneddo** [comment]
Fixed in dev branch

**Comment by BKroepfl** [comment]
That was quick, thank you! However, one issue to note, if the results are returned in List format, the asterisk still remains.

**Comment by Sneddo** [comment]
Will fix this tomorrow, should be the same code anyway.
