### ISSUE TITLE
$EmailTo / $EmailCC

### ISSUE THREAD

**Issue by Loyail1** [alanrenouf/vCheck-vSphere#464]
I am looking adding the variable for either -Emailto or -EmailCC while kicking off vcheck.ps1 from another program. I have  tested listing the parameter to the top of vcheck.ps1 and/or globalvariables.ps1. In either place powershell will not accept the provided variable stating "parameter cannot be found that matches parameter name" What am I missing?

**Comment by Sneddo** [comment]
You would need to change to a different variable name I think. Adding EmailTo or EmailCC to params would get clobbered when the globalVariables get imported.
