### ISSUE TITLE
enhancement: passing server in cli

### ISSUE THREAD

**Issue by rockaut** [alanrenouf/vCheck-vSphere#466]
We have multiple vcsa running. i haven't found a way to pass the server so i only could automate one.

is there a way to pass the server manually each time?

**Comment by Sneddo** [comment]
The closest thing would be to use a [job file](https://github.com/alanrenouf/vCheck-vSphere/wiki/Job-XML-Specification) to specify a different globalVariables.ps1

**Comment by rockaut** [comment]
well i tried that already. but how do i have to set the variable in the global variables file?

$Server haven't worked.

**Comment by Sneddo** [comment]
Yeah, you would need to have a separate file per server, even if you just set $Server and dot source a files with the rest of the configuration.

**Comment by danimalrowe** [comment]
Would people be interested in having the server passed in on the command line?  What I have done is moved $Server out of the Connection Plugin and placed it in the param of vCheck.ps1 and setting a default value for the server.  This will work for users that only have one server so nothing would change on how they run vCheck.  But allows users with multiple servers to pass in on the command line a server to override the default.

Example
     vCheck.ps1 -Server vcServer02

param (
	[Switch]$config,

	[ValidateScript({ Test-Path $_ -PathType 'Container' })]
	[string]$Outputpath=$Env:TEMP,

	[ValidateScript({ Test-Path $_ -PathType 'Leaf' })]
	[string]$job,

    [string]$Server = "vcServer01"
)

**Comment by danimalrowe** [comment]
Would people be interested in having the server passed in on the command line? What I have done is moved $Server out of the Connection Plugin and placed it in the param of vCheck.ps1 and setting a default value for the server. This will work for users that only have one server so nothing would change on how they run vCheck. But allows users with multiple servers to pass in on the command line a server to override the default.

Example
 vCheck.ps1 -Server vcServer02

param (
    [Switch]$config,

    [ValidateScript({ Test-Path $_ -PathType 'Container' })]
    [string]$Outputpath=$Env:TEMP,

    [ValidateScript({ Test-Path $_ -PathType 'Leaf' })]
    [string]$job,

    [string]$Server = "vcServer01"

)

**Comment by cgreggo** [comment]
I think others would benefit. That approach has worked well for my environment. I run vCheck against four different vCenter servers (all on different scheduled tasks). Passing the vCenter server name as a parameter allows me to avoid duplicating the folder structure for each vCenter's vCheck report.

**Comment by danimalrowe** [comment]
Added the code for command line parameters Server and DataCenter to DEV.  See Pull Request #489

**Comment by Sneddo** [comment]
This goes against vCheck as a reporting framework. Using job files achieves the same functionality, and changes to the settings handling will make it even easier again.
