### ISSUE TITLE
I am want to pull information of all VM in which VMtool is not upto date.

### ISSUE THREAD

**Issue by gautamparkash** [alanrenouf/vCheck-vSphere#470]
but through vcheck script, it give output of only 30 VM. i changed the value in 114 VM Tools Not Up to Date. but not working

**Comment by Sneddo** [comment]
Works for me, what exactly isn't working for you? 

The plugin code is a bit redundant, but the logic is sound.

**Comment by gautamparkash** [comment]
I setup vcheck again now i am able to pull required information.
