### ISSUE TITLE
Scripts according VM CPU/Memory Hot-Plug Features

### ISSUE THREAD

**Issue by rebneth** [alanrenouf/vCheck-vSphere#473]
Hello,
the vCheck framework is an awesome tool to those who do not have vCOps or just get an overview about the things that do not comply 'standards or recommendations'. Sometimes it is executed by people, who do not really dive-in deep in the scripts and in environments with hundreds or thousands of VMs...

According KB 2040375, I think CPU/Memory Hot-Plug should ony be enabled, if You really need it.
https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2040375

By default CPU Hot-Plug and Memory Hot-Add are disabled. If CPU Hot-Plug is enabled, vNUMA is disabled, which might have other impacts.
Therefore I think vCheck reports should only list those VMs, that have either CPU Hot Plug or Memory Hot Add enabled. 

Right now, there are 2 scripts that address this. Maybe it is the best to provide only 1 script like mine
(I list only VMs that do not have either CPU nor Memory Hot Add enabled) - You can improve this by defining the desired CPU/Hot Plug state ($true / $false)

[103 VMs with CPU and or Memory Hot Add Configuration.txt](https://github.com/alanrenouf/vCheck-vSphere/files/408862/103.VMs.with.CPU.and.or.Memory.Hot.Add.Configuration.txt)

**Comment by Sneddo** [comment]
Good suggestion - and good pickup on the duplicate plugins.

Will try to push a commit this week.

**Comment by Sneddo** [comment]
Removed duplicate plugin and updated 201 to allow defining what value you want each setting.
