### ISSUE TITLE
79 Find VMs in Uncontrolled Snapshot Mode.ps1

### ISSUE THREAD

**Issue by rogersa2k** [alanrenouf/vCheck-vSphere#478]
I just upgraded to 6.23 and when I run it I get the following:

```
[09:44:03] ..start calculating VMs in uncontrolled snapshot mode by Rick Glover, Matthias Koehler, Dan Rowe v1.4 [73 of 84]
Method invocation failed because [System.Management.Automation.PSObject] doesnot contain a method named 'op_Addition'.
At C:\Scripts\vCheck6\vcenter901\Plugins\60 VM\79 Find VMs in Uncontrolled
Snapshot Mode.ps1:9 char:5
+     $fileList += Get-ChildItem -Path "$FilePath" | Select Name, FolderPath,
Full ...
+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

**Comment by rogersa2k** [comment]
Hmm, I can't seem to figure out how to paste the entire error properly but I think you get the point.

**Comment by danimalrowe** [comment]
Hi rogersa2k,

I think the issue is that the statement prior is not finding any data so $fileList is not defined.  Try this

Replace line 9 with the following

if ( $fileList -ne $null ) {
    $fileList += Get-ChildItem -Path "$FilePath" | Select Name, FolderPath, FullName
} else {
    $fileList = Get-ChildItem -Path "$FilePath" | Select Name, FolderPath, FullName
}

Hopefully this will fix the issue.

**Comment by Sneddo** [comment]
Yep, I think danimalrowe is right on this one.

We can just cast $filelist as an array as well, which should fix it without additional lines of code.

**Comment by Sneddo** [comment]
Just puushed an update to the dev branch which seems to fix this for me. Let me know if you still have issues.
