### ISSUE TITLE
The '31 NTP Name and Service.ps1' script delivers wrong results if more that one NTP server was specified.

### ISSUE THREAD

**Issue by MWalterDE** [alanrenouf/vCheck-vSphere#486]
Once more that one NTP has been specified in the ESXi host configuration, the '31 NTP Name and Service.ps1' script seems to have a problem with the multiline response of the Get-VMHostNtpServer CMDlet and delivers a warning in the report.

**Comment by Sneddo** [comment]
Just pushed an update which should fix this, please test.

**Comment by MWalterDE** [comment]
Seems to work, no warning is reported until I change the settings to something wrong on one of our hosts...
