### ISSUE TITLE
Storing configuration in version control

### ISSUE THREAD

**Issue by rnelson0** [alanrenouf/vCheck-vSphere#490]
Question: How should I store my configuration in version control? The settings are part of the plugin files, which I believe means that I would need to store the data in my own fork. In the short term, this would suffice, but long term could cause conflicts and issues with updates to vCheck. Is there a method to store the config separately that I am missing? If not, are there any efforts underway to enable that? Thank you!

**Comment by Sneddo** [comment]
This is something that has been discussed previously (#361), to pull the settings out of the plugin files into another data source. It really just needs someone with time to dedicate to the effort.

In the meantime, I guess you could use the Export-vCheckSettings functions in the vCheckUtils.ps1 to export to csv, and check that into your version control.

**Comment by rnelson0** [comment]
Thanks @Sneddo, that works great and I'm not sure how I missed it in the docs!
