### ISSUE TITLE
Plugin Multi-Writer destroys $VM

### ISSUE THREAD

**Issue by liverpool139** [alanrenouf/vCheck-vSphere#493]
Hi there,
I've written my own PlugIns for vCheck - and I was wondering why my PlugIn doesn't work when I work with the $VM Variable which is set in the '00 Connection Plugin for vCenter.ps1'.
So I troubleshooted my Issue and found the '120 Multi-writer.ps1' in the '60 VM' Plugin. I don't know why, but when I run this Multi-Write Script, the $VM isn't the same as before running the script.
Can anybody check this Problem?
Thanks
Christoph

**Comment by Sneddo** [comment]
Good catch, just pushed a fix to the dev branch.
