### ISSUE TITLE
Plugin 'General Information' Order of Items

### ISSUE THREAD

**Issue by liverpool139** [alanrenouf/vCheck-vSphere#494]
The PSObject which is genereated in 'General Information' is not ordered (alphabetical or in the order which the hashtable is created):

$Info = New-Object -TypeName PSObject -Property @{
    "Number of Hosts" = (@($VMH).Count)
    "Number of VMs" = (@($VM).Count)
    ...
}

You can order like it is defined in the PSObject with following command:

$Info = New-Object -TypeName PSObject -Property **([ordered]**@{
    "Number of Hosts" = (@($VMH).Count)
    "Number of VMs" = (@($VM).Count)
    ...

}**)**
Notice the ) at the end!

So I think is Issue is closes - maybe there are other ways to order in PSObjects!?!

**Comment by Sneddo** [comment]
Yeah, assuming everyone is using Powershell 3 or above this would work. Otherwise a Select with the columns in order would also work.

I'd actually be interested in adding some basic anonymous stats to vCheck to see what versions of Powershell/PowerCLI are in use, and which plugins are most used...
