### ISSUE TITLE
Duplicate results

### ISSUE THREAD

**Issue by xavtrix** [alanrenouf/vCheck-vSphere#495]
Getting duplicate results for lots of different plugins.  For example, results for the General Information plugin displays double the number of hosts, templates, VMs, Clusters, etc, in my environment.  Have a pretty simple environment: one vCenter, 21 hosts, about 200 VMs.  Not sure how to go about troubleshooting this.  I've Googled the issue and browed the Issues section in this GitHub - others have experienced the issue from what I have read but haven't seen a solution.  Any ideas?  Many thanks,

**Comment by rkleijwegt** [comment]
Bvv

Op 22 sep. 2016 7:30 p.m. schreef "xavtrix" <notifications@github.com>:

**Comment by xavtrix** [comment]
Bvv?

**Comment by xavtrix** [comment]
Finally, figured this one out..  In PowerCLI session, I was connecting to my vCenter with Connect-VIServer command as I usually do when using PowerCLI, then running vcheck.ps1 script.  For some reason, this caused duplicate results.  If I open a PowerCLI session and just run the vcheck.ps1 script, works fine.  Odd issue!  Just glad it's working now. =)
