### ISSUE TITLE
no results in: $Display = "Graph"

### ISSUE THREAD

**Issue by amaralma** [alanrenouf/vCheck-vSphere#500]
I'm trying to use but it not returns the graph even if with an simple example like below.
Can some one help me please.

```
# Start of Settings 
# End of Settings 

$Ressult = @()
$data = @{"Windows"=654;"Other"=140}
$Ressult += New-Chart -data $data -ChartType Bar -Title "VMs by OS"

$Ressult

$Title = "New Chart Example"
$Header = "Warning New Chart Example"
$Comments = "The following warnings were New Chart Example"
$Display = "Graph"
$Author = "Chart Example"
$PluginVersion = 1.0
$PluginCategory = "vSphere"
```

**Comment by Sneddo** [comment]
You don't need to call New-Chart, just return an array of values and vCheck does the formatting, same as any plugin.

**Comment by amaralma** [comment]
By the way: It's not working yet...
Can some one show me an example of plug-in and the result with the chart please ?!

**Comment by Sneddo** [comment]
Yep, my mistake- it's been so long since I've looked at the Chart output type! You do need to call New-Chart in the plugin.

The only problem with your example is that $Display should be "Chart", not "Graph". Just tested it on vCheck 6.23 and works for me.

**Comment by amaralma** [comment]
Once more, thanks for answer!
It solved when I sent Hashtable instead of Object to New-Chart function...
