### ISSUE TITLE
General informations missing

### ISSUE THREAD

**Issue by jojo1303** [alanrenouf/vCheck-vSphere#503]
Hello,

I used  an old version of vcheck (vcheck 5) for a long time. This old release gave me the following information into the general informations item of vcheck report

Total Number of vCPU allocated on VM
Total Number of memory allocated on VM

I don't see these informations into the vcheck 6 report.

How can I do this please ?

Thanks 
Rgds

**Comment by Sneddo** [comment]
I guess you could either add a [new plugin](https://github.com/alanrenouf/vCheck-vSphere/wiki/Plugin-structure) or update the General Information plugin to add this information.

CPU count: ($vm | Measure-Object -sum NumCPU).sum
Memory allocated: ($vm | Measure-Object -sum MemoryGB).sum

**Comment by jojo1303** [comment]
Hello,  thanks great.I have added this information into the General information plugins,it working.
Now,I want to Know if it possible to have the same  informations for each clusters into vcenter . 
Is it possible to integrate nbr of CPU and MEM for each clusters into the général informations plugins?
Thanks for your help

**Comment by Sneddo** [comment]
Probably best to create a new plugin for this

      $Title = "Cluster CPU/Memory Allocations"
      $Header =  "Cluster CPU/Memory Allocations"
      $Comments = ""
      $Display = "Table"
      $Author = "John Sneddon"
      $PluginVersion = 1.0
      $PluginCategory = "vSphere"

      # Start of Settings   
      # End of Settings

      foreach ($cluster in $clusters)
      {
         $cluster | select Name, @{Name="Total Number of vCPU allocated on VM";e={($vm | Where {$cluster.ExtensionData.Host -contains $_.VMHostID } | Measure-Object -sum NumCPU).Sum}}, @{Name="Total Number of memory allocated on VM";e={($vm | Where {$cluster.ExtensionData.Host -contains $_.VMHostID } | Measure-Object -sum MemoryGB).Sum}}
      }

**Comment by jojo1303** [comment]
Thanks for your help.It works

**Comment by jojo1303** [comment]
Thanks
