### ISSUE TITLE
vcheck false positive results ? NTP issues, syslog issues.... 

### ISSUE THREAD

**Issue by maZuFC** [alanrenouf/vCheck-vSphere#505]
hi

im going through the vcheck reports and im curious as to why the report says that we have issues with our NTP and syslog settings..

NTP is setup correctly with the right NTP server and the syslog is setup with a scratch partition.

**NTP**, looking at the NTP issues section you can see the following

Name - host name 
NTPServer - NTP IPs
ServiceRunning - TRUE on all hosts

i can confirm that the NTP IPs are pingable from the hosts.

**Syslog**, looking at the syslog issue section in the HTML output.

Name column - i can see the host names.
SyslogServer column - blank
SyslogSetting column - only 2 hosts show /scratch/log 

checking the other hosts scratch partition is set correctly but not displaying in the vcheck report.

is there something missing/incorrectly configured or is vcheck reporting a false positive?

let me know if you need any more info....

many thanks

M.

**Comment by Sneddo** [comment]
What version of vCheck, and plugins?

Do you have multiple NTP servers or anything unusual? It would be useful to know your plugin settings for each.

**Comment by maZuFC** [comment]
vCheck v6.23 

no multiple NTPs and nothing unusual that i can think of.

most plugin settings are default.
the only ones that have been edited are the ones like report name, SMTP settings and email settings.

apart from that... when i was setting it up i was just pressing enter to select default.

**Comment by Sneddo** [comment]
OK, let's just run the logic of the plugin manually and see what value it is returning. Hopefully we can see why it isn't matching the $ntpserver setting...

`GetVMHost | Where {$_.Connectionstate -ne "Disconnected"} | Select Name, @{N="NTPServer";E={($_ | Get-VMHostNtpServer) -join ","}}, @{N="ServiceRunning";E={(Get-VmHostService -VMHost $_ | Where-Object {$_.key -eq "ntpd"}).Running}}`

**Comment by maZuFC** [comment]
ok so for NTP it comes back with the following

Name: i can see the host names
NTPServer: i can see the correct NTP ips
ServiceRunning: all are TRUE

for Syslog

Name: i can see the host names
Syslog: every entry is blank
SyslogSetting: only 2 hosts show /scratch/log, every other host is blank.

**Comment by Scepticalist** [comment]
The logic for Syslog isn't great.

The "Syslog" setting is for a remote server and would have a udp or tcp url for a Syslog server. SyslogSetting is for the local datastore location of the log, which would be irrelevant if you had a Syslog server.
I'm going to work on an amendment so that it tests for those conditions before reporting.

**Comment by maZuFC** [comment]
thanks for updating this thread...

i look forward to your update

**Comment by Scepticalist** [comment]
Thsi is actually dealt with in Issue 472 - the fix is posted there

**Comment by lucdekens** [comment]
Merge with #472
