### ISSUE TITLE
Request to report VMs powered off in the last day

### ISSUE THREAD

**Issue by cwiley2566** [alanrenouf/vCheck-vSphere#511]
Can script 60 Powered Off VMs.ps1  be edited to display VMs that had been powered off in the last day?

**Comment by Sneddo** [comment]
Yep, just add a where clause to it.

Something like this should work (but haven't tested)

      # Start of Settings 
      # VMs not to report on
      $IgnoredVMs = "Windows7*"
      # End of Settings

      $VM | Where-Object {$_.ExtensionData.Config.ManagedBy.ExtensionKey -ne 'com.vmware.vcDr' -and 
                          $_.PowerState -eq "PoweredOff" -and 
                          $_.Name -notmatch $IgnoredVMs -and 
                          $_.LastPoweredOffDate -gt (Get-Date_.AddDays(-1)} |
        Select-Object -Property Name, LastPoweredOffDate, Folder, Notes |
        Sort-Object -Property LastPoweredOffDate)

      $Title = "Powered Off VMs"
      $Header = "VMs Powered Off - Number of Days"
      $Comments = "May want to consider deleting VMs that have been powered off for more than 30 days"
      $Display = "Table"
      $Author = "Adam Schwartzberg"
      $PluginVersion = 1.3
      $PluginCategory = "vSphere"

**Comment by cwiley2566** [comment]
I am having trouble getting this to work. I think its the lastpoweredoffdate. Is that coming from this in connection:
function Get-VMLastPoweredOffDate {
  param([Parameter(Mandatory=$true,ValueFromPipeline=$true)]
        [VMware.VimAutomation.ViCore.Impl.V1.Inventory.VirtualMachineImpl] $vm)
  process {
    $Report = "" | Select-Object -Property Name,LastPoweredOffDate
     $Report.Name = $_.Name
    $Report.LastPoweredOffDate = (Get-VIEventPlus -Entity $vm | `
      Where-Object { $_.Gettype().Name -eq "VmPoweredOffEvent" } | `
       Select-Object -First 1).CreatedTime
     $Report
  }
}

Because when the report ran before the add on that last powered off column is blank. So I would think it wont work because the lastpoweredoffdate is not working. 
![capture](https://cloud.githubusercontent.com/assets/22579161/20716446/41f44a48-b620-11e6-8350-9f9d4110368f.JPG)

**Comment by Sneddo** [comment]
Yep, I think you're right. 

What version of Powershell, PowerCLI, and vCheck are you running? 
What do you have your event retention set to on vCenter?
Do you see the power off events in your vSphere client for the VMs?

**Comment by cwiley2566** [comment]
Powershell = 4.0 
VMware vSphere PowerCLI 6.3 Release 1 build 3737840
vCheck = 6.23
vCenter Retention = 100 days
Do you see the power off events in your vSphere client for the VMs? I think so.. see picture
![capture](https://cloud.githubusercontent.com/assets/22579161/20728489/02c97204-b64c-11e6-86e7-fc7685b62a36.JPG)

**Comment by Sneddo** [comment]
hrrmmmm that's really weird...

Guess we need to check if the right events are being pulled back:
      function Get-VIEventPlus {
          
         param(
            [VMware.VimAutomation.ViCore.Impl.V1.Inventory.InventoryItemImpl[]]$Entity,
            [string[]]$EventType,
            [DateTime]$Start,
            [DateTime]$Finish = (Get-Date),
            [switch]$Recurse,
            [string[]]$User,
            [Switch]$System,
            [string]$ScheduledTask,
            [switch]$FullMessage = $false,
            [switch]$UseUTC = $false
         )

         process {
            $eventnumber = 100
            $events = @()
            $eventMgr = Get-View EventManager
            $eventFilter = New-Object VMware.Vim.EventFilterSpec
            $eventFilter.disableFullMessage = ! $FullMessage
            $eventFilter.entity = New-Object VMware.Vim.EventFilterSpecByEntity
            $eventFilter.entity.recursion = &{if($Recurse){"all"}else{"self"}}
            $eventFilter.eventTypeId = $EventType
            if($Start -or $Finish){
               $eventFilter.time = New-Object VMware.Vim.EventFilterSpecByTime
               if($Start){
                  $eventFilter.time.beginTime = $Start
               }
               if($Finish){
                  $eventFilter.time.endTime = $Finish
               }
            }
            if($User -or $System){
               $eventFilter.UserName = New-Object VMware.Vim.EventFilterSpecByUsername
               if($User){
                  $eventFilter.UserName.userList = $User
               }
               if($System){
                  $eventFilter.UserName.systemUser = $System
               }
            }
            if($ScheduledTask){
               $si = Get-View ServiceInstance
               $schTskMgr = Get-View $si.Content.ScheduledTaskManager
               $eventFilter.ScheduledTask = Get-View $schTskMgr.ScheduledTask |
               where {$_.Info.Name -match $ScheduledTask} |
               Select -First 1 |
               Select -ExpandProperty MoRef
            }
            if(!$Entity){
               $Entity = @(Get-Folder -NoRecursion)
            }
            $entity | %{
               $eventFilter.entity.entity = $_.ExtensionData.MoRef
               $eventCollector = Get-View ($eventMgr.CreateCollectorForEvents($eventFilter))
               $eventsBuffer = $eventCollector.ReadNextEvents($eventnumber)
               while($eventsBuffer){
                  $events += $eventsBuffer
                  $eventsBuffer = $eventCollector.ReadNextEvents($eventnumber)
               }
               $eventCollector.DestroyCollector()
            }
            if (-not $UseUTC)
            {
               $events | % { $_.createdTime = $_.createdTime.ToLocalTime() }
            }
            
            $events
         }
      }    

    $vm = Get-VM <<vmname>>
    Get-VIEventPlus -Entity $vm | Where-Object { $_.Gettype().Name -eq "VmPoweredOffEvent" }`

**Comment by cwiley2566** [comment]
I am getting: 
$vm = Get-VM "replaced with vm name"
Get-VIEventPlus -Entity $vm | Where-Object { $_.Gettype().Name -eq "VmPoweredOffEvent" }`
Incomplete string token.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : IncompleteString

**Comment by Sneddo** [comment]
Oops, looks like I have a stray backtick at the end there!

Get-VIEventPlus -Entity $vm | Where-Object { $_.Gettype().Name -eq "VmPoweredOffEvent" }

**Comment by cwiley2566** [comment]
Ok finally got time to get back to this. I think this means the events are coming back: 
![capture](https://cloud.githubusercontent.com/assets/22579161/21012200/e383729a-bd22-11e6-8719-4ee39b298d71.JPG)

**Comment by Sneddo** [comment]
hmmm so it seems like New-VIProperty isn't working properly in PowerCLI 6.3. I don't seem to get those properties populated on 6.3, but works on previous version.

Will need to look at this a bit more.

**Comment by cwiley2566** [comment]
Ok thanks very much!!

**Comment by Scepticalist** [comment]
Latest PowerCLI has changed the property. To get this plugin working again edit the plugin "00 Connection Plugin for vCenter" as follows:

In the two function definitions Get-VMLastPoweredOffDate and Get-VMLastPoweredOnDate:

Replace 

VMware.VimAutomation.ViCore.Impl.V1.Inventory.VirtualMachineImpl

With 

VMware.VimAutomation.ViCore.Impl.V1.VM.UniversalVirtualMachineImpl

**Comment by Sneddo** [comment]
Fixed with Pull #528. Discussed in issue #526

**Comment by mehdife** [comment]
Hello, 
I write on post because i had the same issue but i resolved in party with informations above. 
in my case i can see the date of  "LastPoweredOffDate " only on the vm wich are in root folder. i can't see vm' poweredOffDate in sub folders.

has anyone ever met this case?

Thank you very much.
