### ISSUE TITLE
VMware PowerCLI 6.5 Compatibility

### ISSUE THREAD

**Issue by MallocArray** [alanrenouf/vCheck-vSphere#514]
The vSwitch Security plugin does not detect PowerCLI correctly and reports:

 ..start calculating vSwitch Security by Justin Mercier, Sam McGeown, John Sneddon v1.2 [58 of 92]
WARNING: PowerCLi version installed is lower than 5.1 Release 2

The version I have installed is: "VMware PowerCLI 6.5 Release 1 build 4624819" which doesn't match the version check of this plugin:
if (((Get-PowerCLIVersion) -match "VMware vSphere PowerCLI (.*) build ([0-9]+)"))

I'm going to change this line to eliminate vSphere from the string to match and I believe it will be ok.

**Comment by Sneddo** [comment]
Fixed in dev branch.
https://raw.githubusercontent.com/alanrenouf/vCheck-vSphere/dev/Plugins/50%20Network/98%20vSwitch%20Security.ps1
