### ISSUE TITLE
vCheck is dropping first column of data in HTML output for a custom plugin

### ISSUE THREAD

**Issue by Hammer7407** [alanrenouf/vCheck-vSphere#515]
A custom plugin that I'm working on drops the data from the first column when it outputs to the HTML report. If I run the same commands in a PS window the data shows up correctly.

I am running version 6.23 of vCheck. The code looks like this.

      $AllESXHosts = Get-VMHost | Where { ($_.ConnectionState -eq "Connected") -or ($_.ConnectionState -eq "Maintenance")} | Sort Name

      $Result = @(Foreach ($esxhost in $AllESXHosts) {Get-VMhost $esxhost | Get-ScsiLun -LunType disk | Select VMHost,CanonicalName,MultipathPolicy | Where {$_.MultipathPolicy -notlike "RoundRobin"} | Where {$_.CanonicalName -like "naa.6000*"}} | Sort-Object -Property VMHost,CanonicalName)
      $Result

      $Title = "VM Hosts with Path Selection Policy - Set to Fixed"
      $Header =  "VM Hosts with Path Selection Policy - NOT set to Round Robin (VMware)"
      $Comments = "The following ESXi Hosts do not have the correct PSP. It is strongly suggested you check these hosts."
      $Display = "Table"
      $Author = "Jason"
      $PluginVersion = 1.0
      $PluginCategory = "vSphere"

Output in the HTML:
      VMHost	CanonicalName	MultipathPolicy
      naa.6000d310006d12000000000000006005	MostRecentlyUsed
      naa.6000d310006d12000000000000006005	MostRecentlyUsed
      naa.6000d310006d12000000000000006005	MostRecentlyUsed
      naa.6000d310006d12000000000000006005	MostRecentlyUsed
      naa.6000d310006d12000000000000006005	MostRecentlyUsed
      naa.6000d310006d12000000000000006005	MostRecentlyUsed
      naa.6000d310006d12000000000000006005	MostRecentlyUsed
      naa.6000d310006d12000000000000006005	MostRecentlyUsed
      naa.6000d310006d12000000000000000009	MostRecentlyUsed
      naa.6000d310006d12000000000000006005	MostRecentlyUsed
      naa.6000d310006d12000000000000006005	MostRecentlyUsed
      naa.6000d310006d12000000000000006005	MostRecentlyUsed

Output in the PS window:
      VMHost                CanonicalName                         MultipathPolicy
      ------                -------------                         ---------------
      denvmp35.test.com naa.6000d310006d12000000000000006005 MostRecentlyUsed
      denvmp37.test.com naa.6000d310006d12000000000000006005 MostRecentlyUsed
      denvmp38.test.com naa.6000d310006d12000000000000006005 MostRecentlyUsed
      denvmp42.test.com naa.6000d310006d12000000000000006005 MostRecentlyUsed
      denvmp43.test.com naa.6000d310006d12000000000000006005 MostRecentlyUsed
      denvmp44.test.com naa.6000d310006d12000000000000006005 MostRecentlyUsed
      denvmp45.test.com naa.6000d310006d12000000000000006005 MostRecentlyUsed
      denvmp46.test.com naa.6000d310006d12000000000000000009 MostRecentlyUsed
      denvmp46.test.com naa.6000d310006d12000000000000006005 MostRecentlyUsed
      denvmp47.test.com naa.6000d310006d12000000000000006005 MostRecentlyUsed
      denvmp48.test.com naa.6000d310006d12000000000000006005 MostRecentlyUsed
      denvmp49.test.com naa.6000d310006d12000000000000006005 MostRecentlyUsed

**Comment by Sneddo** [comment]
Assuming you're including the Connection plugin as well, I modified your plugin a bit:

      $VMH | Where { ($_.ConnectionState -eq "Connected") -or ($_.ConnectionState -eq "Maintenance")} | Get-ScsiLun -LunType disk | Select VMHost,CanonicalName,MultipathPolicy | Where {$_.MultipathPolicy -notlike "RoundRobin" -and $_.CanonicalName -like "naa.6000*"} | Sort-Object -Property VMHost,CanonicalName

      $Title = "VM Hosts with Path Selection Policy - Set to Fixed"
      $Header = "VM Hosts with Path Selection Policy - NOT set to Round Robin (VMware)"
      $Comments = "The following ESXi Hosts do not have the correct PSP. It is strongly suggested you check these hosts."
      $Display = "Table"
      $Author = "Jason"
      $PluginVersion = 1.0
      $PluginCategory = "vSphere"

This Tests OK on PowerCLI 6.3 R1, Powershell 5.0, and vCheck 6.23

Otherwise, you could just replace $VMH with Get-VMHost

**Comment by Hammer7407** [comment]
That worked perfectly, thank you.
