### ISSUE TITLE
Erron in Uncontrolled Snapshot Mode

### ISSUE THREAD

**Issue by rajeshr9888** [alanrenouf/vCheck-vSphere#522]
AM Getting Below Error , please help 

Get-ChildItem : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS 
secure channel.
At C:\Scripts\vCheck-vSphere-master\Plugins\60 VM\79 Find VMs in Uncontrolled Snapshot Mode.ps1:7 char:17
+     $fileList = Get-ChildItem -Path "$FilePath" | Select Name, FolderPath, FullN ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ChildItem], ViError
    + FullyQualifiedErrorId : VMware.VimAutomation.Sdk.Types.V1.ErrorHandling.VimException.ViError,Microsoft.Power 
   Shell.Commands.GetChildItemCommand

**Comment by Sneddo** [comment]
Discussed in issue #217 - may be some useful things to try in there.
