### ISSUE TITLE
Getting errors using PowerCLI 5.1 R1 

### ISSUE THREAD

**Issue by jbh1** [alanrenouf/vCheck-vSphere#524]
I have put everything in place for the script to run but when I run.\vcheck.ps1 -config I get Property 'PositionalBinding' cannot be found for type 'System.Management.Automa
tion.CmdletBindingAttribute'.
At C:\vCheck\Vcheck\vCheck.ps1:162 char:16
+     [CmdletBinding <<<< (PositionalBinding = $true)]
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

I get this for every line in the script. What am I missing? I had this working for VCenter 5 but when we upgraded to version 6 it stopped working. I am trying to create a whole new setup on a new system.

**Comment by Sneddo** [comment]
What version of Powershell and vCheck are you running (dev or master branch?)

Any reason you're not using the latest PowerCLI? There are some dramatic improvements in 6.3...

**Comment by alanrenouf** [comment]
recommend updating to the latest version of PowerCLI

**Comment by wramby** [comment]
I am having this issue as well.
PowerShell 2
PowerCLI 5.1

**Comment by Sneddo** [comment]
Upgrade PowerCLI and Powershell (V3 will be the minimum required for newer versions of vCheck)
