### ISSUE TITLE
email through Office 365 relay

### ISSUE THREAD

**Issue by JmillerCT** [alanrenouf/vCheck-vSphere#529]
Alan,
Excellent job with this script, it is really helpful.  I have a client who is on office 365 and they gave me a username/password/port to send to and I am not great at coding so I don't know the easiest way to implement this into the script.  I created a test powershell script to test mail functionality and it works using an encrypted password file (http://o365info.com/send-e-mail-office-365-using-powershell-script-saved-encrypted-password-part-2-of-2/) , but just not sure how to best implement it into vCheck.  Can you please assist?
smtp.office365.com
port 587
TLS enabled
https://support.office.com/en-us/article/How-to-set-up-a-multifunction-device-or-application-to-send-email-using-Office-365-69f58e99-c550-4274-ad18-c805d654b4c4

**Comment by Sneddo** [comment]
At the moment there's not a _simple_ way to do this, but it's not too hard.

Set `$SMTPSRV = "smtp.office365.com"` in GlobalVariables.ps1, then edit vcheck.ps1 to:
- Remove the line: `$smtpClient = New-Object System.Net.Mail.SmtpClient`
- Add a line to set $smtpClient.Credentials to your credential object containing the username/password you have been provided

Issue #144 is still open to eventually add this feature, I just don't have time to really do much on vCheck lately...

**Comment by JmillerCT** [comment]
Alan,
Sorry maybe I am just not good enough at coding but I keep getting an error
that I am not authenticated to send the email.  I hate to ask but can you
paste exactly what I should paste into the code of the vheck.ps1 at the
bottom because I tried several things and it just doesn't seem like it is
passing the user/pass along.


Thanks,

Jeff
917-270-4097

**Comment by JmillerCT** [comment]
I figured it out, here is what the code looks like now, probably not the
cleanest way but it worked

# Send the email
$smtpPort = "587"
$smtpServer = "smtp.office365.com"
$smtpUser = "Put.Your.o365.SMTP.username.Here"
$smtpPass = "Put.Your.o365.SMTP.password.Here"

$smtpClient = New-Object System.Net.Mail.SmtpClient($smtpServer,$smtpPort)
$smtpClient.EnableSsl = $true
$smtpClient.Credentials = New-Object
System.Net.NetworkCredential($smtpUser,$smtpPass)
# Find the VI Server and port from the global settings file
# $smtpClient.Host = ($SMTPSRV -Split ":")[0]
# if (($SMTPSRV -split ":")[1]) {
# $smtpClient.Port = ($SMTPSRV -split ":")[1]
# }


# if ($EmailSSL -eq $true) {
# $smtpClient.EnableSsl = $true
}
# $smtpClient.UseDefaultCredentials = $true;
$smtpClient.Send($msg)
If ($SendAttachment) { $attachment.Dispose() }
$msg.Dispose()
#}

# Run EndScript once everything else is complete
if (Test-Path ($ScriptPath + "\EndScript.ps1")) {
. ($ScriptPath + "\EndScript.ps1")
}

#endregion output


Thanks,

Jeff
917-270-4097
