### ISSUE TITLE
Email to

### ISSUE THREAD

**Issue by samuk912** [alanrenouf/vCheck-vSphere#540]
Hi All

ive been trying to setup emailing the report to multiple email addresses and its not working for me.
below user01@example.com and user02@example.com are example email addresses im using live email accounts in my testing
ive tried $EmailTo ="user01@example.com,user02@example.com" only sent to the 1st address
ive removed the 1st address so it only sends to the 2nd address that works.
ive changed the order of the 1st and 2nd address $EmailTo ="user02@example.com,user01@example.com"  only sends to user02.
i tried the , to ; doesnt send to any address.
im not sure what else i can test to try and get it to send to both addresses

**Comment by gregharms** [comment]
$EmailTo ="user01@example.com","user02@example.com"

PowerShell's Send-MailMessage expects an array of email addresses, not a string containing multiple addresses.
