### ISSUE TITLE
23 VI Events.   

### ISSUE THREAD

**Issue by mbreclaw** [alanrenouf/vCheck-vSphere#552]
Plugin 23 uses the $VCEventAge variable which is defined in the 42 Windows vCenter Error Event Logs plugin.  If you disable plugin 42 (we do because we use the VCSA), you will not get the vCenter Event Logs in the report.  What we did was copied the $VCEventAge variable to the 00 Connection Plugin.  There may be a better place for it, but it works there.

**Comment by Sneddo** [comment]
Thanks. This has already been fixed in the dev branch, just not merged into master/release
