### ISSUE TITLE
Error when creating the html file at the end ?

### ISSUE THREAD

**Issue by garethhwilson** [alanrenouf/vCheck-vSphere#555]
When i run the script i am getting the following, anyone got any ideas how to fix this ?

Out-File : The given path's format is not supported.
At C:\Scripts\vCheck-vSphere-master\vCheck.ps1:851 char:16
+ $embedReport | Out-File -encoding ASCII -filepath $Filename
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], NotSupportedException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.Ou
   tFileCommand

[10:07:15] ..Displaying HTML results
Invoke-Item : Cannot find path 'C:\Users\GHW-AD~1\AppData\Local\Temp\vcentre.sw
an.ac.uk:443_vCheck_20170425_1007.htm' because it does not exist.
At C:\Scripts\vCheck-vSphere-master\vCheck.ps1:856 char:2
+     Invoke-Item $Filename
+     ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\GHW-AD...170425_1007.h
   tm:String) [Invoke-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.Invok
   eItemCommand

**Comment by Sneddo** [comment]
Looks like we need to strip the port off the vCenter address in the filename, as the colon is causing this issue I'd say.

The simplest solution is to not specify port 443, as this is the default and will work without explicitly putting this in.

I'll have a look at a patch to fix this in the next release.

**Comment by garethhwilson** [comment]
fix by sneddo has worked lovely
