### ISSUE TITLE
46 Missing ESX Patches

### ISSUE THREAD

**Issue by mbreclaw** [alanrenouf/vCheck-vSphere#567]
Tried getting this plugin to work but it would always return $Results as empty even though there were known missing patches.  We added a '+' to line 16 ($Results += $baseline.NotCompliantPatches | ) to fill the array and everything works fine now.  see below:

_**If (Get-PSSnapin Vmware.VumAutomation -ErrorAction SilentlyContinue) {
	foreach($esx in $VMH){
		foreach($baseline in (Get-Compliance -Entity $esx -Detailed | where {$_.Status -eq "NotCompliant"})){
			$Results += $baseline.NotCompliantPatches |
			select @{N="Host";E={$esx.Name}},
			@{N="Baseline";E={$baseline.Baseline.Name}},Name,ReleaseDate,IdByVendor,
			@{N="KB";E={(Select-String "(?<url>http://[\w|\.|/]*\w{1})" -InputObject $_.Description).Matches[0].Groups['url'].Value}}
		}
	}
}_**

**Comment by Sneddo** [comment]
Thanks. This has already been fixed in the dev branch. 

Probably worth merging into master at some point, since development has slowed...
