### ISSUE TITLE
Vcheck : python version 

### ISSUE THREAD

**Issue by saratlingamarla** [alanrenouf/vCheck-vSphere#570]
I would like to create a branch for the python version of vcheck using the pyvmomi official library and Django framework.

**Comment by vScripter** [comment]
@saratlingamarla Sweet! Take a look [here](https://github.com/vCheckReport/vcheck-vsphere-python/tree/master). Feel free to fork/PR into this new repo; I also created a `develop` branch.

**Comment by saratlingamarla** [comment]
thank you!
