### ISSUE TITLE
vCheck fails with Exception calling "ReadNextEvents" with "1" argument(s): "The underlying connection was closed: Could not establish

### ISSUE THREAD

**Issue by rychannel** [alanrenouf/vCheck-vSphere#578]
When I try to run the script it gets to around the 70th check and starts failing with Exception calling "ReadNextEvents" with "1" argument(s): "The underlying connection was closed: Could not establish

**Comment by Sneddo** [comment]
Try having a look at issue #217 and see if it resolves this issue
