### ISSUE TITLE
Various modules dependent on Get-EventPlus

### ISSUE THREAD

**Issue by Scepticalist** [alanrenouf/vCheck-vSphere#583]
As above, this function does not seem to be included in the script - it assumes it is being run by the user e.g. "General Information" plugin

**Comment by Sneddo** [comment]
Get-VIEventPlus is included in the "00 Connection Plugin for vCenter.ps1" script. 

Can you post the output to see if there is some other issue that you are hitting?

**Comment by Scepticalist** [comment]
Hmm, I did another pull of Master yesterday and testing this morning this error is now not occurring. Many thanks anyway.
