### ISSUE TITLE
CBT check and table of contents

### ISSUE THREAD

**Issue by michealo** [alanrenouf/vCheck-vSphere#585]
Noticing that "VMs with CBT disabled" plugin is reporting on VMs that have CBT enabled with the variable "Should CBT be enabled" set to "$true".  Am i misunderstanding that it should be reporting on VMs that instead have CBT disabled?
Changing line 17 to "Where-object {$_.Config.ChangeTrackingEnabled -ne $CBTEnabled}"  flips this

Also, I searched but was unable to find a way to disable the 'table of contents' at top of vCheck report.
Is this easily possible?

Thanks for maintaining this script, Alan and everyone else

**Comment by Sneddo** [comment]
Yep, good catch! Just pushed an update to the dev branch- can you test it out for us? 

There is a setting in the style to show the table of contents or not- $ShowTOC

**Comment by michealo** [comment]
thanks Sneddo, dev copy of '620 CBT Status' looks good.

I changed $ShowTOC in style to $false but table of contents is still appearing in email.
Also could not locate where $ShowTOC is being called out in any other file, unless that's not how it's being handled.  
I renamed the 'Get-ReportTOC' function to something else as a workaround

**Comment by Sneddo** [comment]
Yeah, you're right- it's not actually used. If I get a chance today I'll push a fix for it, otherwise it will be a week or so.

**Comment by Sneddo** [comment]
This should now be fixed
