### ISSUE TITLE
Question: Clarity as default theme?

### ISSUE THREAD

**Issue by alanrenouf** [alanrenouf/vCheck-vSphere#588]
I am nearly ready to add my change to the dev branch for the clarity theme, anyone want to give me a thumbs up or object if i make it the default theme? 

Here is the before and after:

![vcheck_before_and_after](https://user-images.githubusercontent.com/4140758/31302611-e3b832a4-aab7-11e7-891d-9eed871dd62e.png)

**Comment by oscardiaz02** [comment]
Thumbs up.

**Comment by smasterson** [comment]
Two thumbs up

**Comment by stvkpln** [comment]
Do it!

**Comment by alanrenouf** [comment]
Ok added to the dev branch so please download, try it out and let me know if you have issues!

https://github.com/alanrenouf/vCheck-vSphere/tree/dev
