### ISSUE TITLE
one of 5 vCheck Reports is always blank

### ISSUE THREAD

**Issue by mezamoe** [alanrenouf/vCheck-vSphere#592]
Hello, I have a small problem that is bugging me. I set up vCheck successfully for 4 vCenter servers and the html reports are successfully exported to an IIS folder where then they are available for reading. However a fifth report successfully runs and the html file goes to the IIS folder too but it has not data. Header, title and  footer are there but no data. I checked:

- credentials. ok.
- vcheck config. ok (it is exactly the same as the others)
- task scheduler config. ok. (manually same results)

vCenter server 6 U3 as the others. I thought that maybe it's all good and the report is sent blank as per configuration, but if I check manually I find issues that could be found by some of the plugins, like free space on some DS is below the trigger set. This same plugin works well with the other vCenter servers. I'm lost. Also... it never worked since initial setup (a week ago)

**Comment by gregharms** [comment]
Could you describe the process you used to confirm the credentials? 
Do you see a login for those credentials in the vCenter log corresponding to the start time of the task?

When I'm troubleshooting vCheck execution and not content, I pare down the plugins to just 00 Connection Plugin for vCenter, 01 General Information, and 999 VeryLastPlugin Used to Disconnect. When that proves successful, I add other plugins a few at a time so if vCheck hangs/crashes, I have a better chance of isolating the problem plugin (or some edge case it crashed on in my environment).

**Comment by mezamoe** [comment]
many thanks indeed Greg! I was so sure of the credentials in the cred store that I didn´t bother checking if a new logon could be seen  in the vcenter server while the vcheck running. In fact it didn´t show up. And that led me to more accurately check all details and I found a mispelling in the vcenter name in the global variable file :) cheers mate
