### ISSUE TITLE
errors running first plugin 00 connection plugin for vcenter

### ISSUE THREAD

**Issue by bomfra** [alanrenouf/vCheck-vSphere#600]
Hello,

trying to setup vCheck for the first time, but have couples issues.

first is what I use: 

-Powershell V5
-Powercli 6.5.R1 (tried 6.3R1 - same issues)
-vcenter 6.0
-last version of vCheck

I did both, config and guiconfig through vcheck.ps1 and imported the settings.

When running the report, this is what I got, everytime:
`[10:05:59] ..début du calcul Connection settings for vCenter by Alan Renouf v1.20 [1 of 113]
Au caractère D:\vCheck-vSphere-master\Plugins\00 Initialize\00 Connection Plugin for vCenter.ps1:440 : 85
+ ... atory=$true,ValueFromPipelineByPropertyName,ParameterSetName=?Datasto ...
+                                                                  ~
Instruction manquante après « = » dans l’argument nommé.
Au caractère D:\vCheck-vSphere-master\Plugins\00 Initialize\00 Connection Plugin for vCenter.ps1:440 : 85
+ ... atory=$true,ValueFromPipelineByPropertyName,ParameterSetName=?Datasto ...
+                                                                  ~
Parenthèse fermante « ) » manquante dans l’expression.
Au caractère D:\vCheck-vSphere-master\Plugins\00 Initialize\00 Connection Plugin for vCenter.ps1:443 : 53
+         [parameter(Mandatory=$true,ParameterSetName=?Path?)]
+                                                     ~
Instruction manquante après « = » dans l’argument nommé.
Au caractère D:\vCheck-vSphere-master\Plugins\00 Initialize\00 Connection Plugin for vCenter.ps1:443 : 53
+         [parameter(Mandatory=$true,ParameterSetName=?Path?)]
+                                                     ~
Parenthèse fermante « ) » manquante dans l’expression.
Au caractère D:\vCheck-vSphere-master\Plugins\00 Initialize\00 Connection Plugin for vCenter.ps1:440 : 85
+ ... atory=$true,ValueFromPipelineByPropertyName,ParameterSetName=?Datasto ...
+                                                                  ~
Un argument d'attribut doit correspondre à une constante ou à un bloc de script.
Au caractère D:\vCheck-vSphere-master\Plugins\00 Initialize\00 Connection Plugin for vCenter.ps1:443 : 53
+         [parameter(Mandatory=$true,ParameterSetName=?Path?)]
+                                                     ~
Un argument d'attribut doit correspondre à une constante ou à un bloc de script.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingExpressionInNamedArgument`

Any help will be very welcomed.
Thanks,
-Francis

**Comment by bomfra** [comment]
![image](https://user-images.githubusercontent.com/34277552/33614727-2d81d684-d9a6-11e7-9705-b52445fa198c.png)


Screenshot might help a bit more.

**Comment by bomfra** [comment]
![capture](https://user-images.githubusercontent.com/34277552/33614817-5e3716e0-d9a6-11e7-9dbc-b78ba4da7cf4.PNG)

Screenshot might help a bit.

**Comment by omrsafetyo** [comment]
Ah - I ran into this issue as well.  Someone checked in the 00 Connection Plugin For vCenter with funny characters in the Get-HttpDatastoreItem function param block, instead of quotes.

**Comment by omrsafetyo** [comment]
I have created a pull request to address this issue:
https://github.com/alanrenouf/vCheck-vSphere/pull/605

This can be addressed locally if you update the Get-HttpDatastoreItem function in the file you referenced.

The issue is in the param block:

```
        [parameter(Mandatory=$true,ValueFromPipelineByPropertyName,ParameterSetName='Datastore')]
        [Alias('Name')]
        [string]$Datastore,
        [parameter(Mandatory=$true,ParameterSetName='Path')]
```

The first and last lines indicated above are the problem. There are some funny characters around Datastore and Path.  Just replace those with quotes on your local copy of the script and you should be good to go.

**Comment by bomfra** [comment]
Work great! Thanks sir!
