### ISSUE TITLE
Output issue with plugin "79 Find VMs in Uncontrolled Snapshot Mode.ps1"

### ISSUE THREAD

**Issue by flynngw** [alanrenouf/vCheck-vSphere#609]
Hi I have found and fixed an issue with the above plugin
The output from this plugin currently will add lines with numbers, which are string length measurements
This is because line 27 "$eachDS.Name" is adding to the output of this plugin, and listing the string length of each datastore checked
Comment out or remove line 27 "$eachDS.Name", and the issue is resolved

**Comment by omrsafetyo** [comment]
Good find!  I had noticed this yesterday and hadn't had a chance to take a look at it yet.  That does seem to correct the issue.

**Comment by Sneddo** [comment]
Thanks @flynngw, just pushed the change to the dev branch.
