### ISSUE TITLE
$Server variable now stored in "00 Connection Plugin for vCenter.ps1"

### ISSUE THREAD

**Issue by flynngw** [alanrenouf/vCheck-vSphere#613]
I have noticed that the _$Server_ variable is now stored in "_00 Connection Plugin for vCenter.ps1_", and its missing from the "_GlobalVariables.ps1_" file.
Was this intentional?
It just decentralizes the settings somewhat and prevents the auto-sent emails from including the server name unless $Server is manually added into the "_GlobalVariables.ps1_" file also.

**Comment by Sneddo** [comment]
This was an intentional change. It separates the configuration of the vCheck report from the configuration of the data in the report, which make the vCheck core more portable to the other vCheck projects.
