### ISSUE TITLE
Network Redundancy Lost Reporting vmnics not assigned to vSwitches

### ISSUE THREAD

**Issue by CRad14** [alanrenouf/vCheck-vSphere#621]
The way the script is currently written, it reports if the vSwitches are down, but doesn't take into account whether they are assigned to a vSwitch. If they are not assigned to a vSwitch they are of course going to be down. The end of the $pnic line should be:

Where-Object {($_.Status -eq "down") -and ($_.vSwitch -notlike $null)}

I personally haven't forked this yet so I can't fix myself. But I might be forking soon :)

Thanks 

vNoob

**Comment by dstamen** [comment]
definitely do this! i was wondering why unused nics were being reported down

**Comment by Sneddo** [comment]
Good catch, I've updated the dev branch with the fix

**Comment by CRad14** [comment]
Sneddo......

Sorry man, I totally boned  my "fix". They need to have the $_.      not $.

Really not sure how I missed it. It looks like the dev branch got updated with my bad fix. The $_ version should work though :)

**Comment by Sneddo** [comment]
Yep, my mistake. Github formatting stripped it out. I tested it with the underscore, but was lazy and copied and pasted the commit on the web...
