### ISSUE TITLE
Scheduled Task will not run unless user is a domain admin

### ISSUE THREAD

**Issue by jmachado81** [alanrenouf/vCheck-vSphere#631]
We recently removed our vmware service account out of our domain admin group (for obvious reasons), however now the service account is unable to run the vCheck-vSphere scheduled task.  I have made the service account an admin of server, but it doesn't resolve the issue.  I updated vCheck and I am able to run the scheduled task successfully using my personal domain admin account.

The service account is an admin of the vCenter and is listed as an admin whereever Administrator@vsphere.local is listed.

I've tried https://kb.vmware.com/s/article/2050701 in my lab and this doesn't resolve it.  The task will simply continue to run until it times-out or is cancelled. 

We have VSCA 6.5.  Does anybody have any thoughts?

**Comment by Sneddo** [comment]
Try running Powershell as your service account and then run vCheck. This should at least help track down where it is getting stuck.

**Comment by jmachado81** [comment]
It appears this fails at attempting to connect to the vCenter due to below
error.  After going through this site "
http://www.pragmaticio.com/2015/01/vmware-powercli-suppress-vcenter-certificate-warnings/"
things appear to run.  Is this the action i should perform or is there a
better action i could take?

Connect-VIServer : 3/22/2018 9:08:09 AM Connect-VIServer
Error: Invalid server certificate. Use
Set-PowerCLIConfiguration to set the value for the InvalidCertificateAction
option to Prompt if you'd like to connect
once or to add a permanent exception for this server.
Additional Information: Could not establish trust relationship for the
SSL/TLS secure channel with authority
'<vcenter>'.
At line:1 char:1

**Comment by Sneddo** [comment]
So the better action would be to install trusted certificates on your vCenter. Failing that, supressing the warning is the best you can do.
