### ISSUE TITLE
Add Logging Enabled to 102 VM Logging.ps1 

### ISSUE THREAD

**Issue by jmachado81** [alanrenouf/vCheck-vSphere#632]
vCheck-vSphere/Plugins/60 VM/102 VM Logging.ps1

There is lots of documentation out there that states to disable VM Logging to improve performance, which obviously hurts in diagnostics.

Is there a way we can add a check in this "VM Logging" that also displays the "Enable Logging" feature (enabled/disabled or true/false) in the report?

When i run the report the output of this doesn't appear to display the current settings for the VM, default or other in regards to the RotateSize and KeepOld...its just blank if it doesn't match.  I have a VSCA 6.5 and attached an image of the report.

![capture](https://user-images.githubusercontent.com/26902513/37716588-3c6c7a1c-2cf5-11e8-897d-a53825c6ae03.PNG)

**Comment by Sneddo** [comment]
Should be added on dev branch now, you can update the plugin with this version and should have the column as requested.
