### ISSUE TITLE
Exclude datastore from "03 Datastore Information"

### ISSUE THREAD

**Issue by Biomains** [alanrenouf/vCheck-vSphere#638]
What is the format/syntax for excluding several data stores in the "$DatastoreIgnore" variabel?
Same in the "39 Datastore OverAllocation", "$ExcldueDatastores"

I have tried different ways to separate the, but not succeeded yet...

**Comment by mrclschstr** [comment]
You have to use regular expressions. For excluding multiple VMs I use: `"^(VM1|VM2|VM3)"`. You can find further information here: https://www.regular-expressions.info/powershell.html

**Comment by Biomains** [comment]
Thanks!
