### ISSUE TITLE
Hosts Overcommit State

### ISSUE THREAD

**Issue by Mjolinir** [alanrenouf/vCheck-vSphere#649]
Plugin Version 1.4
Running ./vCheck.ps1 from command line

`The variable '$VMMem' cannot be retrieved because it has not been set.`
`At C:\PowerShell\Scripts\vCheck-vSphere-master\Plugins\30 Host\07 Hosts Overcommit State.ps1:33 char:12`
`+       [INT]$VMMem += $_.MemoryMB`
`+            ~~~~~~`
`    + CategoryInfo          : InvalidOperation: (VMMem:String) [], RuntimeException`
`    + FullyQualifiedErrorId : VariableIsUndefined`

**Comment by doogleit** [comment]
This is most likely due to strict mode being enabled in your Powershell session.  Try running "Set-StrictMode -Off" before running vCheck.  It is normally off by default.

**Comment by Mjolinir** [comment]
This was indeed the issue, thank you!
