### ISSUE TITLE
Unable to connect using vCheck 6.25 and VCSA 6.7u1

### ISSUE THREAD

**Issue by lukester1** [alanrenouf/vCheck-vSphere#668]
I have been using vCheck for years and haven't had many issues until about a month ago when I upgraded my VCSA to 6.7u1. Since then I can no longer connect to my vcsa and was curious if anyone else had experienced this and what the potential fix might be?

**Comment by virtualFrog** [comment]
What is the error message you receive? 
Have you saved credentials or are you using the default prompt mechanism?
Can you connect to your VCSA using PowerCLI without running vCheck?
What version of PowerCLI are you running?

_I run a fork of vCheck against 4 different 6.7 U1 VCSAs and have not had any problems._

**Comment by lukester1** [comment]
I updated my version of powercli and that fixed my issue.
