### ISSUE TITLE
Capacity Planning ratio is using vCPUs not pCPUs

### ISSUE THREAD

**Issue by smthbh** [alanrenouf/vCheck-vSphere#676]
It's recommended to calculate the vCPU/pCPU ratio using pCPU cores for ratio calculations, not vCPU threads. (https://communities.vmware.com/thread/572025)

Submitted a fix for this: #677

**Comment by smthbh** [comment]
Submitted a fix for this: #677

**Comment by marcolussetti** [comment]
Just a random passerby but: as #677 was merged, I think is fixed & can be closed.
