### ISSUE TITLE
No Data Retrieved When Vcheck-vSpere runs in TaskScheduler

### ISSUE THREAD

**Issue by haggartymf** [alanrenouf/vCheck-vSphere#701]
Vcheck runs fine interactively within PCLI producting report with data.  However, when running in taskscheduler with the following...

Command: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
Arguments: C:\vCheck\vCheck.ps1

Report is generated with no data.

Thoughts?

**Comment by smasterson** [comment]
I'd check to ensure the user that is specified to execute the scheduled task has permissions to vCenter and access to the PowerCLI module.

**Comment by haggartymf** [comment]
Yes, it does
