### ISSUE TITLE
Getting error while installing vCheck nuget package in visual studio

### ISSUE THREAD

**Issue by mohammedamirk** [alanrenouf/vCheck-vSphere#707]
Could not install package 'vCheck 6.23.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by lucdekens** [comment]
That seems to indicate that you are trying to install the package to a framework higher than 4.5.
Create a project with framework 4.5.2 or target multiple frameworks in the project.

For that last option see [Support multiple .NET versions](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks)

**Comment by mohammedamirk** [comment]
Hi Lucd,
I have succesfully installed the vCheck 6.23.2 from nuget package manager in visual studio. While running this package from PS console. iam getting this error:
![image](https://user-images.githubusercontent.com/43793957/77797924-f02bdb00-7097-11ea-832f-1a2e734688cc.png)

**Comment by lucdekens** [comment]
I just tried that nuget package, and it doesn't look as if could ever work.
There are files missing.

A better solution is to install from this github repo.

**Comment by mohammedamirk** [comment]
Yes. That's what i did. Already install this from github repo.
