### ISSUE TITLE
vCheck Hangs after vCenter Upgrade to ver 7.0.3

### ISSUE THREAD

**Issue by SimonPickard** [alanrenouf/vCheck-vSphere#742]
vCenter was upgraded to ver 7.0.3 yesterday and now vCheck hangs when running the plugin 01 General Information.  I have downloaded the current version with the same results.

Any guidance on where to find the issue?

**Comment by SimonPickard** [comment]
I have left the script running and eventually this plugin reports finished after 52 minutes.  It then hangs on various other plugins including 33 VM CPU Usage which eventually reports finished after almost 11 hours.  In total the report now takes 15 hours where it used to take 15-20 minutes.

**Comment by tgoetheyn** [comment]
It seems I have the same issue.
Stopped working since upgrade to 7.0.3

I didn't let it run 15 hours though

**Comment by shouldabeen77** [comment]
Yes, agreed - any updates / guidance?

**Comment by SimonPickard** [comment]
I have an update on this ticket.

I have run the script again today and have found that it has completed in about 33mins.  I will monitor the scheduled task over the next few days but this issue may have resolved itself.

**Comment by SimonPickard** [comment]
I can confirm that my scheduled task for vCheck ran this morning and completed in 29 minutes.  So for me the issue is resolved.  Although it is taking longer (by about 10-12 minutes)

I will wait and see if @tgoetheyn or @shouldabeen77 respond before closing this issue.

**Comment by shouldabeen77** [comment]
Hmm... it's not resolved for me, but the scheduled task was set to kill after 4 hours.  I've changed that to 24 hours, so I'll see if it runs and just takes longer (normally takes well < 1 hour).  If that doesn't work, I'm going to run it manually and see where it's hanging up.  I've not really delved deeply besides trying to track down the issue here.

**Comment by tgoetheyn** [comment]
Well, I can also confirm the latest run of the vCheck was succesfull.

It does take longer then before:
now: 1378 sec
before: 786 sec

but now it falls within the timeout I set for the script, so that's good for me.

**Comment by shouldabeen77** [comment]
In my environment, the previous working version took 453.79 seconds to run "General Information".  This last run took 47807.03.  So the whole thing is now taking like 14 hours as opposed to around 30 minutes before.  General information is the plugin that seemed to blow up for some reason.

**Comment by shouldabeen77** [comment]
So every time it runs, it runs approximately 1 hour quicker.  It's very very odd.   So now after several iterations it's finishing at 1PM instead of 8pm.

**Comment by shouldabeen77** [comment]
Well, it's really odd, but the pattern has absolutely continued.  One hour earlier every day.  And today it finished at 7am (about what it used to finish at.)  I'll see if tomorrow it finishes *before* it starts.  :-D  Very strange and never did figure it out.

**Comment by SimonPickard** [comment]
This sounds like we all now have no real issue apart from the script taking slightly longer so I will close this issue now.
