### ISSUE TITLE
License Report Blank Expiration Date Fields

### ISSUE THREAD

**Issue by MasterChiefJon** [alanrenouf/vCheck-vSphere#744]
Whenever we run vCheck, the license report shows all of our licenses, but the Information and ExpirationDate fields are all blank.  Otherwise, the report is accurate.  I drilled down into the PowerShell script, and it is looking for a property where the value of $_.key -eq 'expirationDate'.  That key does not exist on any of the licenses in our vCenter 7.0U3 system.

**Comment by rebelinux** [comment]
Happen also in my environment. I believe the issue is related to non expiring licenses.

![vcenter_portal_licenses](https://user-images.githubusercontent.com/1002783/198891196-17ab4bb8-7477-4d59-8863-9fef4648e8c5.png)

**Comment by rebelinux** [comment]
vCheck license report before fix:

![vcheck_licenses_report_before_fix](https://user-images.githubusercontent.com/1002783/198891703-0942f578-3c92-4d7a-90d7-caefb91e36cf.png)

**Comment by rebelinux** [comment]
vCheck license report after fix applied:

![vcheck_licenses_report_after_fix](https://user-images.githubusercontent.com/1002783/198891836-1d3723ae-ae9d-4a27-a452-02945359ab2c.png)
